#!/usr/bin/env python3
"""genbundled.py — generates cpp/internal/bundled/bundled_generated.cpp.

Mirrors tsc/internal/bundled/{libs_generated.go,embed_generated.go}: embeds the
contents of tsc/internal/bundled/libs/*.d.ts into the binary (the equivalent of
Go's //go:embed) so `bundled:///libs/<name>` resolves identically to the oracle.
"""
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LIBS = os.path.join(REPO, "tsc", "internal", "bundled", "libs")
OUT = os.path.join(REPO, "cpp", "internal", "bundled", "bundled_generated.cpp")


def c_escape(data: bytes) -> str:
    # Escapes are emitted per byte so multi-byte UTF-8 sequences round-trip
    # exactly as the on-disk file (Go's //go:embed stores raw bytes).
    out = []
    for b in data:
        if b == 0x5C:
            out.append("\\\\")
        elif b == 0x22:
            out.append('\\"')
        elif b == 0x0A:
            out.append("\\n")
        elif b == 0x0D:
            out.append("\\r")
        elif b == 0x09:
            out.append("\\t")
        elif 32 <= b < 127:
            out.append(chr(b))
        else:
            out.append(f"\\{b:03o}")
    return "".join(out)


def main() -> int:
    names = sorted(os.listdir(LIBS))
    with open(OUT, "w") as f:
        f.write("// Code generated by genbundled.py; DO NOT EDIT.\n")
        f.write("// Mirrors tsc/internal/bundled/libs_generated.go + embed_generated.go.\n\n")
        f.write('#include "internal/bundled/bundled.h"\n\n')
        f.write("namespace tsc::bundled {\n\n")
        f.write("// LibNames — libs_generated.go. All bundled lib files, sorted by name.\n")
        f.write("const std::vector<std::string> LibNames = {\n")
        for n in names:
            f.write(f'\t"{n}",\n')
        f.write("};\n\n")
        f.write("// embeddedContents — embed_generated.go (libs/<name> -> contents).\n")
        f.write("const std::unordered_map<std::string, std::string_view> embeddedContents = {\n")
        for n in names:
            with open(os.path.join(LIBS, n), "rb") as src:
                data = src.read()
            f.write(f'\t{{"libs/{n}", "{c_escape(data)}"}},\n')
        f.write("};\n\n")
        f.write("} // namespace tsc::bundled\n")
    print(f"wrote {OUT} ({len(names)} libs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
