#!/usr/bin/env python3
"""gencpp.py — generate C++ headers from the Go sources in tsc/internal.

Subcommands:
  kinds       -> internal/ast/kind.h          (Kind enum + range constants + name table)
  diagnostics -> internal/diagnostics/messages_generated.h
  unicode     -> internal/stringutil/unicode_tables.h
  nodes       -> internal/ast/nodes_generated.h (flattened node structs + factory + dispatch)

Run from the repository root: python3 cpp/tools/gencpp.py <subcommand>
"""
import re
import sys
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TSC = os.path.join(ROOT, "tsc", "internal")
OUT = os.path.join(ROOT, "cpp", "internal")

HEADER = "// Code generated by cpp/tools/gencpp.py from tsc/internal Go sources; DO NOT EDIT.\n"

# ----------------------------------------------------------------------------
# Kind enum
# ----------------------------------------------------------------------------

def load_kinds():
    """Returns (enum_members, range_consts) from kind_generated.go."""
    src = open(os.path.join(TSC, "ast", "kind_generated.go")).read()
    const_block = re.search(r"const \(\n(.*?)\n\)", src, re.S).group(1)
    kinds = []
    singles = {}
    for line in const_block.split("\n"):
        line = line.strip()
        if not line:
            continue
        if re.match(r"Kind\w+\s*(Kind\s*)?=\s*iota", line):
            kinds.append(re.match(r"(Kind\w+)", line).group(1))
            continue
        if "=" in line:
            m = re.match(r"(Kind\w+)\s*=\s*(.+)", line)
            if m:
                singles[m.group(1)] = m.group(2).strip()
            continue
        m = re.match(r"(Kind\w+)", line)
        if m:
            kinds.append(m.group(1))
    for m in re.finditer(r"const (Kind\w+) = ([^\n]+)", src):
        singles[m.group(1)] = m.group(2).strip()
    return kinds, singles


def gen_kinds():
    kinds, singles = load_kinds()

    # names from kind_stringer_generated.go: `_Kind_name = "UnknownEndOfFile..."`
    strsrc = open(os.path.join(TSC, "ast", "kind_stringer_generated.go")).read()
    name_blob = re.search(r'_Kind_name = "([^"]*)"', strsrc).group(1)
    idx_vals = [int(x) for x in re.search(
        r"_Kind_index = \[\.\.\.\]uint16\{([^}]*)\}", strsrc).group(1).split(",")]
    names = []
    for i in range(len(idx_vals) - 1):
        n = name_blob[idx_vals[i]:idx_vals[i + 1]]
        names.append(n[4:] if n.startswith("Kind") else n)

    lines = [HEADER]
    lines.append("#pragma once\n")
    lines.append("#include <cstdint>\n#include <string_view>\n")
    lines.append("namespace tsc {\n\n")
    lines.append("enum class Kind : int16_t {\n")
    for k in kinds:
        lines.append(f"\t{k[4:]},")  # strip "Kind" prefix -> bare name
    lines.append("};\n\n")
    lines.append("inline constexpr int KindCount = static_cast<int>(Kind::Count);\n\n")
    for name, expr in singles.items():
        if name == "KindCount":
            continue
        kindset = set(kinds)
        cxx = re.sub(
            r"\bKind(\w+)",
            lambda m: f"Kind::{m.group(1)}"
            if "Kind" + m.group(1) in kindset
            else m.group(0),
            expr)
        lines.append(f"inline constexpr Kind {name[4:] + 'Const' if False else name} = {cxx};\n")
    lines.append("\n")
    # name table
    lines.append("inline constexpr std::string_view kKindNames[] = {\n")
    for n in names:
        lines.append(f'\t"{n}",\n')
    lines.append("};\n\n")
    lines.append("inline constexpr std::string_view kindToString(Kind k) {\n")
    lines.append("\treturn kKindNames[static_cast<int>(k)];\n}\n\n")
    lines.append("}  // namespace tsc\n")
    out = os.path.join(OUT, "ast", "kind.h")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("".join(lines))
    print(f"wrote {out} ({len(kinds)} kinds, {len(names)} names)")


# ----------------------------------------------------------------------------
# Diagnostics messages
# ----------------------------------------------------------------------------

def gen_diagnostics():
    src = open(os.path.join(TSC, "diagnostics", "diagnostics_generated.go")).read()
    # var Name = &Message{code: N, category: CategoryX, key: "...", text: "..."}
    pat = re.compile(
        r'var (\w+) = &Message\{\s*code:\s*(-?\d+),\s*category:\s*(\w+),\s*key:\s*"([^"]*)",\s*text:\s*"((?:[^"\\]|\\.)*)"([^}]*)\}',
        re.S)
    entries = []
    for m in pat.finditer(src):
        name, code, cat, key, text, extra = m.groups()
        text = bytes(text, "utf-8").decode("unicode_escape")
        un = "reportsUnnecessary: true" in extra
        dep = "reportsDeprecated: true" in extra
        elided = "elidedInCompatibilityPyramid: true" in extra
        entries.append((name, int(code), cat, key, text, un, dep, elided))
    print(f"parsed {len(entries)} diagnostics")

    def cxxstr(s):
        # Encode each UTF-8 byte; octal escapes are unambiguous (\xNN can
        # greedily absorb a following hex digit, changing the string).
        enc = []
        for b in s.encode("utf-8"):
            if 32 <= b < 127 and b not in (34, 92):
                enc.append(chr(b))
            elif b == 34:
                enc.append('\\"')
            elif b == 92:
                enc.append("\\\\")
            elif b == 10:
                enc.append("\\n")
            elif b == 9:
                enc.append("\\t")
            else:
                enc.append(f"\\{b:03o}")
        return "".join(enc)

    lines = [HEADER]
    lines.append("#pragma once\n")
    lines.append("namespace tsc {\n\n")
    lines.append("// const DiagnosticMessage& name or nullptr; emitted as a flat table.\n")
    lines.append("inline constexpr DiagnosticMessage kDiagnosticMessages[] = {\n")
    for name, code, cat, key, text, un, dep, elided in entries:
        cxxcat = {"CategoryError": "DiagnosticCategory::Error",
                  "CategoryWarning": "DiagnosticCategory::Warning",
                  "CategorySuggestion": "DiagnosticCategory::Suggestion",
                  "CategoryMessage": "DiagnosticCategory::Message"}[cat]
        flags = f", {str(un).lower()}, {str(elided).lower()}, {str(dep).lower()}" if (un or dep or elided) else ""
        lines.append(f'\t{{{code}, {cxxcat}, "{cxxstr(key)}", "{cxxstr(text)}"{flags}}},  // {name}\n')
    lines.append("};\n\n")
    lines.append("// Named accessors matching the Go package-level vars.\n")
    for i, (name, code, cat, key, text, un, dep, elided) in enumerate(entries):
        lines.append(f"inline const DiagnosticMessage* {name} = &kDiagnosticMessages[{i}];\n")
    lines.append("\n}  // namespace tsc\n")
    out = os.path.join(OUT, "diagnostics", "messages_generated.h")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("".join(lines))
    print(f"wrote {out}")


# ----------------------------------------------------------------------------
# Unicode identifier tables
# ----------------------------------------------------------------------------

def gen_unicode():
    src = open(os.path.join(TSC, "stringutil", "identifier_parts_generated.go")).read()
    # unicodeESNextIdentifierStart = &unicode.RangeTable{ R16: []unicode.Range16{...}, R32: ..., LatinOffset: n}
    def parse_rt(varname):
        m = re.search(varname + r"\s*=\s*&unicode\.RangeTable\{(.*?)\}\n", src, re.S)
        body = m.group(1)
        def section(nm):
            m2 = re.search(nm + r":\s*\[\]unicode\.Range\d+\{(.*?)\n\s*\},", body, re.S)
            return [tuple(int(x, 0) for x in t.split(",")) for t in
                    re.findall(r"\{([^}]+)\}", m2.group(1))] if m2 else []
        lat = re.search(r"LatinOffset:\s*(\d+)", body)
        return section("R16"), section("R32"), int(lat.group(1)) if lat else 0

    lines = [HEADER, "#pragma once\n", "#include <cstdint>\n\nnamespace tsc {\n\n"]
    for var, cxx in [("unicodeESNextIdentifierStart", "kIdentifierStart"),
                     ("unicodeESNextIdentifierPart", "kIdentifierPart")]:
        r16, r32, lat = parse_rt(var)
        lines.append(f"inline constexpr uint16_t {cxx}R16[][3] = {{\n")
        for lo, hi, stride in r16:
            lines.append(f"\t{{{lo}, {hi}, {stride}}},\n")
        lines.append("};\n")
        lines.append(f"inline constexpr uint32_t {cxx}R32[][3] = {{\n")
        for lo, hi, stride in r32:
            lines.append(f"\t{{{lo}, {hi}, {stride}}},\n")
        lines.append("};\n")
        lines.append(f"inline constexpr int {cxx}LatinOffset = {lat};\n\n")
        print(f"{var}: {len(r16)} r16, {len(r32)} r32, latinOffset={lat}")
    lines.append("}  // namespace tsc\n")
    out = os.path.join(OUT, "stringutil", "unicode_tables.h")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("".join(lines))
    print(f"wrote {out}")


# ----------------------------------------------------------------------------
# Node structs — the big one
# ----------------------------------------------------------------------------

# Go builtin/foreign types that are NOT node structs (map to C++ directly or as
# forward-declared pointers)
GO_VALUE_TYPES = {
    "string": "std::string",
    "bool": "bool",
    "core.TextRange": "::tsc::TextRange",
    "core.LanguageVariant": "::tsc::LanguageVariant",
    "core.ScriptKind": "::tsc::ScriptKind",
    "core.Tristate": "::tsc::Tristate",
    "core.ScriptTarget": "::tsc::ScriptTarget",
    "core.ResolutionMode": "::tsc::ResolutionMode",
    "::tsc::TokenFlags": "::tsc::TokenFlags",
    "::tsc::NodeFlags": "::tsc::NodeFlags",
    "::tsc::ModifierFlags": "::tsc::ModifierFlags",
    "::tsc::CheckFlags": "::tsc::CheckFlags",
    "::tsc::FunctionFlags": "::tsc::FunctionFlags",
    "::tsc::SubtreeFacts": "::tsc::SubtreeFacts",
    "LanguageFeatureMinimumTarget": "int",
    "::tsc::LanguageVariant": "::tsc::LanguageVariant",
    "::tsc::ScriptKind": "::tsc::ScriptKind",
    "::tsc::Tristate": "::tsc::Tristate",
    "::tsc::ScriptTarget": "::tsc::ScriptTarget",
    "::tsc::SourceFileParseOptions": "::tsc::SourceFileParseOptions",
    "::tsc::ExternalModuleIndicatorOptions": "::tsc::ExternalModuleIndicatorOptions",
    "::tsc::CommentDirectiveKind": "::tsc::CommentDirectiveKind",
    "::tsc::CommentDirective": "::tsc::CommentDirective",
    "::tsc::CommentRange": "::tsc::CommentRange",
    "::tsc::Pragma": "::tsc::Pragma",
    "::tsc::FileReference": "::tsc::FileReference",
    "::tsc::CheckJsDirective": "::tsc::CheckJsDirective",
    "::tsc::PatternAmbientModule": "::tsc::PatternAmbientModule",
    "tspath.Path": "std::string",
    "xxh3.Uint128": "::tsc::Uint128",
    "core.TextPos": "::tsc::TextPos",
    "::tsc::TextPos": "::tsc::TextPos",
    "core.ModuleKind": "::tsc::ModuleKind",
    "::tsc::ModuleKind": "::tsc::ModuleKind",
    "::tsc::ResolutionMode": "::tsc::ResolutionMode",
    "ScriptReferenceHost": "void*",
    "::tsc::CommentDirective": "::tsc::CommentDirective",
    "::tsc::MappedDiagnosticDirective": "::tsc::MappedDiagnosticDirective",
    "::tsc::SourceFileMetaData": "::tsc::SourceFileMetaData",
    "::tsc::Kind": "::tsc::Kind",
    "int": "int32_t",
    "int32": "int32_t",
    "int64": "int64_t",
    "uint32": "uint32_t",
    "uint64": "uint64_t",
    "atomic.Uint32": "CopyableAtomic<uint32_t>",
    "atomic.Uint64": "CopyableAtomic<uint64_t>",
    "atomic.Bool": "CopyableAtomic<bool>",
    "sync.Mutex": "std::mutex",
    "sync.RWMutex": "std::shared_mutex",
    "sync.Once": "::tsc::OnceFlag",
    "::tsc::SymbolTable": "::tsc::SymbolTable",
}

NON_NODE_PTR = {
    "Symbol", "FlowNode", "Diagnostic", "FileReference", "CheckJsDirective",
    "NodeFactory", "PositionMap", "ContentMapperSourceFileInfo", "ModuleResolutionKind",
    "TokenCacheKey", "RepopulateDiagnosticInfo", "SourceFileMetaData",
    "SymbolId", "SymbolLinks", "DeclarationBitMaps", "SymbolFormatFlags",
    "ModifierListCache", "QueuedMap", "Extension",
}

CPP_RESERVED = {
    "operator": "op", "template": "template_", "new": "new_", "delete": "delete_",
    "this": "self", "class": "class_", "namespace": "namespace_", "typename": "typename_",
    "virtual": "virtual_", "switch": "switch_", "case": "case_", "default": "default_",
    "register": "register_", "typeid": "typeid_", "and": "and_", "or": "or_", "not": "not_",
    "xor": "xor_", "signed": "signed_", "unsigned": "unsigned_", "long": "long_",
    "short": "short_", "float": "float_", "double": "double_", "char": "char_",
    "int": "int_", "bool": "bool_", "union": "union_", "enum": "enum_", "struct": "struct_",
    "friend": "friend_", "inline": "inline_", "const": "const_", "static": "static_",
    "extern": "extern_", "auto": "auto_", "sizeof": "sizeof_", "return": "return_",
    "if": "if_", "else": "else_", "for": "for_", "while": "while_", "do": "do_",
    "break": "break_", "continue": "continue_", "goto": "goto_", "try": "try_",
    "catch": "catch_", "throw": "throw_", "public": "public_", "private": "private_",
    "protected": "protected_", "constexpr": "constexpr_", "nullptr": "nullptr_",
    "export": "export_", "import": "import_", "module": "module_", "requires": "requires_",
    "concept": "concept_", "co_await": "co_await_", "co_return": "co_return_",
    "co_yield": "co_yield_", "mutable": "mutable_", "volatile": "volatile_",
    "wchar_t": "wchar_t_", "char8_t": "char8_t_", "char16_t": "char16_t_",
    "char32_t": "char32_t_", "true": "true_", "false": "false_",
    "type": "type_",  # not reserved in C++ but `type` reads badly; keep it though:
}
# `type` IS a legal C++ identifier; keep it legal:
del CPP_RESERVED["type"]


def sanitize(name):
    return CPP_RESERVED.get(name, name)


# Hand-maintained ports of ast.go helpers the generator cannot auto-translate
# (non-kind-check predicates and the AccessKind machinery). Emitted verbatim at
# the end of nodes_generated.h. Keep in sync with tsc/internal/ast/ast.go.
MANUAL_AST_HELPERS = """
// ---------------------------------------------------------------------------
// Hand-maintained ports of the non-trivial ast.go helpers (accessKind, the
// write-access family, GetDeclarationFromName, and the data-presence
// predicates). The generator only auto-ports pure kind-check predicates; these
// are emitted verbatim by gencpp.py. Keep in sync with
// tsc/internal/ast/ast.go.
// ---------------------------------------------------------------------------

// isAssignmentOperator is defined later in ast.h, after this header's
// inclusion point; forward-declared so accessKind can call it.
bool isAssignmentOperator(Kind kind);

// AccessKind — ast.go:1494
enum class AccessKind : int32_t {
	AccessKindRead,      // Only reads from a variable
	AccessKindWrite,     // Only writes to a variable without ever reading it
	AccessKindReadWrite, // Reads from and writes to a variable
};

// reverseAccessKind — ast.go:1484
inline AccessKind reverseAccessKind(AccessKind a) {
	switch (a) {
	case AccessKind::AccessKindRead:
		return AccessKind::AccessKindWrite;
	case AccessKind::AccessKindWrite:
		return AccessKind::AccessKindRead;
	case AccessKind::AccessKindReadWrite:
		return AccessKind::AccessKindReadWrite;
	}
	TSC_UNREACHABLE("Unhandled case in reverseAccessKind");
}

// accessKind — ast.go:1424
inline AccessKind accessKind(Node* node) {
	Node* parent = node->parent;
	if (parent == nullptr) {
		return AccessKind::AccessKindRead;
	}
	switch (parent->kind) {
	case Kind::ParenthesizedExpression:
		return accessKind(parent);
	case Kind::PrefixUnaryExpression: {
		Kind op = parent->as<PrefixUnaryExpression>()->Operator;
		if (op == Kind::PlusPlusToken || op == Kind::MinusMinusToken) {
			return AccessKind::AccessKindReadWrite;
		}
		return AccessKind::AccessKindRead;
	}
	case Kind::PostfixUnaryExpression: {
		Kind op = parent->as<PostfixUnaryExpression>()->Operator;
		if (op == Kind::PlusPlusToken || op == Kind::MinusMinusToken) {
			return AccessKind::AccessKindReadWrite;
		}
		return AccessKind::AccessKindRead;
	}
	case Kind::BinaryExpression:
		if (parent->as<BinaryExpression>()->Left == node) {
			Node* opTok = parent->as<BinaryExpression>()->OperatorToken;
			if (isAssignmentOperator(opTok->kind)) {
				if (opTok->kind == Kind::EqualsToken) {
					return AccessKind::AccessKindWrite;
				}
				return AccessKind::AccessKindReadWrite;
			}
		}
		return AccessKind::AccessKindRead;
	case Kind::PropertyAccessExpression:
		if (parent->name() != node) {
			return AccessKind::AccessKindRead;
		}
		return accessKind(parent);
	case Kind::PropertyAssignment: {
		AccessKind parentAccess = accessKind(parent->parent);
		// In `({ x: varname }) = { x: 1 }`, the left `x` is a read, the right
		// `x` is a write.
		if (node == parent->as<PropertyAssignment>()->name) {
			return reverseAccessKind(parentAccess);
		}
		return parentAccess;
	}
	case Kind::ShorthandPropertyAssignment:
		// Assume it's the local variable being accessed, since we don't check
		// public properties for --noUnusedLocals.
		if (node ==
		    parent->as<ShorthandPropertyAssignment>()
		        ->ObjectAssignmentInitializer) {
			return AccessKind::AccessKindRead;
		}
		return accessKind(parent->parent);
	case Kind::ArrayLiteralExpression:
		return accessKind(parent);
	case Kind::ForInStatement:
	case Kind::ForOfStatement:
		if (node == parent->as<ForInOrOfStatement>()->Initializer) {
			return AccessKind::AccessKindWrite;
		}
		return AccessKind::AccessKindRead;
	default:
		return AccessKind::AccessKindRead;
	}
}

// IsWriteOnlyAccess — ast.go:1268
inline bool isWriteOnlyAccess(Node* node) {
	return accessKind(node) == AccessKind::AccessKindWrite;
}
inline bool isWriteOnlyAccess(const Node* node) {
	return isWriteOnlyAccess(const_cast<Node*>(node));
}

// IsWriteAccess — ast.go:1272
inline bool isWriteAccess(Node* node) {
	return accessKind(node) != AccessKind::AccessKindRead;
}
inline bool isWriteAccess(const Node* node) {
	return isWriteAccess(const_cast<Node*>(node));
}

// IsArrayLiteralOrObjectLiteralDestructuringPattern — ast.go:1406
inline bool isArrayLiteralOrObjectLiteralDestructuringPattern(Node* node) {
	if (!(isArrayLiteralExpression(node) || isObjectLiteralExpression(node))) {
		return false;
	}
	Node* parent = node->parent;
	// [a,b,c] from:
	// [a, b, c] = someExpression;
	if (isBinaryExpression(parent) &&
	    parent->as<BinaryExpression>()->Left == node &&
	    parent->as<BinaryExpression>()->OperatorToken->kind ==
	        Kind::EqualsToken) {
		return true;
	}
	// [a, b, c] from:
	// for([a, b, c] of expression)
	if (isForOfStatement(parent) && parent->initializer() == node) {
		return true;
	}
	// {x, a: {a, b, c} } = someExpression
	if (isPropertyAssignment(parent)) {
		return isArrayLiteralOrObjectLiteralDestructuringPattern(parent->parent);
	}
	// [a, b, c] of
	// [x, [a, b, c] ] = someExpression
	return isArrayLiteralOrObjectLiteralDestructuringPattern(parent);
}
inline bool isArrayLiteralOrObjectLiteralDestructuringPattern(
    const Node* node) {
	return isArrayLiteralOrObjectLiteralDestructuringPattern(
	    const_cast<Node*>(node));
}

// GetDeclarationFromName — ast.go:1281
inline Node* getDeclarationFromName(Node* name) {
	if (name == nullptr || name->parent == nullptr) {
		return nullptr;
	}
	Node* parent = name->parent;
	switch (name->kind) {
	case Kind::StringLiteral:
	case Kind::NoSubstitutionTemplateLiteral:
	case Kind::NumericLiteral:
		if (isComputedPropertyName(parent)) {
			return parent->parent;
		}
		[[fallthrough]];
	case Kind::Identifier:
		if (isDeclaration(parent)) {
			if (parent->name() == name) {
				return parent;
			}
			return nullptr;
		}
		if (isQualifiedName(parent)) {
			Node* tag = parent->parent;
			if (isJSDocParameterTag(tag) && tag->name() == parent) {
				return tag;
			}
			return nullptr;
		}
		{
			Node* binExp = parent->parent;
			if (isBinaryExpression(binExp) &&
			    getAssignmentDeclarationKind(binExp) != JSDeclarationKind::None) {
				// (binExp.left as BindableStaticNameExpression).symbol ||
				// binExp.symbol
				bool leftHasSymbol =
				    binExp->as<BinaryExpression>()->Left != nullptr &&
				    binExp->as<BinaryExpression>()->Left->symbol() != nullptr;
				if (leftHasSymbol || binExp->symbol() != nullptr) {
					if (getNameOfDeclaration(binExp) == name) {
						return binExp;
					}
				}
			}
		}
		break;
	case Kind::PrivateIdentifier:
		if (isDeclaration(parent) && parent->name() == name) {
			return parent;
		}
		break;
	}
	return nullptr;
}

// declarationIsWriteAccess — ast.go:1327
inline bool declarationIsWriteAccess(Node* decl) {
	if (decl == nullptr) {
		return false;
	}
	// Consider anything in an ambient declaration to be a write access since it
	// may be coming from JS.
	if ((decl->flags & NodeFlagsAmbient) != 0) {
		return true;
	}

	switch (decl->kind) {
	case Kind::BinaryExpression:
	case Kind::BindingElement:
	case Kind::ClassDeclaration:
	case Kind::ClassExpression:
	case Kind::DefaultKeyword:
	case Kind::EnumDeclaration:
	case Kind::EnumMember:
	case Kind::ExportSpecifier:
	case Kind::ImportClause: // default import
	case Kind::ImportEqualsDeclaration:
	case Kind::ImportSpecifier:
	case Kind::InterfaceDeclaration:
	case Kind::JSDocCallbackTag:
	case Kind::JSDocTypedefTag:
	case Kind::JsxAttribute:
	case Kind::ModuleDeclaration:
	case Kind::NamespaceExportDeclaration:
	case Kind::NamespaceImport:
	case Kind::NamespaceExport:
	case Kind::Parameter:
	case Kind::ShorthandPropertyAssignment:
	case Kind::TypeAliasDeclaration:
	case Kind::JSTypeAliasDeclaration:
	case Kind::TypeParameter:
		return true;

	case Kind::PropertyAssignment:
		// In `({ x: y } = 0);`, `x` is not a write access.
		return !isArrayLiteralOrObjectLiteralDestructuringPattern(decl->parent);

	case Kind::FunctionDeclaration:
	case Kind::FunctionExpression:
	case Kind::Constructor:
	case Kind::MethodDeclaration:
	case Kind::GetAccessor:
	case Kind::SetAccessor:
		// functions considered write if they provide a value (have a body)
		switch (decl->kind) {
		case Kind::FunctionDeclaration:
			return decl->as<FunctionDeclaration>()->Body != nullptr;
		case Kind::FunctionExpression:
			return decl->as<FunctionExpression>()->Body != nullptr;
		case Kind::Constructor:
			return decl->as<ConstructorDeclaration>()->Body != nullptr;
		case Kind::MethodDeclaration:
			return decl->as<MethodDeclaration>()->Body != nullptr;
		case Kind::GetAccessor:
			return decl->as<GetAccessorDeclaration>()->Body != nullptr;
		case Kind::SetAccessor:
			return decl->as<SetAccessorDeclaration>()->Body != nullptr;
		}
		return false;

	case Kind::VariableDeclaration:
	case Kind::PropertyDeclaration: {
		// variable/property write if initializer present or is in catch clause
		bool hasInit;
		if (decl->kind == Kind::VariableDeclaration) {
			hasInit = decl->as<VariableDeclaration>()->Initializer != nullptr;
		} else {
			hasInit = decl->as<PropertyDeclaration>()->Initializer != nullptr;
		}
		return hasInit || isCatchClause(decl->parent);
	}

	case Kind::MethodSignature:
	case Kind::PropertySignature:
	case Kind::JSDocPropertyTag:
	case Kind::JSDocParameterTag:
		return false;

	default:
		TSC_UNREACHABLE("Unhandled case in declarationIsWriteAccess");
	}
}

// IsWriteAccessForReference — ast.go:1276
inline bool isWriteAccessForReference(Node* node) {
	Node* decl = getDeclarationFromName(node);
	return (decl != nullptr && declarationIsWriteAccess(decl)) ||
	       node->kind == Kind::DefaultKeyword || isWriteAccess(node);
}
inline bool isWriteAccessForReference(const Node* node) {
	return isWriteAccessForReference(const_cast<Node*>(node));
}

// IsDeclarationNode — ast.go:1505 (node.DeclarationData() != nil)
inline bool isDeclarationNode(const Node* node) {
	return const_cast<Node*>(node)->declarationData().symbol != nullptr;
}
inline bool isDeclarationNode(Node* node) {
	return node->declarationData().symbol != nullptr;
}

// IsLocalsContainer — ast.go:1532 (node.LocalsContainerData() != nil)
inline bool isLocalsContainer(const Node* node) {
	return const_cast<Node*>(node)->localsContainerData().locals != nullptr;
}
inline bool isLocalsContainer(Node* node) {
	return node->localsContainerData().locals != nullptr;
}

"""


def parse_structs(*files):
    """Parse `type X struct { ... }` and `type X = Y` aliases; returns
    (structs: {name: [(field_name, go_type, is_embedded)]}, aliases: {name: target}).
    Embedded fields appear as (None, type_name, True)."""
    structs = {}
    aliases = {}
    struct_pat = re.compile(r"^type (\w+) struct\s*\{", re.M)
    for path in files:
        src = open(path).read()
        for m in struct_pat.finditer(src):
            name = m.group(1)
            i = m.end()
            depth = 1
            while depth > 0:
                c = src[i]
                if c == "{":
                    depth += 1
                elif c == "}":
                    depth -= 1
                i += 1
            body = src[m.end():i - 1]
            fields = []
            for line in body.split("\n"):
                line = line.strip()
                if not line or line.startswith("//"):
                    continue
                line = re.sub(r"//.*$", "", line).strip()  # strip trailing comment
                if not line:
                    continue
                line = re.sub(r"`[^`]*`", "", line).strip()  # strip tags
                parts = line.split(None, 1)
                if len(parts) == 1:
                    fields.append((None, parts[0], True))  # embedded
                else:
                    fname, ftype = parts[0], parts[1].strip()
                    # multi-name fields `a, b T`
                    names = [n.strip() for n in fname.split(",")]
                    for n in names:
                        fields.append((n, ftype, False))
            structs[name] = fields
        # standalone `type X = Y` aliases
        for m in re.finditer(r"^type (\w+) = (\w+)", src, re.M):
            aliases[m.group(1)] = m.group(2).strip()
        # `type ( X = Y ... )` blocks
        for bm in re.finditer(r"^type \(\n(.*?)\n\)", src, re.S | re.M):
            for am in re.finditer(r"^\s*(\w+)\s*=\s*(\w+)", bm.group(1), re.M):
                aliases[am.group(1)] = am.group(2).strip()
    return structs, aliases


NODE_CORE_FIELDS = {"Kind", "Flags", "Loc", "id", "Parent", "data"}


def flatten(structs, name, seen=None):
    """DFS-expand embedded bases; dedupe by field name. The `Node` core
    fields are skipped because C++ node structs inherit `struct Node`."""
    out = []
    have = set()
    def go(n):
        for fname, ftype, emb in structs.get(n, []):
            if emb:
                base = ftype.lstrip("*")
                if base in structs:
                    go(base)
                else:
                    # embedded external (e.g. NodeBase chain end) -> keep as field
                    if base not in have:
                        have.add(base)
                        out.append((base.lower() + "_", base, False))
            else:
                if n == "Node" or fname in NODE_CORE_FIELDS:
                    continue
                if fname in have:
                    continue
                have.add(fname)
                out.append((fname, ftype, False))
    go(name)
    return out


def go_type_to_cpp(t, node_structs, aliases):
    """Map a Go type to a C++ type. Pointers to node-ish things -> Node* /
    NodeList* / ModifierList*; pointers to foreign structs -> X*; slices ->
    std::vector<>; maps -> std::unordered_map<>."""
    t = t.strip()
    # resolve aliases of the form `type X = T`
    def resolve(a):
        while a in aliases:
            a = aliases[a]
        return a
    if t.startswith("[]"):
        inner = go_type_to_cpp(t[2:], node_structs, aliases)
        return f"std::vector<{inner}>"
    if t.startswith("map[") or t.startswith("collections.OrderedMap[") or \
       t.startswith("sync.Map["):
        m = re.match(r"(?:map|collections\.OrderedMap|sync\.Map)\[([^\]]+)\](.+)$", t)
        k = go_type_to_cpp(m.group(1), node_structs, aliases)
        v = go_type_to_cpp(m.group(2), node_structs, aliases)
        return f"std::unordered_map<{k}, {v}>"
    if t.startswith("collections.Set[") or t.startswith("collections.SetOrStar["):
        inner = go_type_to_cpp(t[t.index("[") + 1:-1], node_structs, aliases)
        return f"std::unordered_set<{inner}>"
    if t.startswith("collections.Heap["):
        inner = go_type_to_cpp(t[t.index("[") + 1:-1], node_structs, aliases)
        return f"std::vector<{inner}>"
    if t == "any" or t == "interface{}":
        return "void*"
    if t.startswith("*"):
        base = resolve(t[1:]).lstrip("*")
        if base == "ModifierList":
            return "::tsc::ModifierList*"
        if base.endswith("List") or base == "NodeList":
            return "::tsc::NodeList*"
        if base in NON_NODE_PTR:
            return "::tsc::" + base + "*"
        if base == "Node" or base in node_structs or base.endswith("Node") or \
           base.endswith("Token") or base.endswith("Literal") or \
           base in ("DeclarationName", "EntityName", "EntityNameExpression",
                    "BindingPattern", "BindingName", "PropertyName", "TypeNode",
                    "Expression", "Statement", "ModuleName", "ModuleExportName",
                    "ForInitializer", "LiteralLikeNode", "TemplateLiteralLikeNode",
                    "JsxAttributeLike", "JsxAttributeValue", "JsxChild",
                    "JsxTagNameExpression", "ClassLikeDeclaration", "AssertionExpression",
                    "NamedMember", "ModifierLike", "ClassLikeBody", "BlockLike",
                    "VariableLikeDeclaration", "SignatureDeclaration",
                    "EnumMember", "ModuleBody", "AccessorDeclaration", "Modifier",
                    "ConciseBody", "FunctionBody", "IncrementExpression",
                    "JSDocComment", "JSDocTag", "ObjectLiteralElementLike"):
            return "::tsc::Node*"
        # unknown pointer type — emit a forward-declared struct pointer
        return "::tsc::" + base + "*"
    base = resolve(t)
    if base.startswith("collections.Set["):
        inner = go_type_to_cpp(base[base.index("[") + 1:-1], node_structs, aliases)
        return f"std::unordered_set<{inner}>"
    if base in GO_VALUE_TYPES:
        return GO_VALUE_TYPES[base]
    if base.endswith("SyntaxKind") or base == "SyntaxKind":
        return "Kind"
    if base.endswith("List") and base != "ModifierList":
        return "::tsc::NodeList"
    if base in node_structs or base == "Node":
        return "::tsc::Node"
    if base == "ModifierList":
        return "::tsc::ModifierList"
    if base[:1].isupper():
        return "::tsc::" + base
    return base


def gen_nodes():
    gendir = os.path.join(TSC, "ast")
    structs, aliases = parse_structs(os.path.join(gendir, "ast.go"),
                                     os.path.join(gendir, "ast_generated.go"))
    src_all = open(os.path.join(gendir, "ast.go")).read() + "\n" + \
              open(os.path.join(gendir, "ast_generated.go")).read()
    # strip // comments so doc text can't fake a declaration match
    src_all = re.sub(r"//[^\n]*", "", src_all)

    # Which structs are node payloads?  Those reachable via newNode(Kind*, data)
    # where data's static type is the struct. Find `data := f.<arena>.New()` and
    # `data := &X{}` inside each New* factory, plus the arena decls.
    arena_types = dict(re.findall(r"(\w+)[ \t]+core\.Arena\[(\w+)\]", src_all))
    node_structs = set()
    factory_methods = {}   # method name -> (kind_const, struct_name, [args], {field: arg})
    new_pat = re.compile(
        r"func \(f \*NodeFactory\) (New\w+)\((.*?)\) \*Node \{\n(.*?)\n\}", re.S)
    for m in new_pat.finditer(src_all):
        fname, args_src, body = m.group(1), m.group(2), m.group(3)
        dm = re.search(r"data := f\.(\w+)\.New\(\)", body)
        if dm:
            sname = arena_types.get(dm.group(1))
            if not sname:
                continue
        else:
            dm = re.search(r"data := &(\w+)\{\}", body)
            if not dm:
                continue
            sname = dm.group(1)
        km = re.search(r"f\.newNode\((\w+)", body)
        if not km:
            continue
        kind = km.group(1)
        if kind == "kind":
            # kind passed as a parameter — collect concrete kinds from call sites
            kind = None
        # parse args
        args = []
        for argm in re.finditer(r"(\w+)\s+([^\s,\)]+(?:\[\]\*?\w+)?)", args_src):
            args.append((argm.group(1), argm.group(2)))
        # field assignments data.X = expr
        assigns = re.findall(r"data\.(\w+) = ([^\n]+)", body)
        # post-construction node assignments, e.g. `node.Flags = flags`
        node_assigns = re.findall(r"node\.(\w+) (\|=|&=|\^=|=) ([^\n]+)", body)
        node_structs.add(sname)
        factory_methods[fname] = (kind, sname, args, assigns, node_assigns)

    # Also catch `f.textCount++` markers (identifiers / literals) — record them.
    textcount = {}
    for m in new_pat.finditer(src_all):
        textcount[m.group(1)] = "f.textCount++" in m.group(3)

    # Is* predicates (ast.go + ast_generated.go — pure kind checks)
    predicates = []
    seen_pred = set()
    for m in re.finditer(
            r"func (Is\w+)\(node \*Node\) bool \{\n(.*?)\n\}", src_all, re.S):
        if m.group(1) not in seen_pred:
            seen_pred.add(m.group(1))
            predicates.append((m.group(1), m.group(2).strip()))

    # ForEachChild bodies per struct
    foreach = {}
    for m in re.finditer(
            r"func \(node \*(\w+)\) ForEachChild\(v Visitor\) bool \{\n(.*?)\n\}",
            src_all, re.S):
        sname, body = m.group(1), m.group(2)
        calls = re.findall(r"(visitModifiers|visitNodeList|visit)\(v, node\.(\w+)\)", body)
        foreach[sname] = calls

    # forEachChild_<Struct> helpers a ForEachChild method may delegate to
    # (e.g. JSDocParameterOrPropertyTag, whose visit order depends on
    # IsNameFirst). The helper body is a boolean expression over visit calls
    # and node fields; emit a translated verbatim return-expression.
    foreach_helpers = {}
    for m in re.finditer(
            r"func forEachChild_(\w+)\(node \*(\w+), v Visitor\) bool \{\n(.*?)\n\}",
            src_all, re.S):
        foreach_helpers[m.group(2)] = m.group(3)

    # Update* factory methods (Go: func (f *NodeFactory) UpdateX(node *X, ...) *Node)
    upd_methods = {}   # sname -> (uname, [(argname, gtype)], body)
    for m in re.finditer(
            r"func \(f \*NodeFactory\) (Update\w+)\(node \*(\w+), (.*?)\) \*Node \{\n(.*?)\n\}",
            src_all, re.S):
        uname, sname, args_src, body = m.groups()
        args = []
        for argm in re.finditer(r"(\w+)\s+([^\s,\)]+(?:\[\]\*?\w+)?)", args_src):
            args.append((argm.group(1), argm.group(2)))
        upd_methods[sname] = (uname, args, body)

    # VisitEachChild bodies per struct (Go: func (node *X) VisitEachChild(v *NodeVisitor) *Node)
    vec_methods = {}
    for m in re.finditer(
            r"func \(node \*(\w+)\) VisitEachChild\(v \*NodeVisitor\) \*Node \{\n(.*?)\n\}",
            src_all, re.S):
        vec_methods[m.group(1)] = m.group(2)

    # visitEachChild_* helpers some VisitEachChild bodies delegate to
    vec_helpers = {}
    for m in re.finditer(
            r"func visitEachChild_(\w+)\(node \*(\w+), v \*NodeVisitor\) \*Node \{\n(.*?)\n\}",
            src_all, re.S):
        vec_helpers[m.group(2)] = m.group(3)

    # Clone bodies per struct (Go: func (node *X) Clone(f NodeFactoryCoercible) *Node)
    clone_methods = {}
    for m in re.finditer(
            r"func \(node \*(\w+)\) Clone\(f NodeFactoryCoercible\) \*Node \{\n(.*?)\n\}",
            src_all, re.S):
        clone_methods[m.group(1)] = m.group(2)

    # Simple accessors: func (node *X) Foo() *T { return node.f }
    accessors = {}  # accessor -> {struct: (ret_type, field)}
    acc_pat = re.compile(
        r"func \(node \*(\w+)\) (\w+)\(\) ([^\s{]+) \{\n\treturn node\.(\w+)\s*\n\}")
    for m in acc_pat.finditer(src_all):
        sname, meth, ret, field = m.groups()
        accessors.setdefault(meth, {})[sname] = (ret, field)

    # kind -> struct map (a struct may serve multiple kinds). Methods taking
    # `kind` as a parameter are resolved by scanning every Go caller.
    all_src = ""
    for dirpath, _, fns in os.walk(TSC):
        for fn in fns:
            if fn.endswith(".go"):
                all_src += open(os.path.join(dirpath, fn)).read()
    struct_kinds = {}   # struct -> [kind,...]
    for fname, (kind, sname, args, assigns, node_assigns) in \
            factory_methods.items():
        struct_kinds.setdefault(sname, [])
        ks = [kind] if kind else []
        if kind is None:
            for cm in re.finditer(fname + r"\((?:ast\.)?(Kind\w+)", all_src):
                ks.append(cm.group(1))
        for k in ks:
            if k and k not in struct_kinds[sname]:
                struct_kinds[sname].append(k)

    # Variable-kind factories (e.g. NewJSDocParameterOrPropertyTag(kind, ...))
    # can't be bound by scanning callers; instead read the authoritative
    # kind -> struct mapping out of the generated Node.ForEachChild dispatch:
    #   case KindA, KindB:
    #       return n.data.(*StructName).ForEachChild(v)
    for cm in re.finditer(
            r"case ((?:ast\.)?Kind\w+(?:,\s*(?:ast\.)?Kind\w+)*)\s*:\s*\n"
            r"\s*return n\.data\.\(\*?(\w+)\)",
            all_src):
        kinds_str, sname = cm.group(1), cm.group(2)
        if sname not in node_structs:
            continue
        for k in re.findall(r"Kind\w+", kinds_str):
            if k not in struct_kinds.get(sname, []):
                struct_kinds.setdefault(sname, []).append(k)

    # Token covers every syntax-token kind (keywords, punctuation, operators)
    # — Go creates them via NewToken(kind) with the kind passed through
    # variables, so call-site scanning only finds literals. The authoritative
    # set is subtractive: every Kind not claimed by another struct is a token.
    # Trivia/sentinel kinds in the enum are never realized as nodes, and
    # Token::computeSubtreeFacts returns None for them anyway, so over-
    # assigning them here is harmless.
    if "Token" in node_structs:
        claimed = set()
        for sname, ks in struct_kinds.items():
            if sname != "Token":
                claimed.update(ks)
        # SyntaxList nodes are produced by newNodeList, not NewToken.
        claimed.add("KindSyntaxList")
        for k in sorted(load_kinds()[0]):
            if k not in claimed and k not in struct_kinds.get("Token", []):
                struct_kinds.setdefault("Token", []).append(k)

    print(f"{len(node_structs)} node structs, {len(factory_methods)} factory methods, "
          f"{len(predicates)} predicates, {len(foreach)} forEachChild, "
          f"{len(accessors)} accessors")

    # ---- emit ----
    out = [HEADER, "#pragma once\n",
           "#include <atomic>\n#include <cstdint>\n#include <memory>\n#include <mutex>\n"
           "#include <shared_mutex>\n#include <string>\n#include <unordered_map>\n"
           "#include <unordered_set>\n#include <vector>\n",
           "#include \"internal/core/arena.h\"\n#include \"internal/core/text.h\"\n"
           "#include \"internal/ast/flags.h\"\n#include \"internal/ast/kind.h\"\n",
           "namespace tsc {\n\n"]

    node_structs.add("SourceFile")

    field_renames = {"ecmaLineMap": "ecmaLineMap_"}

    extra_members = {
        "SourceFile": (
            "\tconst std::vector<::tsc::TextPos>& ecmaLineMap();\n"
            "\tstd::vector<::tsc::Node*> resolveJSDoc(::tsc::Node* n);\n"
            "\tvoid setHasLazyJSDoc(bool lazy) { hasLazyJSDoc = lazy; }\n"
            "\tconst std::string& FileName() const { return fileName; }\n"
            "\tconst std::string& Path() const { return fileName; }\n"
            "\tconst std::string& Text() const { return text; }\n"
            "\t::tsc::SourceFileParseOptions ParseOptions() const { return parseOptions; }\n"
            "\tconst std::string& OriginalText() const;\n"
            "\tstd::string OriginalFileName() const;\n"
            "\t::tsc::spanmap::SpanMap* SpanMap() const;\n"
            "\tstd::string ContentMapper() const;\n"
            "\tbool IsContentMapperFailureStub() const;\n"
            "\tstd::string ContentMapperTransformIdentity() const;\n"
            "\tstd::string VirtualFileName() const;\n"
            "\t::tsc::SourceFileParseOptions ContentMapperParseOptions() const;\n"
            "\tvoid SetContentMapperInfo(const ::tsc::ContentMapperSourceFileInfo& info);\n"
            "\tconst std::vector<::tsc::MappedDiagnosticDirective>* DiagnosticDirectives() const;\n"
            "\tconst std::vector<::tsc::SourceFile*>* SupplementalSourceFiles() const;\n"
            "\t::tsc::SourceFile* CanonicalSourceFile() const;\n"
            "\tbool IsContentMapperSupplemental() const;\n"
            "\t::tsc::Arena nodeArena;\n"
            "\t::tsc::Arena jsdocArena;\n"
            "\tvoid copyFrom(SourceFile* other);\n"
        ),
    }

    # flatten + emit each node struct
    flat = {}
    for sname in sorted(node_structs):
        fields = flatten(structs, sname)
        flat[sname] = fields
        out.append(f"struct {sname} : Node {{\n")
        if sname in extra_members:
            out.append(extra_members[sname])
        for fname, gtype, _ in fields:
            cxx = go_type_to_cpp(gtype, node_structs, aliases)
            cf = sanitize(fname)
            cf = field_renames.get(cf, cf)
            # default-init scalars
            if cxx in ("bool",):
                out.append(f"\t{cxx} {cf}{{}};\n")
            elif cxx in ("int32_t", "int64_t", "uint32_t", "uint64_t"):
                out.append(f"\t{cxx} {cf}{{}};\n")
            elif "Atomic<" in cxx:
                out.append(f"\tmutable {cxx} {cf}{{}};\n")
            elif cxx.endswith("*"):
                out.append(f"\t{cxx} {cf}{{}};\n")
            elif cxx in ("::tsc::TokenFlags", "::tsc::NodeFlags", "::tsc::ModifierFlags",
                         "::tsc::CheckFlags", "::tsc::FunctionFlags", "::tsc::SubtreeFacts",
                         "::tsc::LanguageVariant", "::tsc::ScriptKind", "::tsc::Tristate",
                         "::tsc::ScriptTarget", "::tsc::ResolutionMode",
                         "::tsc::CommentDirectiveKind", "Kind", "int"):
                out.append(f"\t{cxx} {cf}{{}};\n")
            else:
                out.append(f"\t{cxx} {cf};\n")
        out.append("};\n\n")

    # ---- NodeFactory methods ----
    out.append("// Factory methods (generated from New* in ast_generated.go).\n\n")
    decls = ["// Method declarations for class NodeFactory; included inside the class\n",
             "// body in ast.h. Generated; DO NOT EDIT.\n"]
    for fname, (kind, sname, args, assigns, node_assigns) in \
            factory_methods.items():
        cxx = fname[0].lower() + fname[1:]  # NewX -> newX
        sig = ", ".join(f"{go_type_to_cpp(t, node_structs, aliases)} {sanitize(n)}"
                        for n, t in args)
        decls.append(f"\tNode* {cxx}({sig});\n")
        out.append(f"inline Node* NodeFactory::{cxx}({sig}) {{\n")
        out.append(f"\tauto* data = arena_.alloc<{sname}>();\n")
        for f, expr in assigns:
            e = sanitize(expr.strip())
            out.append(f"\tdata->{sanitize(f)} = {e};\n")
        if textcount.get(fname):
            out.append("\ttextCount_++;\n")
        k = "Kind::" + kind[4:] if kind else "kind"
        if node_assigns:
            out.append(f"\tauto* node = newNode({k}, data);\n")
            for nf, nop, nexpr in node_assigns:
                ne = sanitize(nexpr.strip())
                field = {"Flags": "flags", "Loc": "loc",
                         "Parent": "parent"}.get(nf, sanitize(nf))
                out.append(f"\tnode->{field} {nop} {ne};\n")
            out.append("\treturn node;\n}\n\n")
        else:
            out.append(f"\treturn newNode({k}, data);\n}}\n\n")

    # ---- Update* methods ----
    # Go `UpdateX` bodies all follow `if (args differ) return updateNode(
    # f.NewX(args...), node.AsNode(), f.hooks); return node.AsNode()`.
    NODE_BASE_FIELDS = {"Kind": "kind", "Flags": "flags", "Loc": "loc",
                      "Parent": "parent", "Id": "id"}

    def go_args(arg_src):
        """Split a Go call-arg list on top-level commas."""
        parts, depth, cur = [], 0, ""
        for ch in arg_src:
            if ch in "([{":
                depth += 1
            elif ch in ")]}":
                depth -= 1
            if ch == "," and depth == 0:
                parts.append(cur)
                cur = ""
            else:
                cur += ch
        if cur.strip():
            parts.append(cur)
        return [p.strip() for p in parts]

    def go_expr(expr, out_recv="node", renames=None):
        """Translate a Go expression fragment found inside Update*/Clone/
        VisitEachChild bodies; `node.` field accesses map to `out_recv->`.
        `renames` maps Go arg names that are C++ keywords to their sanitized
        form (must match the emitted signature)."""
        e = expr.strip()
        if renames:
            for go_name, cpp_name in renames.items():
                e = re.sub(r"\b" + re.escape(go_name) + r"\b", cpp_name, e)
        e = re.sub(r"!core\.Same\(([^,()]+),\s*([^()]+)\)",
                   r"(\1 != \2)", e)
        e = re.sub(r"core\.Same\(([^,()]+),\s*([^()]+)\)",
                   r"(\1 == \2)", e)
        e = e.replace("f.AsNodeFactory().", "f.")
        e = e.replace("node.AsNode()", out_recv)
        # node.AsXxx() is the templated cast.
        e = re.sub(r"node\.As(\w+)\(\)", out_recv + "->as<\\1>()", e)
        # node.Modifiers()/node.Name()/... are base-class accessors; structs
        # carry same-named fields (modifiers, name) that would shadow them, so
        # qualify the call with Node:: explicitly.
        e = re.sub(r"node\.(\w+)\(\)",
                   lambda m: out_recv + "->Node::" + m.group(1)[0].lower() +
                   m.group(1)[1:] + "()", e)
        e = re.sub(r"node\.(\w+)",
                   lambda m: out_recv + "->" +
                   NODE_BASE_FIELDS.get(m.group(1), sanitize(m.group(1))), e)
        e = re.sub(r"f\.(\w+)\(",
                   lambda m: m.group(1)[0].lower() + m.group(1)[1:] + "(", e)
        return e

    out.append("// Update* methods (generated from Update* in\n"
               "// ast_generated.go + ast.go).\n\n")
    for sname in sorted(upd_methods):
        uname, args, body = upd_methods[sname]
        cxx = uname[0].lower() + uname[1:]
        sig = ", ".join(f"{go_type_to_cpp(t, node_structs, aliases)} {sanitize(n)}"
                        for n, t in args)
        decls.append(f"\tNode* {cxx}({sname}* node, {sig});\n")
        # Go arg names may be C++ keywords (operator, template, namespace, ...)
        # — sanitize() renames them in the signature; rewrite them in bodies too.
        renames = {n: sanitize(n) for n, _ in args if sanitize(n) != n}
        if sname == "SourceFile":
            out.append(
                f"inline Node* NodeFactory::{cxx}({sname}* node, {sig}) {{\n"
                "\tif (statements != node->Statements ||"
                " endOfFileToken != node->EndOfFileToken) {\n"
                "\t\tauto* updated = newSourceFile(node->parseOptions,"
                " node->text, statements, endOfFileToken)->as<SourceFile>();\n"
                "\t\tupdated->copyFrom(node);\n"
                "\t\treturn updateNode(updated, node, hooks);\n"
                "\t}\n"
                "\treturn node;\n}\n\n")
            continue
        m2 = re.match(
            r"\s*if (.*?) \{\s*"
            r"return updateNode\(f\.(\w+)\((.*)\),\s*node\.AsNode\(\),\s*f\.hooks\)\s*\}"
            r"\s*return node\.AsNode\(\)\s*$", body, re.S)
        out.append(f"inline Node* NodeFactory::{cxx}({sname}* node, {sig}) {{\n")
        if m2:
            cond, newcall = m2.group(1), f"f.{m2.group(2)}({m2.group(3)})"
            out.append(f"\tif ({go_expr(cond, renames=renames)}) {{\n")
            out.append(f"\t\treturn updateNode({go_expr(newcall, renames=renames)}, node, hooks);\n")
            out.append("\t}\n\treturn node;\n}\n\n")
            continue
        # Kind-switched variant: `if (args differ) { switch node.Kind { case
        # K: return updateNode(f.NewY(args), node.AsNode(), f.hooks) ...
        # default: panic } } return node.AsNode()`
        m3 = re.match(
            r"\s*if (.*?) \{\s*switch node\.Kind \{\s*(.*?)\s*default:\s*"
            r"panic\(.*?\)\s*\}\s*\}\s*return node\.AsNode\(\)\s*$",
            body, re.S)
        assert m3, f"unhandled Update body for {sname}: {body[:200]}"
        cond = m3.group(1)
        out.append(f"\tif ({go_expr(cond, renames=renames)}) {{\n\t\tswitch (node->kind) {{\n")
        for cm in re.finditer(
                r"case (\w+):\s*return updateNode\(f\.(\w+)\((.*?)\),\s*"
                r"node\.AsNode\(\),\s*f\.hooks\)", m3.group(2), re.S):
            k, newcall = cm.group(1), f"f.{cm.group(2)}({cm.group(3)})"
            out.append(f"\t\tcase Kind::{k[4:]}:\n")
            out.append(f"\t\t\treturn updateNode({go_expr(newcall, renames=renames)}, node, hooks);\n")
        out.append("\t\tdefault:\n"
                   f"\t\t\tTSC_UNREACHABLE(\"unexpected kind in {cxx}\");\n"
                   "\t\t}\n\t}\n\treturn node;\n}\n\n")

    # ---- dispatch ----
    out.append("// forEachChild / name / modifiers dispatch (generated).\n\n")

    # Group structs -> kinds for switch emission
    def kinds_case(sname, seen=None):
        ks = struct_kinds.get(sname, [])
        out_s = ""
        for k in ks:
            if seen is not None:
                if k in seen:
                    continue
                seen.add(k)
            out_s += f"\t\tcase Kind::{k[4:]}:\n"
        return out_s

    out.append("template <class F>\nbool Node::forEachChild(F&& v) const {\n")
    out.append("\tswitch (kind) {\n")
    seen_kinds = set()
    for sname, calls in sorted(foreach.items()):
        helper = foreach_helpers.get(sname)
        if not calls and helper is None:
            continue
        out.append(kinds_case(sname, seen_kinds))
        out.append(f"\t\t{{\n\t\t\tauto* n = static_cast<const {sname}*>(this);\n")
        if helper is not None:
            # Delegated body: translate `return <bool-expr>` verbatim.
            expr = helper.strip()
            expr = re.sub(r"^return\s*", "", expr).rstrip().rstrip(";")
            expr = re.sub(r"visitModifiers\(v, node\.(\w+)\)",
                          lambda m: f"visitChildModifiers(v, n->{sanitize(m.group(1))})", expr)
            expr = re.sub(r"visitNodeList\(v, node\.(\w+)\)",
                          lambda m: f"visitChildList(v, n->{sanitize(m.group(1))})", expr)
            expr = re.sub(r"visit\(v, node\.(\w+)\)",
                          lambda m: f"visitChild(v, n->{sanitize(m.group(1))})", expr)
            expr = re.sub(r"node\.(\w+)",
                          lambda m: f"n->{sanitize(m.group(1))}", expr)
            out.append("\t\t\treturn " + expr + ";\n\t\t}\n")
            continue
        parts = []
        for fn, field in calls:
            cf = sanitize(field)
            if fn == "visit":
                parts.append(f"visitChild(v, n->{cf})")
            elif fn == "visitNodeList":
                parts.append(f"visitChildList(v, n->{cf})")
            elif fn == "visitModifiers":
                parts.append(f"visitChildModifiers(v, n->{cf})")
        out.append("\t\t\treturn " + " ||\n\t\t\t\t".join(parts) + ";\n\t\t}\n")
    out.append("\t\tdefault:\n\t\t\treturn false;\n\t}\n}\n\n")

    # deepClone dispatch (generated): one case per struct, cloning every child
    # field per the same visit* list used by forEachChild.
    # syntheticLocation mirrors Go's getDeepCloneVisitor: true forces every
    # clone (and cloned list) to Loc (-1,-1) / last node (-2,-2) when the list
    # has a trailing comma; false (DeepCloneReparse) preserves locations.
    # onClone mirrors Go's Node.Clone -> updateNode -> hooks.OnClone, which is
    # how the EmitContext copies emitNode data onto clones.
    out.append("// deepClone dispatch (generated).\n\n")
    out.append("inline Node* deepCloneNode(NodeFactory& f, const Node* node,\n"
               "                           bool syntheticLocation = true);\n")
    out.append("inline NodeList* deepCloneNodeList(NodeFactory& f,\n"
               "                                   const NodeList* l,\n"
               "                                   bool syntheticLocation = true);\n")
    out.append("inline ModifierList* deepCloneModifierList(NodeFactory& f,\n"
               "                                           const ModifierList* m,\n"
               "                                           bool syntheticLocation = true);\n\n")
    out.append("inline NodeList* deepCloneNodeList(NodeFactory& f,\n"
               "                                   const NodeList* l,\n"
               "                                   bool syntheticLocation) {\n"
               "\tif (l == nullptr) return nullptr;\n"
               "\tbool trailingComma = l->hasTrailingComma();\n"
               "\tauto* c = f.arena().alloc<NodeList>(*l);\n"
               "\tfor (auto& n : c->nodes) n = deepCloneNode(f, n, syntheticLocation);\n"
               "\tif (syntheticLocation) {\n"
               "\t\tc->loc = TextRange{-1, -1};\n"
               "\t\tif (trailingComma) {\n"
               "\t\t\tc->nodes.back()->loc = TextRange{-2, -2};\n"
               "\t\t}\n"
               "\t}\n"
               "\treturn c;\n}\n\n")
    out.append("inline ModifierList* deepCloneModifierList(NodeFactory& f,\n"
               "                                           const ModifierList* m,\n"
               "                                           bool syntheticLocation) {\n"
               "\tif (m == nullptr) return nullptr;\n"
               "\tbool trailingComma = m->hasTrailingComma();\n"
               "\tauto* c = f.arena().alloc<ModifierList>(*m);\n"
               "\tfor (auto& n : c->nodes) n = deepCloneNode(f, n, syntheticLocation);\n"
               "\tc->ModifierFlags = NodeFactory::modifiersToFlags(c->nodes);\n"
               "\tif (syntheticLocation) {\n"
               "\t\tc->loc = TextRange{-1, -1};\n"
               "\t\tif (trailingComma) {\n"
               "\t\t\tc->nodes.back()->loc = TextRange{-2, -2};\n"
               "\t\t}\n"
               "\t}\n"
               "\treturn c;\n}\n\n")
    out.append("inline Node* deepCloneNode(NodeFactory& f, const Node* node,\n"
               "                           bool syntheticLocation) {\n"
               "\tif (node == nullptr) return nullptr;\n"
               "\tswitch (node->kind) {\n")
    seen_kinds = set()
    for sname in sorted(struct_kinds):
        cases = kinds_case(sname, seen_kinds)
        if not cases:
            continue
        out.append(cases)
        if sname == "SourceFile":
            # SourceFile is never a clone target (mutexes aren't copyable);
            # keep the case for exhaustive switching.
            out.append("\t\t{\n\t\t\treturn nullptr;\n\t\t}\n")
            continue
        out.append(f"\t\t{{\n\t\t\tauto* n = static_cast<const {sname}*>(node);\n")
        out.append(f"\t\t\tauto* c = f.arena().alloc<{sname}>(*n);\n")
        for fn, field in foreach.get(sname, []):
            cf = sanitize(field)
            tgt = {"visit": "deepCloneNode",
                   "visitNodeList": "deepCloneNodeList",
                   "visitModifiers": "deepCloneModifierList"}[fn]
            out.append(f"\t\t\tc->{cf} = {tgt}(f, n->{cf}, syntheticLocation);\n")
        out.append("\t\t\tif (syntheticLocation) c->loc = TextRange{-1, -1};\n"
                   "\t\t\tif (f.hooks.onClone) f.hooks.onClone(c, const_cast<Node*>(node));\n"
                   "\t\t\treturn c;\n\t\t}\n")
    out.append("\t\tdefault:\n"
               "\t\t\t// Leaf token kinds clone as plain Token nodes (they have\n"
               "\t\t\t// no children and carry no extra fields).\n"
               "\t\t\tif (node->kind <= KindLastToken) {\n"
               "\t\t\t\tauto* n = static_cast<const Token*>(node);\n"
               "\t\t\t\tauto* c = f.arena().alloc<Token>(*n);\n"
               "\t\t\t\tif (syntheticLocation) c->loc = TextRange{-1, -1};\n"
               "\t\t\t\tif (f.hooks.onClone) f.hooks.onClone(c, const_cast<Node*>(node));\n"
               "\t\t\t\treturn c;\n"
               "\t\t\t}\n"
               "\t\t\treturn nullptr;\n"
               "\t}\n}\n\n")

    # name()/modifiers() etc: accessors found above
    node_decls = ["// Method declarations for struct Node; included inside the struct\n",
                  "// body in ast.h. Generated; DO NOT EDIT.\n",
                  "\ttemplate <class F> bool forEachChild(F&& v) const;\n"]
    for meth, per_struct in sorted(accessors.items()):
        cxxmeth = meth[0].lower() + meth[1:]
        # common return type across structs
        rets = {go_type_to_cpp(r, node_structs, aliases) for r, f in per_struct.values()}
        ret = rets.pop() if len(rets) == 1 else "Node*"
        # skip accessors we hand-write
        if cxxmeth in ("asNode", "forEachChild", "visitEachChild", "clone",
                       "subtreeFacts", "flowNodeData", "declarationData",
                       "exportableData", "localsContainerData", "functionLikeData",
                       "classLikeData", "bodyData", "literalLikeData",
                       "templateLiteralLikeData", "modifiers",
                       "text"):
            continue
        node_decls.append(f"\t{ret} {cxxmeth}() const;\n")
        out.append(f"inline {ret} Node::{cxxmeth}() const {{\n\tswitch (kind) {{\n")
        for sname, (r, f) in sorted(per_struct.items()):
            if sname not in node_structs:
                continue
            out.append(kinds_case(sname))
            out.append(f"\t\t\treturn static_cast<const {sname}*>(this)->{sanitize(f)};\n")
        out.append("\t\tdefault:\n\t\t\treturn {};\n\t}\n}\n\n")

    # ---- embedded-base membership + field presence per struct ----
    enum_names = set(load_kinds()[0])
    enum_names_sorted = sorted(enum_names, key=len, reverse=True)

    def base_closure(sname):
        seen = set()
        def go(n):
            for _f, bt, emb in structs.get(n, []):
                if emb:
                    b = bt.lstrip("*")
                    if b in structs and b not in seen:
                        seen.add(b)
                        go(b)
        go(sname)
        return seen

    def has_field(sname, *names):
        fs = {f for f, _t, _e in flat[sname]}
        return all(n in fs for n in names)

    # ---- Data-accessor views over flattened base fields ----
    out.append(
        "// Views over flattened embedded-base fields (generated). Callers get\n"
        "// pointers to the real fields so reads and writes behave like Go's\n"
        "// embedded-base accessors.\n\n"
        "struct DeclarationDataRef { Symbol** symbol; };\n"
        "struct ExportableDataRef { Symbol** localSymbol; };\n"
        "struct LocalsContainerDataRef { SymbolTable* locals; Node** nextContainer; };\n"
        "struct FlowNodeDataRef { FlowNode** flowNode; };\n"
        "struct FunctionLikeDataRef { SymbolTable* locals; Node** nextContainer; "
        "NodeList** typeParameters; NodeList** parameters; Node** type; "
        "Node** fullSignature; };\n"
        "struct BodyDataRef { Node** asteriskToken; Node** body; FlowNode** endFlowNode; };\n"
        "struct ClassLikeDataRef { Symbol** localSymbol; ModifierList** modifiers; "
        "SymbolTable* locals; Node** nextContainer; Node** name; "
        "NodeList** typeParameters; NodeList** heritageClauses; NodeList** members; };\n"
        "struct LiteralLikeDataRef { std::string* text; TokenFlags* tokenFlags; };\n"
        "struct TemplateLiteralLikeDataRef { std::string* text; TokenFlags* tokenFlags; "
        "std::string* rawText; TokenFlags* templateFlags; };\n\n")

    def data_dispatch(meth, ref, detect, fields):
        out.append(f"inline {ref} Node::{meth}() {{\n\tswitch (kind) {{\n")
        seen_kinds = set()
        for sname in sorted(node_structs):
            if detect(sname):
                expr = ", ".join(f"&n->{f}" if has_field(sname, f)
                                 else "nullptr" for f in fields)
                out.append(kinds_case(sname, seen_kinds))
                out.append(f"\t\t\t{{ auto* n = static_cast<{sname}*>(this); "
                           f"return {{ {expr} }}; }}\n")
        out.append("\t\tdefault:\n\t\t\treturn {};\n\t}\n}\n\n")
        node_decls.append(f"\t{ref} {meth}();\n")

    data_dispatch("declarationData", "DeclarationDataRef",
                  lambda s: has_field(s, "Symbol"), ["Symbol"])
    data_dispatch("exportableData", "ExportableDataRef",
                  lambda s: has_field(s, "LocalSymbol"), ["LocalSymbol"])
    data_dispatch("localsContainerData", "LocalsContainerDataRef",
                  lambda s: has_field(s, "Locals", "NextContainer"),
                  ["Locals", "NextContainer"])
    data_dispatch("flowNodeData", "FlowNodeDataRef",
                  lambda s: has_field(s, "FlowNode"), ["FlowNode"])
    data_dispatch("functionLikeData", "FunctionLikeDataRef",
                  lambda s: has_field(s, "TypeParameters", "Parameters",
                                      "Type", "FullSignature"),
                  ["Locals", "NextContainer", "TypeParameters",
                   "Parameters", "Type", "FullSignature"])
    data_dispatch("bodyData", "BodyDataRef",
                  lambda s: has_field(s, "AsteriskToken", "Body", "EndFlowNode"),
                  ["AsteriskToken", "Body", "EndFlowNode"])
    data_dispatch("classLikeData", "ClassLikeDataRef",
                  lambda s: has_field(s, "HeritageClauses", "Members"),
                  ["LocalSymbol", "modifiers", "Locals", "NextContainer",
                   "name", "TypeParameters", "HeritageClauses", "Members"])
    data_dispatch("literalLikeData", "LiteralLikeDataRef",
                  lambda s: has_field(s, "Text", "TokenFlags"),
                  ["Text", "TokenFlags"])
    data_dispatch("templateLiteralLikeData", "TemplateLiteralLikeDataRef",
                  lambda s: has_field(s, "RawText", "TemplateFlags"),
                  ["Text", "TokenFlags", "RawText", "TemplateFlags"])

    # modifiers()/setModifiers() — kinds with a `modifiers` field
    out.append("inline ModifierList* Node::modifiers() const {\n\tswitch (kind) {\n")
    seen_kinds = set()
    for sname in sorted(node_structs):
        if has_field(sname, "modifiers"):
            out.append(kinds_case(sname, seen_kinds))
            out.append(f"\t\t\treturn static_cast<const {sname}*>(this)->modifiers;\n")
    out.append("\t\tdefault:\n\t\t\treturn nullptr;\n\t}\n}\n\n")
    node_decls.append("\tModifierList* modifiers() const;\n")
    node_decls.append("\tvoid setModifiers(ModifierList* m);\n")
    out.append("inline void Node::setModifiers(ModifierList* m) {\n\tswitch (kind) {\n")
    seen_kinds = set()
    for sname in sorted(node_structs):
        if has_field(sname, "modifiers"):
            out.append(kinds_case(sname, seen_kinds))
            out.append(f"\t\t\tstatic_cast<{sname}*>(this)->modifiers = m; return;\n")
    out.append("\t\tdefault:\n\t\t\treturn;\n\t}\n}\n\n")

    # ---- subtree facts ----
    prop_masks = {
        "CatchClause": ("SubtreeExclusionsCatchClause", None),
        "VariableDeclarationList": ("SubtreeExclusionsVariableDeclarationList", None),
        "BindingPattern": ("SubtreeExclusionsBindingPattern", None),
        "ParameterDeclaration": ("SubtreeExclusionsParameter", None),
        "FunctionDeclaration": ("SubtreeExclusionsFunction", None),
        "ClassDeclaration": ("SubtreeExclusionsClass", None),
        "ClassExpression": ("SubtreeExclusionsClass", None),
        "ModuleDeclaration": ("SubtreeExclusionsModule", None),
        "ConstructorDeclaration": ("SubtreeExclusionsConstructor", None),
        "GetAccessorDeclaration": ("SubtreeExclusionsAccessor", "name"),
        "SetAccessorDeclaration": ("SubtreeExclusionsAccessor", "name"),
        "MethodDeclaration": ("SubtreeExclusionsMethod", "name"),
        "PropertyDeclaration": ("SubtreeExclusionsProperty", "name"),
        "ArrowFunction": ("SubtreeExclusionsArrowFunction", None),
        "FunctionExpression": ("SubtreeExclusionsFunction", None),
        "AsExpression": ("SubtreeExclusionsOuterExpression", None),
        "SatisfiesExpression": ("SubtreeExclusionsOuterExpression", None),
        "TypeAssertion": ("SubtreeExclusionsOuterExpression", None),
        "PropertyAccessExpression": ("SubtreeExclusionsPropertyAccess", None),
        "ElementAccessExpression": ("SubtreeExclusionsElementAccess", None),
        "CallExpression": ("SubtreeExclusionsCall", None),
        "NewExpression": ("SubtreeExclusionsNew", None),
        "ArrayLiteralExpression": ("SubtreeExclusionsArrayLiteral", None),
        "ObjectLiteralExpression": ("SubtreeExclusionsObjectLiteral", None),
    }

    out.append("// subtree facts (generated).\n\n")
    out.append("inline SubtreeFacts Node::propagateSubtreeFacts() const {\n\tswitch (kind) {\n")
    seen_kinds = set()
    for sname in sorted(node_structs):
        if "TypeSyntaxBase" in base_closure(sname):
            out.append(kinds_case(sname, seen_kinds))
            out.append("\t\t\treturn SubtreeContainsTypeScript;\n")
            continue
        if sname in prop_masks:
            mask, extra = prop_masks[sname]
            out.append(kinds_case(sname, seen_kinds))
            r = f"\t\t\t{{ auto* n = static_cast<const {sname}*>(this); " \
                f"return subtreeFacts() & ~{mask}"
            if extra:
                r += f" | ::tsc::propagateSubtreeFacts(n->{extra})"
            r += "; }\n"
            out.append(r)
    out.append("\t\tdefault:\n\t\t\treturn subtreeFacts() & ~SubtreeExclusionsNode;\n\t}\n}\n\n")
    node_decls.append("\tSubtreeFacts propagateSubtreeFacts() const;\n")

    # pointer-producing member names for `a.b` -> `a->b` hop conversion
    ptr_members = set()
    for s in node_structs:
        for fn_, gt_, _ in flat.get(s, []):
            if go_type_to_cpp(gt_, node_structs, aliases).endswith("*"):
                ptr_members.add(sanitize(fn_))
    PTR_ACCS = {"name", "expression", "type", "body", "initializer", "tagName",
                "questionToken", "postfixToken", "questionDotToken", "propertyName",
                "propertyNameOrName", "label", "attributes", "moduleSpecifier",
                "importClause", "statement", "typeExpression", "className",
                "argumentList", "typeArgumentList", "typeParameterList", "memberList",
                "statementList", "elementList", "propertyList", "commentList",
                "parameterList", "modifiers", "symbol", "localSymbol", "locals",
                "nextContainer", "parent"}
    # capitalized Go accessor/cast calls -> lowercase C++ equivalents
    METHOD_RENAMES = {
        "Text": "text", "RawText": "rawText", "Name": "name", "Expression": "expression",
        "Type": "type", "Body": "body", "Initializer": "initializer", "TagName": "tagName",
        "QuestionToken": "questionToken", "PostfixToken": "postfixToken",
        "QuestionDotToken": "questionDotToken", "PropertyName": "propertyName",
        "Label": "label", "Attributes": "attributes", "ModuleSpecifier": "moduleSpecifier",
        "ImportClause": "importClause", "Statement": "statement",
        "TypeExpression": "typeExpression", "ClassName": "className",
        "ArgumentList": "argumentList", "TypeArgumentList": "typeArgumentList",
        "TypeParameterList": "typeParameterList", "MemberList": "memberList",
        "StatementList": "statementList", "ElementList": "elementList",
        "PropertyList": "propertyList", "CommentList": "commentList",
        "ParameterList": "parameterList", "Arguments": "arguments",
        "TypeArguments": "typeArguments", "TypeParameters": "typeParameters",
        "Members": "members", "Statements": "statements", "Elements": "elements",
        "Properties": "properties", "Comments": "comments", "Parameters": "parameters",
        "Children": "children", "CanHaveStatements": "canHaveStatements",
        "IsTypeOnly": "isTypeOnly", "ModifierFlags": "modifierFlags",
        "Modifiers": "modifiers", "SubtreeFacts": "subtreeFacts",
        "Locals": "locals", "Symbol": "symbol", "LocalSymbol": "localSymbol",
        "NextContainer": "nextContainer", "Contains": "contains",
        "ForEachChild": "forEachChild", "End": "end", "Pos": "pos", "Len": "len",
        "AsNode": "asNode", "PosEnd": "posEnd",
    }
    METH_PAT = "|".join(sorted(METHOD_RENAMES, key=len, reverse=True))

    # computeSubtreeFacts bodies translated from Go
    def facts_expr(e):
        e = e.strip()
        e = e.replace("!= nil", "!= nullptr").replace("== nil", "== nullptr")
        e = e.replace("node.ModifierFlags()", "n->modifierFlags()")
        e = e.replace("node.modifiers.ModifierFlags", "(n->modifiers ? n->modifiers->ModifierFlags : ModifierFlags{})")
        e = e.replace("node.", "n->")
        e = re.sub(r"\bnode\b", "n", e)
        e = re.sub(r"core\.IfElse\(", "ifElse(", e)
        # `.x` -> `->x` where the receiver produces a pointer (iterate to fixpoint)
        def _hops(s):
            def hop(m):
                recv, mem = m.group(1), m.group(2)
                base = recv
                if recv.endswith(")"):
                    b = re.match(r"(\w+)\(", recv)
                    base = b.group(1) if b else recv
                if recv.startswith("as<") or base in ptr_members or base in PTR_ACCS:
                    return recv + "->" + mem
                return m.group(0)
            return re.sub(r"(as<\w+>\(\)|\w+(?:\(\))?)\.(\w+)", hop, s)
        prev = None
        while prev != e:
            prev = e
            e = _hops(e)
        # casts and capitalized accessor calls on pointers
        e = re.sub(r"->As(\w+)\(\)", r"->as<\1>()", e)
        e = re.sub(r"->(" + METH_PAT + r")\(",
                   lambda m: "->" + METHOD_RENAMES[m.group(1)] + "(", e)
        # value-member calls on TextRange / NodeList values
        e = re.sub(r"\.(End|Pos|Len|Contains|ContainsInclusive|Overlaps|Intersects)\(",
                   lambda m: "." + m.group(1)[0].lower() + m.group(1)[1:] + "(", e)
        # core field names stay lowercase in C++
        e = e.replace("->Kind", "->kind").replace("->Flags", "->flags")
        e = e.replace("->Parent", "->parent").replace("->Loc", "->loc")
        e = e.replace("->Nodes", "->nodes").replace("->Id", "->id")
        e = re.sub(r"\bIs(\w+)\(", r"is\1(", e)
        e = re.sub(r"\bContainsObjectRestOrSpread\(", "containsObjectRestOrSpread(", e)
        e = re.sub(r"\b(propagateSubtreeFacts|propagateEraseableSyntax|"
                   r"propagateEraseableSyntaxFacts|"
                   r"propagateEraseableSyntaxListSubtreeFacts|"
                   r"propagateNodeListSubtreeFacts|"
                   r"propagateModifierListSubtreeFacts|"
                   r"propagateObjectBindingElementSubtreeFacts|"
                   r"propagateBindingElementSubtreeFacts|"
                   r"containsObjectRestOrSpread)\(",
                   r"::tsc::\1(", e)
        e = e.replace("&^=", "&= ~")
        e = re.sub(r"&\s*\^\s*(\w+)", r"& ~\1", e)
        for k in enum_names_sorted:
            e = re.sub(r"\b" + re.escape(k) + r"\b", "Kind::" + k[4:], e)
        return e

    def facts_body(sname, body):
        # join multi-line expressions: a line ending with a binary operator or
        # containing unbalanced parens continues on the next line.
        logical = []
        buf = ""
        for raw in body.split("\n"):
            l = raw.strip()
            if not l:
                continue
            buf = (buf + " " + l) if buf else l
            if re.search(r"[|&?,(]$", l) or l.endswith("||") or l.endswith("&&"):
                continue
            if buf.count("(") != buf.count(")"):
                continue
            logical.append(buf)
            buf = ""
        if buf:
            logical.append(buf)

        lines_out = []
        for ln in logical:
            if ln == "}" or ln == "} else {" or ln == "else {":
                lines_out.append(ln.replace("else", "else"))
                continue
            if ln.startswith("switch "):
                m2 = re.match(r"switch (.*) \{$", ln)
                lines_out.append("switch (" + facts_expr(m2.group(1)) + ") {")
                continue
            if ln.startswith("case ") and ln.endswith(":"):
                rest = ln[5:-1]
                labels = [facts_expr(x.strip()) for x in rest.split(",")]
                lines_out.append(" ".join(f"case {x}:" for x in labels))
                continue
            if ln.startswith("default"):
                lines_out.append(facts_expr(ln))
                continue
            if ln.startswith("for ") and ln.endswith("{"):
                m2 = re.match(r"for (?:_, )?(\w+) := range (.*) \{$", ln)
                if m2:
                    lines_out.append(f"for (auto* {m2.group(1)} : {facts_expr(m2.group(2))}) {{")
                    continue
                m2 = re.match(r"for (\w+), (\w+) := range (.*) \{$", ln)
                if m2:
                    lines_out.append(
                        f"for (auto _r : {facts_expr(m2.group(3))}) {{ "
                        f"auto {m2.group(1)} = _r.first; auto {m2.group(2)} = _r.second;")
                    continue
                lines_out.append("// TODO for: " + ln)
                continue
            if ln.startswith("if ") and ln.endswith("{"):
                lines_out.append("if (" + facts_expr(ln[3:-1].strip()) + ") {")
                continue
            if ln.startswith("return "):
                lines_out.append("return " + facts_expr(ln[7:]) + ";")
                continue
            if ln == "return":
                lines_out.append("return SubtreeFactsNone;")
                continue
            m2 = re.match(r"(\w+) :?= (.*)$", ln)
            if m2:
                lines_out.append(f"auto {m2.group(1)} = {facts_expr(m2.group(2))};")
                continue
            m2 = re.match(r"(\w+) (&\^=|\|=|\^=|&=|=|\+=|-=) (.*)$", ln)
            if m2:
                op = m2.group(2)
                op = "&= ~" if op == "&^=" else op
                lines_out.append(f"{m2.group(1)} {op} {facts_expr(m2.group(3))};")
                continue
            if ln.startswith("panic("):
                lines_out.append("TSC_UNREACHABLE(" + ln[6:-1] + ");")
                continue
            lines_out.append(facts_expr(ln) + ";")
        return lines_out

    # ---- Is* predicates (emitted before computeSubtreeFacts which calls them) ----
    def map_kind(k):
        return f"Kind::{k[4:]}" if k in enum_names else k

    # Predicates with real bodies ported by hand in MANUAL_AST_HELPERS below;
    # skip them here so the generated stubs don't collide.
    manual_predicates = {
        "IsWriteOnlyAccess", "IsWriteAccess", "IsWriteAccessForReference",
        "IsArrayLiteralOrObjectLiteralDestructuringPattern",
        "IsDeclarationNode", "IsLocalsContainer"}

    out.append("// is* predicates (generated).\n\n")
    for name, body in predicates:
        cxx = name[0].lower() + name[1:]
        if name in manual_predicates:
            continue
        # emit a kind-union only when the body is a pure kind-check
        ids = set(re.findall(r"\b([A-Za-z_]\w*)\b", body)) - {
            "node", "Kind", "return", "case", "switch", "default", "if",
            "else", "true", "false", "nil", "fallthrough"}
        nonkind = [i for i in ids if not i.startswith("Kind")]
        if nonkind:
            out.append(f"inline bool {cxx}(const Node*) {{ return false; /* TODO: {name} */ }}\n")
            continue
        ks = re.findall(r"Kind\w+", body)
        cond = " || ".join(f"n->kind == {map_kind(k)}"
                            for k in dict.fromkeys(ks))
        out.append(f"inline bool {cxx}(const Node* n) {{ return {cond}; }}\n")
    out.append("\n")

    compute = {}
    for m in re.finditer(
            r"func \(node \*(\w+)\) computeSubtreeFacts\(\) SubtreeFacts \{\n(.*?)\n\}",
            src_all, re.S):
        compute[m.group(1)] = m.group(2)
    # single-line bodies: `func (node *X) computeSubtreeFacts() SubtreeFacts { return Y }`
    for m in re.finditer(
            r"func \(node \*(\w+)\) computeSubtreeFacts\(\) SubtreeFacts \{ return (\w+) \}",
            src_all):
        compute.setdefault(m.group(1), f"return {m.group(2)}")

    # Concrete structs that inherit computeSubtreeFacts from an embedded base
    # (ClassLikeBase, AccessorDeclarationBase, TypeSyntaxBase, ...) resolve to
    # the providing base; a function is generated per concrete struct using
    # the base's body (fields are flattened identically).
    provider = {}
    for sname in node_structs:
        if sname in compute:
            continue
        # NodeDefault/CompositeBase are universal roots whose
        # computeSubtreeFacts is abstract (`panic("not implemented")`) — never
        # a real provider; Go promotion picks the shallower base.
        provs = [b for b in base_closure(sname)
                 if b in compute and b not in ("NodeDefault", "CompositeBase")]
        if provs:
            if len(provs) > 1:
                print(f"WARN: {sname} has multiple computeSubtreeFacts "
                      f"providers {provs}; using {sorted(provs)[0]}")
            provider[sname] = sorted(provs)[0]

    for sname in sorted(set(compute) | set(provider)):
        if sname not in node_structs:
            continue
        body = compute.get(sname) or compute[provider[sname]]
        out.append(f"inline SubtreeFacts computeSubtreeFacts_{sname}(const {sname}* n) {{\n")
        for ln in facts_body(sname, body):
            out.append("\t" + ln + "\n")
        out.append("}\n\n")

    out.append("inline SubtreeFacts Node::computeSubtreeFacts() const {\n\tswitch (kind) {\n")
    seen_kinds = set()
    for sname in sorted(set(compute) | set(provider)):
        if sname not in node_structs:
            continue
        out.append(kinds_case(sname, seen_kinds))
        out.append(f"\t\t\treturn computeSubtreeFacts_{sname}(static_cast<const {sname}*>(this));\n")
    out.append("\t\tdefault:\n\t\t\treturn SubtreeFactsNone;\n\t}\n}\n\n")
    node_decls.append("\tSubtreeFacts computeSubtreeFacts() const;\n")

    out.append(
        "inline SubtreeFacts Node::subtreeFacts() const {\n\tswitch (kind) {\n")
    seen_kinds = set()
    for sname in sorted(node_structs):
        if has_field(sname, "facts"):
            out.append(kinds_case(sname, seen_kinds))
            out.append(f"\t\t\t{{ auto* n = static_cast<const {sname}*>(this);\n"
                       "\t\t\t\tuint32_t f = n->facts.load(std::memory_order_acquire);\n"
                       "\t\t\t\tif (!(f & SubtreeFactsComputed)) {\n"
                       "\t\t\t\t\tf = computeSubtreeFacts() | SubtreeFactsComputed;\n"
                       "\t\t\t\t\tn->facts.store(f, std::memory_order_release);\n"
                       "\t\t\t\t}\n"
                       "\t\t\t\treturn f & ~SubtreeFactsComputed; }\n")
    out.append("\t\tdefault:\n\t\t\treturn computeSubtreeFacts();\n\t}\n}\n\n")
    node_decls.append("\tSubtreeFacts subtreeFacts() const;\n")

    # ---- visitor machinery (visitor.go): Node::clone / Node::visitEachChild /
    # SourceFile::copyFrom, emitted into nodes_visitor_generated.h which is
    # included at the end of visitor.h (needs a complete NodeVisitor). ----
    node_decls.append("\tNode* clone(NodeFactory& f);\n")
    node_decls.append("\tNode* visitEachChild(NodeVisitor& v);\n")

    vout = ["// Clone + visitEachChild kind dispatch and SourceFile::copyFrom,\n",
            "// generated from ast_generated.go + ast.go by gencpp.py. DO NOT EDIT.\n",
            "#pragma once\n\nnamespace tsc {\n\n"]

    # SourceFile::copyFrom (ast.go) — Go stores a *copy* of contentMapperInfo;
    # our ContentMapperSourceFileInfo is an opaque pointer, so we share it.
    vout.append(
        "inline void SourceFile::copyFrom(SourceFile* other) {\n"
        "\t// Do not copy fields set by newSourceFile (text, fileName,\n"
        "\t// parseOptions, statements).\n"
        "\tif (other->contentMapperInfo != nullptr) {\n"
        "\t\tcontentMapperInfo = other->contentMapperInfo;\n"
        "\t}\n"
        "\tLanguageVariant = other->LanguageVariant;\n"
        "\tScriptKind = other->ScriptKind;\n"
        "\tIsDeclarationFile = other->IsDeclarationFile;\n"
        "\tUsesUriStyleNodeCoreModules = other->UsesUriStyleNodeCoreModules;\n"
        "\timports = other->imports;\n"
        "\tModuleAugmentations = other->ModuleAugmentations;\n"
        "\tAmbientModuleNames = other->AmbientModuleNames;\n"
        "\tCommentDirectives = other->CommentDirectives;\n"
        "\tPragmas = other->Pragmas;\n"
        "\tReferencedFiles = other->ReferencedFiles;\n"
        "\tTypeReferenceDirectives = other->TypeReferenceDirectives;\n"
        "\tLibReferenceDirectives = other->LibReferenceDirectives;\n"
        "\tCommonJSModuleIndicator = other->CommonJSModuleIndicator;\n"
        "\tExternalModuleIndicator = other->ExternalModuleIndicator;\n"
        "\tflags |= other->flags;\n"
        "}\n\n")

    # ---- Clone dispatch ----
    def visit_arg(a):
        m = re.match(r"v\.(visit\w+)\(node\.(\w+)\)", a.strip())
        if m:
            return f"v.{m.group(1)}Hooked(n->{sanitize(m.group(2))})"
        return go_expr(a, "n")

    vout.append("inline Node* Node::clone(NodeFactory& f) {\n"
                "\tswitch (kind) {\n")
    seen_kinds = set()
    for sname in sorted(struct_kinds):
        cases = kinds_case(sname, seen_kinds)
        if not cases:
            continue
        vout.append(cases)
        body = clone_methods.get(sname)
        if body is None or sname == "SourceFile":
            if sname == "SourceFile":
                vout.append(
                    "\t\t{\n"
                    "\t\t\tauto* n = static_cast<SourceFile*>(this);\n"
                    "\t\t\tauto* updated = f.newSourceFile(n->parseOptions,"
                    " n->text, n->Statements, n->EndOfFileToken);\n"
                    "\t\t\tupdated->as<SourceFile>()->copyFrom(n);\n"
                    "\t\t\treturn cloneNode(updated, n, f.hooks);\n"
                    "\t\t}\n")
            else:
                # structs without a Clone body (or the NodeDefault fallback)
                vout.append("\t\t{\n\t\t\treturn nullptr;\n\t\t}\n")
            continue
        # Kind-switched Clone bodies (multi-kind structs like
        # ImportDeclaration/TypeAliasDeclaration) dispatch on node.Kind.
        mswitch = re.search(r"switch node\.Kind \{\s*(.*?)\s*default:\s*"
                            r"panic\(.*?\)", body, re.S)
        if mswitch:
            vout.append(f"\t\t{{\n\t\t\tauto* n = static_cast<{sname}*>(this);\n"
                        "\t\t\tswitch (kind) {\n")
            for cm in re.finditer(
                    r"case (\w+):\s*return cloneNode\(f\.AsNodeFactory\(\)\."
                    r"(\w+)\((.*?)\),\s*node\.AsNode\(\),\s*f\.AsNodeFactory\(\)"
                    r"\.hooks\)", mswitch.group(1), re.S):
                k, newname, args_src = cm.group(1), cm.group(2), cm.group(3)
                args = ", ".join(go_expr(a, "n") for a in go_args(args_src))
                vout.append(f"\t\t\tcase Kind::{k[4:]}:\n"
                            f"\t\t\t\treturn cloneNode("
                            f"f.{newname[0].lower() + newname[1:]}({args}), "
                            f"n, f.hooks);\n")
            vout.append("\t\t\tdefault:\n"
                        f"\t\t\t\tTSC_UNREACHABLE(\"unexpected kind in "
                        f"{sname}::clone\");\n\t\t\t}}\n\t\t}}\n")
            continue
        m2 = re.search(
            r"cloneNode\(f\.AsNodeFactory\(\)\.(\w+)\((.*)\),\s*node\.AsNode\(\),\s*"
            r"f\.AsNodeFactory\(\)\.hooks\)", body, re.S)
        assert m2, f"unhandled Clone body for {sname}: {body[:200]}"
        newname, args_src = m2.group(1), m2.group(2)
        args = ", ".join(go_expr(a, "n") for a in go_args(args_src))
        vout.append(f"\t\t{{\n\t\t\tauto* n = static_cast<{sname}*>(this);\n"
                    f"\t\t\treturn cloneNode(f.{newname[0].lower() + newname[1:]}"
                    f"({args}), n, f.hooks);\n\t\t}}\n")
    vout.append("\t\tdefault:\n\t\t\treturn nullptr;\n\t}\n}\n\n")

    # ---- VisitEachChild dispatch ----
    vout.append("inline Node* Node::visitEachChild(NodeVisitor& v) {\n"
                "\tswitch (kind) {\n")
    seen_kinds = set()
    for sname in sorted(struct_kinds):
        cases = kinds_case(sname, seen_kinds)
        if not cases:
            continue
        body = vec_methods.get(sname)
        if body is not None:
            hm = re.match(r"\s*return visitEachChild_\w+\(node, v\)\s*$", body)
            if hm:
                body = vec_helpers[sname]
        vout.append(cases)
        if body is None:
            # NodeBase/Token fallback — returns the node itself.
            vout.append("\t\t{\n\t\t\treturn this;\n\t\t}\n")
            continue
        vout.append(f"\t\t{{\n\t\t\tauto* n = static_cast<{sname}*>(this);\n")
        sm = re.search(r"(\w+) := core\.SameMap\(node\.(\w+),", body)
        if sm:
            var, field = sm.group(1), sanitize(sm.group(2))
            vout.append(
                f"\t\t\tstd::vector<Node*> {var};\n"
                f"\t\t\t{var}.reserve(n->{field}.size());\n"
                f"\t\t\tfor (auto* c : n->{field})"
                f" {var}.push_back(v.visitNodeHooked(c));\n")
        um = re.search(r"return v\.Factory\.(\w+)\(node,\s*(.*)\)\s*$",
                       body, re.S)
        assert um, f"unhandled VisitEachChild body for {sname}: {body[:200]}"
        uname, args_src = um.group(1), um.group(2)
        args = []
        for a in go_args(args_src):
            if sm and a == sm.group(1):
                args.append(f"std::move({a})")
            else:
                args.append(visit_arg(a))
        vout.append(f"\t\t\treturn v.factory->{uname[0].lower() + uname[1:]}"
                    f"(n, {', '.join(args)});\n\t\t}}\n")
    vout.append("\t\tdefault:\n\t\t\treturn this;\n\t}\n}\n\n")

    vout.append("\n}  // namespace tsc\n")

    # Hand-maintained ports of the non-trivial ast.go helpers the generator
    # cannot auto-translate: the AccessKind machinery and the predicates whose
    # bodies are not pure kind checks. Keep in sync with tsc/internal/ast/ast.go.
    out.append(MANUAL_AST_HELPERS)

    out.append("\n}  // namespace tsc\n")
    def fix_flag_cmp(t):
        # Go `a & b != 0` parses as `(a & b) != 0`; C++ binds `!=` first.
        # Rewrite `ATOM [&|^] ATOM [...] ==/!= RHS` into a parenthesized group.
        atom = (r"(?:\([^()]*(?:\([^()]*\)[^()]*)*\)"
                r"|\{[^}]*\}"
                r"|[\w:>\-~]+(?:\(\))?)")
        pat = re.compile(
            r"(?<![\w>)\]:.])"
            r"((?:" + atom + r"\s*[&|^]\s*)+" + atom + r")"
            r"\s*(!=|==)\s*(\w+)")
        def repl(m):
            return "(" + m.group(1).strip() + ") " + m.group(2) + " " + m.group(3)
        prev = None
        while prev != t:
            prev = t
            t = pat.sub(repl, t)
        return t

    out_path = os.path.join(OUT, "ast", "nodes_generated.h")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    open(out_path, "w").write(fix_flag_cmp("".join(out)))
    open(os.path.join(OUT, "ast", "nodes_factory_decl.inc"), "w").write("".join(decls))
    open(os.path.join(OUT, "ast", "nodes_node_decl.inc"), "w").write("".join(node_decls))
    open(os.path.join(OUT, "ast", "nodes_visitor_generated.h"),
         "w").write(fix_flag_cmp("".join(vout)))
    # forward declarations for every node payload struct; included before
    # class NodeFactory in ast.h so update* decls can take typed pointers.
    fwd = ["// Forward declarations for every node payload struct.\n",
           "// Generated; DO NOT EDIT.\n"]
    for sname in sorted(node_structs):
        fwd.append(f"struct {sname};\n")
    open(os.path.join(OUT, "ast", "nodes_fwd_decl.inc"), "w").write("".join(fwd))
    print(f"wrote {out_path} (+ node/factory/fwd decl + visitor includes)")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "all"
    if cmd in ("kinds", "all"):
        gen_kinds()
    if cmd in ("diagnostics", "all"):
        gen_diagnostics()
    if cmd in ("unicode", "all"):
        gen_unicode()
    if cmd in ("nodes", "all"):
        gen_nodes()
