#!/usr/bin/env python3
"""gencpp.py — generate C++ headers from the Go sources in tsc/internal.

Subcommands:
  kinds       -> internal/ast/kind.h          (Kind enum + range constants + name table)
  diagnostics -> internal/diagnostics/messages_generated.h
  unicode     -> internal/stringutil/unicode_tables.h
  nodes       -> internal/ast/nodes_generated.h (flattened node structs + factory + dispatch)

Run from the repository root: python3 cpp/tools/gencpp.py <subcommand>
"""
import re
import sys
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TSC = os.path.join(ROOT, "tsc", "internal")
OUT = os.path.join(ROOT, "cpp", "internal")

HEADER = "// Code generated by cpp/tools/gencpp.py from tsc/internal Go sources; DO NOT EDIT.\n"

# ----------------------------------------------------------------------------
# Kind enum
# ----------------------------------------------------------------------------

def load_kinds():
    """Returns (enum_members, range_consts) from kind_generated.go."""
    src = open(os.path.join(TSC, "ast", "kind_generated.go")).read()
    const_block = re.search(r"const \(\n(.*?)\n\)", src, re.S).group(1)
    kinds = []
    singles = {}
    for line in const_block.split("\n"):
        line = line.strip()
        if not line:
            continue
        if re.match(r"Kind\w+\s*(Kind\s*)?=\s*iota", line):
            kinds.append(re.match(r"(Kind\w+)", line).group(1))
            continue
        if "=" in line:
            m = re.match(r"(Kind\w+)\s*=\s*(.+)", line)
            if m:
                singles[m.group(1)] = m.group(2).strip()
            continue
        m = re.match(r"(Kind\w+)", line)
        if m:
            kinds.append(m.group(1))
    for m in re.finditer(r"const (Kind\w+) = ([^\n]+)", src):
        singles[m.group(1)] = m.group(2).strip()
    return kinds, singles


def gen_kinds():
    kinds, singles = load_kinds()

    # names from kind_stringer_generated.go: `_Kind_name = "UnknownEndOfFile..."`
    strsrc = open(os.path.join(TSC, "ast", "kind_stringer_generated.go")).read()
    name_blob = re.search(r'_Kind_name = "([^"]*)"', strsrc).group(1)
    idx_vals = [int(x) for x in re.search(
        r"_Kind_index = \[\.\.\.\]uint16\{([^}]*)\}", strsrc).group(1).split(",")]
    names = []
    for i in range(len(idx_vals) - 1):
        n = name_blob[idx_vals[i]:idx_vals[i + 1]]
        names.append(n[4:] if n.startswith("Kind") else n)

    lines = [HEADER]
    lines.append("#pragma once\n")
    lines.append("#include <cstdint>\n#include <string_view>\n")
    lines.append("namespace tsc {\n\n")
    lines.append("enum class Kind : int16_t {\n")
    for k in kinds:
        lines.append(f"\t{k[4:]},")  # strip "Kind" prefix -> bare name
    lines.append("};\n\n")
    lines.append("inline constexpr int KindCount = static_cast<int>(Kind::Count);\n\n")
    for name, expr in singles.items():
        if name == "KindCount":
            continue
        kindset = set(kinds)
        cxx = re.sub(
            r"\bKind(\w+)",
            lambda m: f"Kind::{m.group(1)}"
            if "Kind" + m.group(1) in kindset
            else m.group(0),
            expr)
        lines.append(f"inline constexpr Kind {name[4:] + 'Const' if False else name} = {cxx};\n")
    lines.append("\n")
    # name table
    lines.append("inline constexpr std::string_view kKindNames[] = {\n")
    for n in names:
        lines.append(f'\t"{n}",\n')
    lines.append("};\n\n")
    lines.append("inline constexpr std::string_view kindToString(Kind k) {\n")
    lines.append("\treturn kKindNames[static_cast<int>(k)];\n}\n\n")
    lines.append("}  // namespace tsc\n")
    out = os.path.join(OUT, "ast", "kind.h")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("".join(lines))
    print(f"wrote {out} ({len(kinds)} kinds, {len(names)} names)")


# ----------------------------------------------------------------------------
# Diagnostics messages
# ----------------------------------------------------------------------------

def gen_diagnostics():
    src = open(os.path.join(TSC, "diagnostics", "diagnostics_generated.go")).read()
    # var Name = &Message{code: N, category: CategoryX, key: "...", text: "..."}
    pat = re.compile(
        r'var (\w+) = &Message\{\s*code:\s*(-?\d+),\s*category:\s*(\w+),\s*key:\s*"([^"]*)",\s*text:\s*"((?:[^"\\]|\\.)*)"\s*\}',
        re.S)
    entries = []
    for m in pat.finditer(src):
        name, code, cat, key, text = m.groups()
        text = bytes(text, "utf-8").decode("unicode_escape")
        entries.append((name, int(code), cat, key, text))
    print(f"parsed {len(entries)} diagnostics")

    def cxxstr(s):
        s = s.replace("\\", "\\\\").replace('"', '\\"')
        s = s.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
        out = []
        for ch in s:
            o = ord(ch)
            if o < 32 or o > 126:
                out.append(f"\\x{o:02x}\\x{0:02x}"[:0] or f'\\u{o:04x}' if False else ch)
            else:
                out.append(ch)
        # safer: encode as UTF-8 with \xNN pairs terminated properly — use \u literals? Go text is
        # unicode; emit UTF-8 bytes escaped
        enc = []
        for b in s.encode("utf-8"):
            if 32 <= b < 127 and b not in (34, 92):
                enc.append(chr(b))
            elif b == 34:
                enc.append('\\"')
            elif b == 92:
                enc.append("\\\\")
            elif b == 10:
                enc.append("\\n")
            elif b == 9:
                enc.append("\\t")
            else:
                enc.append(f"\\x{b:02x}")
        return "".join(enc)

    lines = [HEADER]
    lines.append("#pragma once\n")
    lines.append("namespace tsc {\n\n")
    lines.append("// const DiagnosticMessage& name or nullptr; emitted as a flat table.\n")
    lines.append("inline constexpr DiagnosticMessage kDiagnosticMessages[] = {\n")
    for name, code, cat, key, text in entries:
        cxxcat = {"CategoryError": "DiagnosticCategory::Error",
                  "CategoryWarning": "DiagnosticCategory::Warning",
                  "CategorySuggestion": "DiagnosticCategory::Suggestion",
                  "CategoryMessage": "DiagnosticCategory::Message"}[cat]
        lines.append(f'\t{{{code}, {cxxcat}, "{cxxstr(key)}", "{cxxstr(text)}"}},  // {name}\n')
    lines.append("};\n\n")
    lines.append("// Named accessors matching the Go package-level vars.\n")
    for i, (name, code, cat, key, text) in enumerate(entries):
        lines.append(f"inline const DiagnosticMessage* {name} = &kDiagnosticMessages[{i}];\n")
    lines.append("\n}  // namespace tsc\n")
    out = os.path.join(OUT, "diagnostics", "messages_generated.h")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("".join(lines))
    print(f"wrote {out}")


# ----------------------------------------------------------------------------
# Unicode identifier tables
# ----------------------------------------------------------------------------

def gen_unicode():
    src = open(os.path.join(TSC, "stringutil", "identifier_parts_generated.go")).read()
    # unicodeESNextIdentifierStart = &unicode.RangeTable{ R16: []unicode.Range16{...}, R32: ..., LatinOffset: n}
    def parse_rt(varname):
        m = re.search(varname + r"\s*=\s*&unicode\.RangeTable\{(.*?)\}\n", src, re.S)
        body = m.group(1)
        def section(nm):
            m2 = re.search(nm + r":\s*\[\]unicode\.Range\d+\{(.*?)\n\s*\},", body, re.S)
            return [tuple(int(x, 0) for x in t.split(",")) for t in
                    re.findall(r"\{([^}]+)\}", m2.group(1))] if m2 else []
        lat = re.search(r"LatinOffset:\s*(\d+)", body)
        return section("R16"), section("R32"), int(lat.group(1)) if lat else 0

    lines = [HEADER, "#pragma once\n", "#include <cstdint>\n\nnamespace tsc {\n\n"]
    for var, cxx in [("unicodeESNextIdentifierStart", "kIdentifierStart"),
                     ("unicodeESNextIdentifierPart", "kIdentifierPart")]:
        r16, r32, lat = parse_rt(var)
        lines.append(f"inline constexpr uint16_t {cxx}R16[][3] = {{\n")
        for lo, hi, stride in r16:
            lines.append(f"\t{{{lo}, {hi}, {stride}}},\n")
        lines.append("};\n")
        lines.append(f"inline constexpr uint32_t {cxx}R32[][3] = {{\n")
        for lo, hi, stride in r32:
            lines.append(f"\t{{{lo}, {hi}, {stride}}},\n")
        lines.append("};\n")
        lines.append(f"inline constexpr int {cxx}LatinOffset = {lat};\n\n")
        print(f"{var}: {len(r16)} r16, {len(r32)} r32, latinOffset={lat}")
    lines.append("}  // namespace tsc\n")
    out = os.path.join(OUT, "stringutil", "unicode_tables.h")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("".join(lines))
    print(f"wrote {out}")


# ----------------------------------------------------------------------------
# Node structs — the big one
# ----------------------------------------------------------------------------

# Go builtin/foreign types that are NOT node structs (map to C++ directly or as
# forward-declared pointers)
GO_VALUE_TYPES = {
    "string": "std::string",
    "bool": "bool",
    "core.TextRange": "::tsc::TextRange",
    "core.LanguageVariant": "::tsc::LanguageVariant",
    "core.ScriptKind": "::tsc::ScriptKind",
    "core.Tristate": "::tsc::Tristate",
    "core.ScriptTarget": "::tsc::ScriptTarget",
    "core.ResolutionMode": "::tsc::ResolutionMode",
    "::tsc::TokenFlags": "::tsc::TokenFlags",
    "::tsc::NodeFlags": "::tsc::NodeFlags",
    "::tsc::ModifierFlags": "::tsc::ModifierFlags",
    "::tsc::CheckFlags": "::tsc::CheckFlags",
    "::tsc::FunctionFlags": "::tsc::FunctionFlags",
    "::tsc::SubtreeFacts": "::tsc::SubtreeFacts",
    "LanguageFeatureMinimumTarget": "int",
    "::tsc::LanguageVariant": "::tsc::LanguageVariant",
    "::tsc::ScriptKind": "::tsc::ScriptKind",
    "::tsc::Tristate": "::tsc::Tristate",
    "::tsc::ScriptTarget": "::tsc::ScriptTarget",
    "::tsc::SourceFileParseOptions": "::tsc::SourceFileParseOptions",
    "::tsc::ExternalModuleIndicatorOptions": "::tsc::ExternalModuleIndicatorOptions",
    "::tsc::CommentDirectiveKind": "::tsc::CommentDirectiveKind",
    "::tsc::CommentDirective": "::tsc::CommentDirective",
    "::tsc::CommentRange": "::tsc::CommentRange",
    "::tsc::Pragma": "::tsc::Pragma",
    "::tsc::FileReference": "::tsc::FileReference",
    "::tsc::CheckJsDirective": "::tsc::CheckJsDirective",
    "::tsc::PatternAmbientModule": "::tsc::PatternAmbientModule",
    "tspath.Path": "std::string",
    "xxh3.Uint128": "::tsc::Uint128",
    "core.TextPos": "::tsc::TextPos",
    "::tsc::TextPos": "::tsc::TextPos",
    "core.ModuleKind": "::tsc::ModuleKind",
    "::tsc::ModuleKind": "::tsc::ModuleKind",
    "::tsc::ResolutionMode": "::tsc::ResolutionMode",
    "ScriptReferenceHost": "void*",
    "::tsc::CommentDirective": "::tsc::CommentDirective",
    "::tsc::MappedDiagnosticDirective": "::tsc::MappedDiagnosticDirective",
    "::tsc::SourceFileMetaData": "::tsc::SourceFileMetaData",
    "::tsc::Kind": "::tsc::Kind",
    "int": "int32_t",
    "int32": "int32_t",
    "int64": "int64_t",
    "uint32": "uint32_t",
    "uint64": "uint64_t",
    "atomic.Uint32": "CopyableAtomic<uint32_t>",
    "atomic.Uint64": "CopyableAtomic<uint64_t>",
    "atomic.Bool": "CopyableAtomic<bool>",
    "sync.Mutex": "std::mutex",
    "sync.RWMutex": "std::shared_mutex",
    "sync.Once": "::tsc::OnceFlag",
    "::tsc::SymbolTable": "::tsc::SymbolTable",
}

NON_NODE_PTR = {
    "Symbol", "FlowNode", "Diagnostic", "FileReference", "CheckJsDirective",
    "NodeFactory", "PositionMap", "ContentMapperSourceFileInfo", "ModuleResolutionKind",
    "TokenCacheKey", "RepopulateDiagnosticInfo", "SourceFileMetaData",
    "SymbolId", "SymbolLinks", "DeclarationBitMaps", "SymbolFormatFlags",
    "ModifierListCache", "QueuedMap", "Extension",
}

CPP_RESERVED = {
    "operator": "op", "template": "template_", "new": "new_", "delete": "delete_",
    "this": "self", "class": "class_", "namespace": "namespace_", "typename": "typename_",
    "virtual": "virtual_", "switch": "switch_", "case": "case_", "default": "default_",
    "register": "register_", "typeid": "typeid_", "and": "and_", "or": "or_", "not": "not_",
    "xor": "xor_", "signed": "signed_", "unsigned": "unsigned_", "long": "long_",
    "short": "short_", "float": "float_", "double": "double_", "char": "char_",
    "int": "int_", "bool": "bool_", "union": "union_", "enum": "enum_", "struct": "struct_",
    "friend": "friend_", "inline": "inline_", "const": "const_", "static": "static_",
    "extern": "extern_", "auto": "auto_", "sizeof": "sizeof_", "return": "return_",
    "if": "if_", "else": "else_", "for": "for_", "while": "while_", "do": "do_",
    "break": "break_", "continue": "continue_", "goto": "goto_", "try": "try_",
    "catch": "catch_", "throw": "throw_", "public": "public_", "private": "private_",
    "protected": "protected_", "constexpr": "constexpr_", "nullptr": "nullptr_",
    "export": "export_", "import": "import_", "module": "module_", "requires": "requires_",
    "concept": "concept_", "co_await": "co_await_", "co_return": "co_return_",
    "co_yield": "co_yield_", "mutable": "mutable_", "volatile": "volatile_",
    "wchar_t": "wchar_t_", "char8_t": "char8_t_", "char16_t": "char16_t_",
    "char32_t": "char32_t_", "true": "true_", "false": "false_",
    "type": "type_",  # not reserved in C++ but `type` reads badly; keep it though:
}
# `type` IS a legal C++ identifier; keep it legal:
del CPP_RESERVED["type"]


def sanitize(name):
    return CPP_RESERVED.get(name, name)


def parse_structs(*files):
    """Parse `type X struct { ... }` and `type X = Y` aliases; returns
    (structs: {name: [(field_name, go_type, is_embedded)]}, aliases: {name: target}).
    Embedded fields appear as (None, type_name, True)."""
    structs = {}
    aliases = {}
    struct_pat = re.compile(r"^type (\w+) struct\s*\{", re.M)
    for path in files:
        src = open(path).read()
        for m in struct_pat.finditer(src):
            name = m.group(1)
            i = m.end()
            depth = 1
            while depth > 0:
                c = src[i]
                if c == "{":
                    depth += 1
                elif c == "}":
                    depth -= 1
                i += 1
            body = src[m.end():i - 1]
            fields = []
            for line in body.split("\n"):
                line = line.strip()
                if not line or line.startswith("//"):
                    continue
                line = re.sub(r"//.*$", "", line).strip()  # strip trailing comment
                if not line:
                    continue
                line = re.sub(r"`[^`]*`", "", line).strip()  # strip tags
                parts = line.split(None, 1)
                if len(parts) == 1:
                    fields.append((None, parts[0], True))  # embedded
                else:
                    fname, ftype = parts[0], parts[1].strip()
                    # multi-name fields `a, b T`
                    names = [n.strip() for n in fname.split(",")]
                    for n in names:
                        fields.append((n, ftype, False))
            structs[name] = fields
        # standalone `type X = Y` aliases
        for m in re.finditer(r"^type (\w+) = (\w+)", src, re.M):
            aliases[m.group(1)] = m.group(2).strip()
        # `type ( X = Y ... )` blocks
        for bm in re.finditer(r"^type \(\n(.*?)\n\)", src, re.S | re.M):
            for am in re.finditer(r"^\s*(\w+)\s*=\s*(\w+)", bm.group(1), re.M):
                aliases[am.group(1)] = am.group(2).strip()
    return structs, aliases


NODE_CORE_FIELDS = {"Kind", "Flags", "Loc", "id", "Parent", "data"}


def flatten(structs, name, seen=None):
    """DFS-expand embedded bases; dedupe by field name. The `Node` core
    fields are skipped because C++ node structs inherit `struct Node`."""
    out = []
    have = set()
    def go(n):
        for fname, ftype, emb in structs.get(n, []):
            if emb:
                base = ftype.lstrip("*")
                if base in structs:
                    go(base)
                else:
                    # embedded external (e.g. NodeBase chain end) -> keep as field
                    if base not in have:
                        have.add(base)
                        out.append((base.lower() + "_", base, False))
            else:
                if n == "Node" or fname in NODE_CORE_FIELDS:
                    continue
                if fname in have:
                    continue
                have.add(fname)
                out.append((fname, ftype, False))
    go(name)
    return out


def go_type_to_cpp(t, node_structs, aliases):
    """Map a Go type to a C++ type. Pointers to node-ish things -> Node* /
    NodeList* / ModifierList*; pointers to foreign structs -> X*; slices ->
    std::vector<>; maps -> std::unordered_map<>."""
    t = t.strip()
    # resolve aliases of the form `type X = T`
    def resolve(a):
        while a in aliases:
            a = aliases[a]
        return a
    if t.startswith("[]"):
        inner = go_type_to_cpp(t[2:], node_structs, aliases)
        return f"std::vector<{inner}>"
    if t.startswith("map[") or t.startswith("collections.OrderedMap[") or \
       t.startswith("sync.Map["):
        m = re.match(r"(?:map|collections\.OrderedMap|sync\.Map)\[([^\]]+)\](.+)$", t)
        k = go_type_to_cpp(m.group(1), node_structs, aliases)
        v = go_type_to_cpp(m.group(2), node_structs, aliases)
        return f"std::unordered_map<{k}, {v}>"
    if t.startswith("collections.Set[") or t.startswith("collections.SetOrStar["):
        inner = go_type_to_cpp(t[t.index("[") + 1:-1], node_structs, aliases)
        return f"std::unordered_set<{inner}>"
    if t.startswith("collections.Heap["):
        inner = go_type_to_cpp(t[t.index("[") + 1:-1], node_structs, aliases)
        return f"std::vector<{inner}>"
    if t == "any" or t == "interface{}":
        return "void*"
    if t.startswith("*"):
        base = resolve(t[1:]).lstrip("*")
        if base == "ModifierList":
            return "::tsc::ModifierList*"
        if base.endswith("List") or base == "NodeList":
            return "::tsc::NodeList*"
        if base in NON_NODE_PTR:
            return "::tsc::" + base + "*"
        if base == "Node" or base in node_structs or base.endswith("Node") or \
           base.endswith("Token") or base.endswith("Literal") or \
           base in ("DeclarationName", "EntityName", "EntityNameExpression",
                    "BindingPattern", "BindingName", "PropertyName", "TypeNode",
                    "Expression", "Statement", "ModuleName", "ModuleExportName",
                    "ForInitializer", "LiteralLikeNode", "TemplateLiteralLikeNode",
                    "JsxAttributeLike", "JsxAttributeValue", "JsxChild",
                    "JsxTagNameExpression", "ClassLikeDeclaration", "AssertionExpression",
                    "NamedMember", "ModifierLike", "ClassLikeBody", "BlockLike",
                    "VariableLikeDeclaration", "SignatureDeclaration",
                    "EnumMember", "ModuleBody", "AccessorDeclaration", "Modifier",
                    "ConciseBody", "FunctionBody", "IncrementExpression",
                    "JSDocComment", "JSDocTag", "ObjectLiteralElementLike"):
            return "::tsc::Node*"
        # unknown pointer type — emit a forward-declared struct pointer
        return "::tsc::" + base + "*"
    base = resolve(t)
    if base.startswith("collections.Set["):
        inner = go_type_to_cpp(base[base.index("[") + 1:-1], node_structs, aliases)
        return f"std::unordered_set<{inner}>"
    if base in GO_VALUE_TYPES:
        return GO_VALUE_TYPES[base]
    if base.endswith("SyntaxKind") or base == "SyntaxKind":
        return "Kind"
    if base.endswith("List") and base != "ModifierList":
        return "::tsc::NodeList"
    if base in node_structs or base == "Node":
        return "::tsc::Node"
    if base == "ModifierList":
        return "::tsc::ModifierList"
    if base[:1].isupper():
        return "::tsc::" + base
    return base


def gen_nodes():
    gendir = os.path.join(TSC, "ast")
    structs, aliases = parse_structs(os.path.join(gendir, "ast.go"),
                                     os.path.join(gendir, "ast_generated.go"))
    src_all = open(os.path.join(gendir, "ast.go")).read() + "\n" + \
              open(os.path.join(gendir, "ast_generated.go")).read()
    # strip // comments so doc text can't fake a declaration match
    src_all = re.sub(r"//[^\n]*", "", src_all)

    # Which structs are node payloads?  Those reachable via newNode(Kind*, data)
    # where data's static type is the struct. Find `data := f.<arena>.New()` and
    # `data := &X{}` inside each New* factory, plus the arena decls.
    arena_types = dict(re.findall(r"(\w+)[ \t]+core\.Arena\[(\w+)\]", src_all))
    node_structs = set()
    factory_methods = {}   # method name -> (kind_const, struct_name, [args], {field: arg})
    new_pat = re.compile(
        r"func \(f \*NodeFactory\) (New\w+)\((.*?)\) \*Node \{\n(.*?)\n\}", re.S)
    for m in new_pat.finditer(src_all):
        fname, args_src, body = m.group(1), m.group(2), m.group(3)
        dm = re.search(r"data := f\.(\w+)\.New\(\)", body)
        if dm:
            sname = arena_types.get(dm.group(1))
            if not sname:
                continue
        else:
            dm = re.search(r"data := &(\w+)\{\}", body)
            if not dm:
                continue
            sname = dm.group(1)
        km = re.search(r"f\.newNode\((\w+)", body)
        if not km:
            continue
        kind = km.group(1)
        if kind == "kind":
            # kind passed as a parameter — collect concrete kinds from call sites
            kind = None
        # parse args
        args = []
        for argm in re.finditer(r"(\w+)\s+([^\s,\)]+(?:\[\]\*?\w+)?)", args_src):
            args.append((argm.group(1), argm.group(2)))
        # field assignments data.X = expr
        assigns = re.findall(r"data\.(\w+) = ([^\n]+)", body)
        # post-construction node assignments, e.g. `node.Flags = flags`
        node_assigns = re.findall(r"node\.(\w+) (\|=|&=|\^=|=) ([^\n]+)", body)
        node_structs.add(sname)
        factory_methods[fname] = (kind, sname, args, assigns, node_assigns)

    # Also catch `f.textCount++` markers (identifiers / literals) — record them.
    textcount = {}
    for m in new_pat.finditer(src_all):
        textcount[m.group(1)] = "f.textCount++" in m.group(3)

    # Is* predicates (ast.go + ast_generated.go — pure kind checks)
    predicates = []
    seen_pred = set()
    for m in re.finditer(
            r"func (Is\w+)\(node \*Node\) bool \{\n(.*?)\n\}", src_all, re.S):
        if m.group(1) not in seen_pred:
            seen_pred.add(m.group(1))
            predicates.append((m.group(1), m.group(2).strip()))

    # ForEachChild bodies per struct
    foreach = {}
    for m in re.finditer(
            r"func \(node \*(\w+)\) ForEachChild\(v Visitor\) bool \{\n(.*?)\n\}",
            src_all, re.S):
        sname, body = m.group(1), m.group(2)
        calls = re.findall(r"(visitModifiers|visitNodeList|visit)\(v, node\.(\w+)\)", body)
        foreach[sname] = calls

    # Simple accessors: func (node *X) Foo() *T { return node.f }
    accessors = {}  # accessor -> {struct: (ret_type, field)}
    acc_pat = re.compile(
        r"func \(node \*(\w+)\) (\w+)\(\) ([^\s{]+) \{\n\treturn node\.(\w+)\s*\n\}")
    for m in acc_pat.finditer(src_all):
        sname, meth, ret, field = m.groups()
        accessors.setdefault(meth, {})[sname] = (ret, field)

    # kind -> struct map (a struct may serve multiple kinds). Methods taking
    # `kind` as a parameter are resolved by scanning every Go caller.
    all_src = ""
    for dirpath, _, fns in os.walk(TSC):
        for fn in fns:
            if fn.endswith(".go"):
                all_src += open(os.path.join(dirpath, fn)).read()
    struct_kinds = {}   # struct -> [kind,...]
    for fname, (kind, sname, args, assigns, node_assigns) in \
            factory_methods.items():
        struct_kinds.setdefault(sname, [])
        ks = [kind] if kind else []
        if kind is None:
            for cm in re.finditer(fname + r"\((?:ast\.)?(Kind\w+)", all_src):
                ks.append(cm.group(1))
        for k in ks:
            if k and k not in struct_kinds[sname]:
                struct_kinds[sname].append(k)

    # Variable-kind factories (e.g. NewJSDocParameterOrPropertyTag(kind, ...))
    # can't be bound by scanning callers; instead read the authoritative
    # kind -> struct mapping out of the generated Node.ForEachChild dispatch:
    #   case KindA, KindB:
    #       return n.data.(*StructName).ForEachChild(v)
    for cm in re.finditer(
            r"case ((?:ast\.)?Kind\w+(?:,\s*(?:ast\.)?Kind\w+)*)\s*:\s*\n"
            r"\s*return n\.data\.\(\*?(\w+)\)",
            all_src):
        kinds_str, sname = cm.group(1), cm.group(2)
        if sname not in node_structs:
            continue
        for k in re.findall(r"Kind\w+", kinds_str):
            if k not in struct_kinds.get(sname, []):
                struct_kinds.setdefault(sname, []).append(k)

    print(f"{len(node_structs)} node structs, {len(factory_methods)} factory methods, "
          f"{len(predicates)} predicates, {len(foreach)} forEachChild, "
          f"{len(accessors)} accessors")

    # ---- emit ----
    out = [HEADER, "#pragma once\n",
           "#include <atomic>\n#include <cstdint>\n#include <memory>\n#include <mutex>\n"
           "#include <shared_mutex>\n#include <string>\n#include <unordered_map>\n"
           "#include <unordered_set>\n#include <vector>\n",
           "#include \"internal/core/arena.h\"\n#include \"internal/core/text.h\"\n"
           "#include \"internal/ast/flags.h\"\n#include \"internal/ast/kind.h\"\n",
           "namespace tsc {\n\n"]

    node_structs.add("SourceFile")

    field_renames = {"ecmaLineMap": "ecmaLineMap_"}

    extra_members = {
        "SourceFile": (
            "\tconst std::vector<::tsc::TextPos>& ecmaLineMap();\n"
            "\tstd::vector<::tsc::Node*> resolveJSDoc(::tsc::Node* n);\n"
            "\tvoid setHasLazyJSDoc(bool lazy) { hasLazyJSDoc = lazy; }\n"
        ),
    }

    # flatten + emit each node struct
    flat = {}
    for sname in sorted(node_structs):
        fields = flatten(structs, sname)
        flat[sname] = fields
        out.append(f"struct {sname} : Node {{\n")
        if sname in extra_members:
            out.append(extra_members[sname])
        for fname, gtype, _ in fields:
            cxx = go_type_to_cpp(gtype, node_structs, aliases)
            cf = sanitize(fname)
            cf = field_renames.get(cf, cf)
            # default-init scalars
            if cxx in ("bool",):
                out.append(f"\t{cxx} {cf}{{}};\n")
            elif cxx in ("int32_t", "int64_t", "uint32_t", "uint64_t"):
                out.append(f"\t{cxx} {cf}{{}};\n")
            elif "Atomic<" in cxx:
                out.append(f"\tmutable {cxx} {cf}{{}};\n")
            elif cxx.endswith("*"):
                out.append(f"\t{cxx} {cf}{{}};\n")
            elif cxx in ("::tsc::TokenFlags", "::tsc::NodeFlags", "::tsc::ModifierFlags",
                         "::tsc::CheckFlags", "::tsc::FunctionFlags", "::tsc::SubtreeFacts",
                         "::tsc::LanguageVariant", "::tsc::ScriptKind", "::tsc::Tristate",
                         "::tsc::ScriptTarget", "::tsc::ResolutionMode",
                         "::tsc::CommentDirectiveKind", "Kind", "int"):
                out.append(f"\t{cxx} {cf}{{}};\n")
            else:
                out.append(f"\t{cxx} {cf};\n")
        out.append("};\n\n")

    # ---- NodeFactory methods ----
    out.append("// Factory methods (generated from New* in ast_generated.go).\n\n")
    decls = ["// Method declarations for class NodeFactory; included inside the class\n",
             "// body in ast.h. Generated; DO NOT EDIT.\n"]
    for fname, (kind, sname, args, assigns, node_assigns) in \
            factory_methods.items():
        cxx = fname[0].lower() + fname[1:]  # NewX -> newX
        sig = ", ".join(f"{go_type_to_cpp(t, node_structs, aliases)} {sanitize(n)}"
                        for n, t in args)
        decls.append(f"\tNode* {cxx}({sig});\n")
        out.append(f"inline Node* NodeFactory::{cxx}({sig}) {{\n")
        out.append(f"\tauto* data = arena_.alloc<{sname}>();\n")
        for f, expr in assigns:
            e = sanitize(expr.strip())
            out.append(f"\tdata->{sanitize(f)} = {e};\n")
        if textcount.get(fname):
            out.append("\ttextCount_++;\n")
        k = "Kind::" + kind[4:] if kind else "kind"
        if node_assigns:
            out.append(f"\tauto* node = newNode({k}, data);\n")
            for nf, nop, nexpr in node_assigns:
                ne = sanitize(nexpr.strip())
                field = {"Flags": "flags", "Loc": "loc",
                         "Parent": "parent"}.get(nf, sanitize(nf))
                out.append(f"\tnode->{field} {nop} {ne};\n")
            out.append("\treturn node;\n}\n\n")
        else:
            out.append(f"\treturn newNode({k}, data);\n}}\n\n")

    # ---- dispatch ----
    out.append("// forEachChild / name / modifiers dispatch (generated).\n\n")

    # Group structs -> kinds for switch emission
    def kinds_case(sname, seen=None):
        ks = struct_kinds.get(sname, [])
        out_s = ""
        for k in ks:
            if seen is not None:
                if k in seen:
                    continue
                seen.add(k)
            out_s += f"\t\tcase Kind::{k[4:]}:\n"
        return out_s

    out.append("template <class F>\nbool Node::forEachChild(F&& v) const {\n")
    out.append("\tswitch (kind) {\n")
    seen_kinds = set()
    for sname, calls in sorted(foreach.items()):
        if not calls:
            continue
        out.append(kinds_case(sname, seen_kinds))
        out.append(f"\t\t{{\n\t\t\tauto* n = static_cast<const {sname}*>(this);\n")
        parts = []
        for fn, field in calls:
            cf = sanitize(field)
            if fn == "visit":
                parts.append(f"visitChild(v, n->{cf})")
            elif fn == "visitNodeList":
                parts.append(f"visitChildList(v, n->{cf})")
            elif fn == "visitModifiers":
                parts.append(f"visitChildModifiers(v, n->{cf})")
        out.append("\t\t\treturn " + " ||\n\t\t\t\t".join(parts) + ";\n\t\t}\n")
    out.append("\t\tdefault:\n\t\t\treturn false;\n\t}\n}\n\n")

    # deepClone dispatch (generated): one case per struct, cloning every child
    # field per the same visit* list used by forEachChild.
    out.append("// deepClone dispatch (generated).\n\n")
    out.append("inline Node* deepCloneNode(NodeFactory& f, const Node* node);\n")
    out.append("inline NodeList* deepCloneNodeList(NodeFactory& f,\n"
               "                                   const NodeList* l);\n")
    out.append("inline ModifierList* deepCloneModifierList(NodeFactory& f,\n"
               "                                           const ModifierList* m);\n\n")
    out.append("inline NodeList* deepCloneNodeList(NodeFactory& f,\n"
               "                                   const NodeList* l) {\n"
               "\tif (l == nullptr) return nullptr;\n"
               "\tauto* c = f.arena().alloc<NodeList>(*l);\n"
               "\tfor (auto& n : c->nodes) n = deepCloneNode(f, n);\n"
               "\treturn c;\n}\n\n")
    out.append("inline ModifierList* deepCloneModifierList(NodeFactory& f,\n"
               "                                           const ModifierList* m) {\n"
               "\tif (m == nullptr) return nullptr;\n"
               "\tauto* c = f.arena().alloc<ModifierList>(*m);\n"
               "\tfor (auto& n : c->nodes) n = deepCloneNode(f, n);\n"
               "\tc->ModifierFlags = NodeFactory::modifiersToFlags(c->nodes);\n"
               "\treturn c;\n}\n\n")
    out.append("inline Node* deepCloneNode(NodeFactory& f, const Node* node) {\n"
               "\tif (node == nullptr) return nullptr;\n"
               "\tswitch (node->kind) {\n")
    seen_kinds = set()
    for sname in sorted(struct_kinds):
        cases = kinds_case(sname, seen_kinds)
        if not cases:
            continue
        out.append(cases)
        if sname == "SourceFile":
            # SourceFile is never a clone target (mutexes aren't copyable);
            # keep the case for exhaustive switching.
            out.append("\t\t{\n\t\t\treturn nullptr;\n\t\t}\n")
            continue
        out.append(f"\t\t{{\n\t\t\tauto* n = static_cast<const {sname}*>(node);\n")
        out.append(f"\t\t\tauto* c = f.arena().alloc<{sname}>(*n);\n")
        for fn, field in foreach.get(sname, []):
            cf = sanitize(field)
            tgt = {"visit": "deepCloneNode",
                   "visitNodeList": "deepCloneNodeList",
                   "visitModifiers": "deepCloneModifierList"}[fn]
            out.append(f"\t\t\tc->{cf} = {tgt}(f, n->{cf});\n")
        out.append("\t\t\treturn c;\n\t\t}\n")
    out.append("\t\tdefault:\n"
               "\t\t\t// Leaf token kinds clone as plain Token nodes (they have\n"
               "\t\t\t// no children and carry no extra fields).\n"
               "\t\t\tif (node->kind <= KindLastToken) {\n"
               "\t\t\t\tauto* n = static_cast<const Token*>(node);\n"
               "\t\t\t\treturn f.arena().alloc<Token>(*n);\n"
               "\t\t\t}\n"
               "\t\t\treturn nullptr;\n"
               "\t}\n}\n\n")

    # name()/modifiers() etc: accessors found above
    node_decls = ["// Method declarations for struct Node; included inside the struct\n",
                  "// body in ast.h. Generated; DO NOT EDIT.\n",
                  "\ttemplate <class F> bool forEachChild(F&& v) const;\n"]
    for meth, per_struct in sorted(accessors.items()):
        cxxmeth = meth[0].lower() + meth[1:]
        # common return type across structs
        rets = {go_type_to_cpp(r, node_structs, aliases) for r, f in per_struct.values()}
        ret = rets.pop() if len(rets) == 1 else "Node*"
        # skip accessors we hand-write
        if cxxmeth in ("asNode", "forEachChild", "visitEachChild", "clone",
                       "subtreeFacts", "flowNodeData", "declarationData",
                       "exportableData", "localsContainerData", "functionLikeData",
                       "classLikeData", "bodyData", "literalLikeData",
                       "templateLiteralLikeData", "modifiers",
                       "text"):
            continue
        node_decls.append(f"\t{ret} {cxxmeth}() const;\n")
        out.append(f"inline {ret} Node::{cxxmeth}() const {{\n\tswitch (kind) {{\n")
        for sname, (r, f) in sorted(per_struct.items()):
            if sname not in node_structs:
                continue
            out.append(kinds_case(sname))
            out.append(f"\t\t\treturn static_cast<const {sname}*>(this)->{sanitize(f)};\n")
        out.append("\t\tdefault:\n\t\t\treturn {};\n\t}\n}\n\n")

    # ---- embedded-base membership + field presence per struct ----
    enum_names = set(load_kinds()[0])
    enum_names_sorted = sorted(enum_names, key=len, reverse=True)

    def base_closure(sname):
        seen = set()
        def go(n):
            for _f, bt, emb in structs.get(n, []):
                if emb:
                    b = bt.lstrip("*")
                    if b in structs and b not in seen:
                        seen.add(b)
                        go(b)
        go(sname)
        return seen

    def has_field(sname, *names):
        fs = {f for f, _t, _e in flat[sname]}
        return all(n in fs for n in names)

    # ---- Data-accessor views over flattened base fields ----
    out.append(
        "// Views over flattened embedded-base fields (generated). Callers get\n"
        "// pointers to the real fields so reads and writes behave like Go's\n"
        "// embedded-base accessors.\n\n"
        "struct DeclarationDataRef { Symbol** symbol; };\n"
        "struct ExportableDataRef { Symbol** localSymbol; };\n"
        "struct LocalsContainerDataRef { SymbolTable* locals; Node** nextContainer; };\n"
        "struct FlowNodeDataRef { FlowNode** flowNode; };\n"
        "struct FunctionLikeDataRef { SymbolTable* locals; Node** nextContainer; "
        "NodeList** typeParameters; NodeList** parameters; Node** type; "
        "Node** fullSignature; };\n"
        "struct BodyDataRef { Node** asteriskToken; Node** body; FlowNode** endFlowNode; };\n"
        "struct ClassLikeDataRef { Symbol** localSymbol; ModifierList** modifiers; "
        "SymbolTable* locals; Node** nextContainer; Node** name; "
        "NodeList** typeParameters; NodeList** heritageClauses; NodeList** members; };\n"
        "struct LiteralLikeDataRef { std::string* text; TokenFlags* tokenFlags; };\n"
        "struct TemplateLiteralLikeDataRef { std::string* text; TokenFlags* tokenFlags; "
        "std::string* rawText; TokenFlags* templateFlags; };\n\n")

    def data_dispatch(meth, ref, detect, fields):
        out.append(f"inline {ref} Node::{meth}() {{\n\tswitch (kind) {{\n")
        seen_kinds = set()
        for sname in sorted(node_structs):
            if detect(sname):
                expr = ", ".join(f"&n->{f}" if has_field(sname, f)
                                 else "nullptr" for f in fields)
                out.append(kinds_case(sname, seen_kinds))
                out.append(f"\t\t\t{{ auto* n = static_cast<{sname}*>(this); "
                           f"return {{ {expr} }}; }}\n")
        out.append("\t\tdefault:\n\t\t\treturn {};\n\t}\n}\n\n")
        node_decls.append(f"\t{ref} {meth}();\n")

    data_dispatch("declarationData", "DeclarationDataRef",
                  lambda s: has_field(s, "Symbol"), ["Symbol"])
    data_dispatch("exportableData", "ExportableDataRef",
                  lambda s: has_field(s, "LocalSymbol"), ["LocalSymbol"])
    data_dispatch("localsContainerData", "LocalsContainerDataRef",
                  lambda s: has_field(s, "Locals", "NextContainer"),
                  ["Locals", "NextContainer"])
    data_dispatch("flowNodeData", "FlowNodeDataRef",
                  lambda s: has_field(s, "FlowNode"), ["FlowNode"])
    data_dispatch("functionLikeData", "FunctionLikeDataRef",
                  lambda s: has_field(s, "TypeParameters", "Parameters",
                                      "Type", "FullSignature"),
                  ["Locals", "NextContainer", "TypeParameters",
                   "Parameters", "Type", "FullSignature"])
    data_dispatch("bodyData", "BodyDataRef",
                  lambda s: has_field(s, "AsteriskToken", "Body", "EndFlowNode"),
                  ["AsteriskToken", "Body", "EndFlowNode"])
    data_dispatch("classLikeData", "ClassLikeDataRef",
                  lambda s: has_field(s, "HeritageClauses", "Members"),
                  ["LocalSymbol", "modifiers", "Locals", "NextContainer",
                   "name", "TypeParameters", "HeritageClauses", "Members"])
    data_dispatch("literalLikeData", "LiteralLikeDataRef",
                  lambda s: has_field(s, "Text", "TokenFlags"),
                  ["Text", "TokenFlags"])
    data_dispatch("templateLiteralLikeData", "TemplateLiteralLikeDataRef",
                  lambda s: has_field(s, "RawText", "TemplateFlags"),
                  ["Text", "TokenFlags", "RawText", "TemplateFlags"])

    # modifiers()/setModifiers() — kinds with a `modifiers` field
    out.append("inline ModifierList* Node::modifiers() const {\n\tswitch (kind) {\n")
    seen_kinds = set()
    for sname in sorted(node_structs):
        if has_field(sname, "modifiers"):
            out.append(kinds_case(sname, seen_kinds))
            out.append(f"\t\t\treturn static_cast<const {sname}*>(this)->modifiers;\n")
    out.append("\t\tdefault:\n\t\t\treturn nullptr;\n\t}\n}\n\n")
    node_decls.append("\tModifierList* modifiers() const;\n")
    node_decls.append("\tvoid setModifiers(ModifierList* m);\n")
    out.append("inline void Node::setModifiers(ModifierList* m) {\n\tswitch (kind) {\n")
    seen_kinds = set()
    for sname in sorted(node_structs):
        if has_field(sname, "modifiers"):
            out.append(kinds_case(sname, seen_kinds))
            out.append(f"\t\t\tstatic_cast<{sname}*>(this)->modifiers = m; return;\n")
    out.append("\t\tdefault:\n\t\t\treturn;\n\t}\n}\n\n")

    # ---- subtree facts ----
    prop_masks = {
        "CatchClause": ("SubtreeExclusionsCatchClause", None),
        "VariableDeclarationList": ("SubtreeExclusionsVariableDeclarationList", None),
        "BindingPattern": ("SubtreeExclusionsBindingPattern", None),
        "ParameterDeclaration": ("SubtreeExclusionsParameter", None),
        "FunctionDeclaration": ("SubtreeExclusionsFunction", None),
        "ClassDeclaration": ("SubtreeExclusionsClass", None),
        "ClassExpression": ("SubtreeExclusionsClass", None),
        "ModuleDeclaration": ("SubtreeExclusionsModule", None),
        "ConstructorDeclaration": ("SubtreeExclusionsConstructor", None),
        "GetAccessorDeclaration": ("SubtreeExclusionsAccessor", "name"),
        "SetAccessorDeclaration": ("SubtreeExclusionsAccessor", "name"),
        "MethodDeclaration": ("SubtreeExclusionsMethod", "name"),
        "PropertyDeclaration": ("SubtreeExclusionsProperty", "name"),
        "ArrowFunction": ("SubtreeExclusionsArrowFunction", None),
        "FunctionExpression": ("SubtreeExclusionsFunction", None),
        "AsExpression": ("SubtreeExclusionsOuterExpression", None),
        "SatisfiesExpression": ("SubtreeExclusionsOuterExpression", None),
        "TypeAssertion": ("SubtreeExclusionsOuterExpression", None),
        "PropertyAccessExpression": ("SubtreeExclusionsPropertyAccess", None),
        "ElementAccessExpression": ("SubtreeExclusionsElementAccess", None),
        "CallExpression": ("SubtreeExclusionsCall", None),
        "NewExpression": ("SubtreeExclusionsNew", None),
        "ArrayLiteralExpression": ("SubtreeExclusionsArrayLiteral", None),
        "ObjectLiteralExpression": ("SubtreeExclusionsObjectLiteral", None),
    }

    out.append("// subtree facts (generated).\n\n")
    out.append("inline SubtreeFacts Node::propagateSubtreeFacts() const {\n\tswitch (kind) {\n")
    seen_kinds = set()
    for sname in sorted(node_structs):
        if "TypeSyntaxBase" in base_closure(sname):
            out.append(kinds_case(sname, seen_kinds))
            out.append("\t\t\treturn SubtreeContainsTypeScript;\n")
            continue
        if sname in prop_masks:
            mask, extra = prop_masks[sname]
            out.append(kinds_case(sname, seen_kinds))
            r = f"\t\t\t{{ auto* n = static_cast<const {sname}*>(this); " \
                f"return subtreeFacts() & ~{mask}"
            if extra:
                r += f" | ::tsc::propagateSubtreeFacts(n->{extra})"
            r += "; }\n"
            out.append(r)
    out.append("\t\tdefault:\n\t\t\treturn subtreeFacts() & ~SubtreeExclusionsNode;\n\t}\n}\n\n")
    node_decls.append("\tSubtreeFacts propagateSubtreeFacts() const;\n")

    # pointer-producing member names for `a.b` -> `a->b` hop conversion
    ptr_members = set()
    for s in node_structs:
        for fn_, gt_, _ in flat.get(s, []):
            if go_type_to_cpp(gt_, node_structs, aliases).endswith("*"):
                ptr_members.add(sanitize(fn_))
    PTR_ACCS = {"name", "expression", "type", "body", "initializer", "tagName",
                "questionToken", "postfixToken", "questionDotToken", "propertyName",
                "propertyNameOrName", "label", "attributes", "moduleSpecifier",
                "importClause", "statement", "typeExpression", "className",
                "argumentList", "typeArgumentList", "typeParameterList", "memberList",
                "statementList", "elementList", "propertyList", "commentList",
                "parameterList", "modifiers", "symbol", "localSymbol", "locals",
                "nextContainer", "parent"}
    # capitalized Go accessor/cast calls -> lowercase C++ equivalents
    METHOD_RENAMES = {
        "Text": "text", "RawText": "rawText", "Name": "name", "Expression": "expression",
        "Type": "type", "Body": "body", "Initializer": "initializer", "TagName": "tagName",
        "QuestionToken": "questionToken", "PostfixToken": "postfixToken",
        "QuestionDotToken": "questionDotToken", "PropertyName": "propertyName",
        "Label": "label", "Attributes": "attributes", "ModuleSpecifier": "moduleSpecifier",
        "ImportClause": "importClause", "Statement": "statement",
        "TypeExpression": "typeExpression", "ClassName": "className",
        "ArgumentList": "argumentList", "TypeArgumentList": "typeArgumentList",
        "TypeParameterList": "typeParameterList", "MemberList": "memberList",
        "StatementList": "statementList", "ElementList": "elementList",
        "PropertyList": "propertyList", "CommentList": "commentList",
        "ParameterList": "parameterList", "Arguments": "arguments",
        "TypeArguments": "typeArguments", "TypeParameters": "typeParameters",
        "Members": "members", "Statements": "statements", "Elements": "elements",
        "Properties": "properties", "Comments": "comments", "Parameters": "parameters",
        "Children": "children", "CanHaveStatements": "canHaveStatements",
        "IsTypeOnly": "isTypeOnly", "ModifierFlags": "modifierFlags",
        "Modifiers": "modifiers", "SubtreeFacts": "subtreeFacts",
        "Locals": "locals", "Symbol": "symbol", "LocalSymbol": "localSymbol",
        "NextContainer": "nextContainer", "Contains": "contains",
        "ForEachChild": "forEachChild", "End": "end", "Pos": "pos", "Len": "len",
        "AsNode": "asNode", "PosEnd": "posEnd",
    }
    METH_PAT = "|".join(sorted(METHOD_RENAMES, key=len, reverse=True))

    # computeSubtreeFacts bodies translated from Go
    def facts_expr(e):
        e = e.strip()
        e = e.replace("!= nil", "!= nullptr").replace("== nil", "== nullptr")
        e = e.replace("node.ModifierFlags()", "n->modifierFlags()")
        e = e.replace("node.modifiers.ModifierFlags", "(n->modifiers ? n->modifiers->ModifierFlags : ModifierFlags{})")
        e = e.replace("node.", "n->")
        e = re.sub(r"\bnode\b", "n", e)
        e = re.sub(r"core\.IfElse\(", "ifElse(", e)
        # `.x` -> `->x` where the receiver produces a pointer (iterate to fixpoint)
        def _hops(s):
            def hop(m):
                recv, mem = m.group(1), m.group(2)
                base = recv
                if recv.endswith(")"):
                    b = re.match(r"(\w+)\(", recv)
                    base = b.group(1) if b else recv
                if recv.startswith("as<") or base in ptr_members or base in PTR_ACCS:
                    return recv + "->" + mem
                return m.group(0)
            return re.sub(r"(as<\w+>\(\)|\w+(?:\(\))?)\.(\w+)", hop, s)
        prev = None
        while prev != e:
            prev = e
            e = _hops(e)
        # casts and capitalized accessor calls on pointers
        e = re.sub(r"->As(\w+)\(\)", r"->as<\1>()", e)
        e = re.sub(r"->(" + METH_PAT + r")\(",
                   lambda m: "->" + METHOD_RENAMES[m.group(1)] + "(", e)
        # value-member calls on TextRange / NodeList values
        e = re.sub(r"\.(End|Pos|Len|Contains|ContainsInclusive|Overlaps|Intersects)\(",
                   lambda m: "." + m.group(1)[0].lower() + m.group(1)[1:] + "(", e)
        # core field names stay lowercase in C++
        e = e.replace("->Kind", "->kind").replace("->Flags", "->flags")
        e = e.replace("->Parent", "->parent").replace("->Loc", "->loc")
        e = e.replace("->Nodes", "->nodes").replace("->Id", "->id")
        e = re.sub(r"\bIs(\w+)\(", r"is\1(", e)
        e = re.sub(r"\bContainsObjectRestOrSpread\(", "containsObjectRestOrSpread(", e)
        e = re.sub(r"\b(propagateSubtreeFacts|propagateEraseableSyntax|"
                   r"propagateEraseableSyntaxFacts|"
                   r"propagateEraseableSyntaxListSubtreeFacts|"
                   r"propagateNodeListSubtreeFacts|"
                   r"propagateModifierListSubtreeFacts|"
                   r"propagateObjectBindingElementSubtreeFacts|"
                   r"propagateBindingElementSubtreeFacts|"
                   r"containsObjectRestOrSpread)\(",
                   r"::tsc::\1(", e)
        e = e.replace("&^=", "&= ~")
        e = re.sub(r"&\s*\^\s*(\w+)", r"& ~\1", e)
        for k in enum_names_sorted:
            e = re.sub(r"\b" + re.escape(k) + r"\b", "Kind::" + k[4:], e)
        return e

    def facts_body(sname, body):
        # join multi-line expressions: a line ending with a binary operator or
        # containing unbalanced parens continues on the next line.
        logical = []
        buf = ""
        for raw in body.split("\n"):
            l = raw.strip()
            if not l:
                continue
            buf = (buf + " " + l) if buf else l
            if re.search(r"[|&?,(]$", l) or l.endswith("||") or l.endswith("&&"):
                continue
            if buf.count("(") != buf.count(")"):
                continue
            logical.append(buf)
            buf = ""
        if buf:
            logical.append(buf)

        lines_out = []
        for ln in logical:
            if ln == "}" or ln == "} else {" or ln == "else {":
                lines_out.append(ln.replace("else", "else"))
                continue
            if ln.startswith("switch "):
                m2 = re.match(r"switch (.*) \{$", ln)
                lines_out.append("switch (" + facts_expr(m2.group(1)) + ") {")
                continue
            if ln.startswith("case ") and ln.endswith(":"):
                rest = ln[5:-1]
                labels = [facts_expr(x.strip()) for x in rest.split(",")]
                lines_out.append(" ".join(f"case {x}:" for x in labels))
                continue
            if ln.startswith("default"):
                lines_out.append(facts_expr(ln))
                continue
            if ln.startswith("for ") and ln.endswith("{"):
                m2 = re.match(r"for (?:_, )?(\w+) := range (.*) \{$", ln)
                if m2:
                    lines_out.append(f"for (auto* {m2.group(1)} : {facts_expr(m2.group(2))}) {{")
                    continue
                m2 = re.match(r"for (\w+), (\w+) := range (.*) \{$", ln)
                if m2:
                    lines_out.append(
                        f"for (auto _r : {facts_expr(m2.group(3))}) {{ "
                        f"auto {m2.group(1)} = _r.first; auto {m2.group(2)} = _r.second;")
                    continue
                lines_out.append("// TODO for: " + ln)
                continue
            if ln.startswith("if ") and ln.endswith("{"):
                lines_out.append("if (" + facts_expr(ln[3:-1].strip()) + ") {")
                continue
            if ln.startswith("return "):
                lines_out.append("return " + facts_expr(ln[7:]) + ";")
                continue
            if ln == "return":
                lines_out.append("return SubtreeFactsNone;")
                continue
            m2 = re.match(r"(\w+) :?= (.*)$", ln)
            if m2:
                lines_out.append(f"auto {m2.group(1)} = {facts_expr(m2.group(2))};")
                continue
            m2 = re.match(r"(\w+) (&\^=|\|=|\^=|&=|=|\+=|-=) (.*)$", ln)
            if m2:
                op = m2.group(2)
                op = "&= ~" if op == "&^=" else op
                lines_out.append(f"{m2.group(1)} {op} {facts_expr(m2.group(3))};")
                continue
            if ln.startswith("panic("):
                lines_out.append("TSC_UNREACHABLE(" + ln[6:-1] + ");")
                continue
            lines_out.append(facts_expr(ln) + ";")
        return lines_out

    # ---- Is* predicates (emitted before computeSubtreeFacts which calls them) ----
    def map_kind(k):
        return f"Kind::{k[4:]}" if k in enum_names else k

    out.append("// is* predicates (generated).\n\n")
    for name, body in predicates:
        cxx = name[0].lower() + name[1:]
        # emit a kind-union only when the body is a pure kind-check
        ids = set(re.findall(r"\b([A-Za-z_]\w*)\b", body)) - {
            "node", "Kind", "return", "case", "switch", "default", "if",
            "else", "true", "false", "nil", "fallthrough"}
        nonkind = [i for i in ids if not i.startswith("Kind")]
        if nonkind:
            out.append(f"inline bool {cxx}(const Node*) {{ return false; /* TODO: {name} */ }}\n")
            continue
        ks = re.findall(r"Kind\w+", body)
        cond = " || ".join(f"n->kind == {map_kind(k)}"
                            for k in dict.fromkeys(ks))
        out.append(f"inline bool {cxx}(const Node* n) {{ return {cond}; }}\n")
    out.append("\n")

    compute = {}
    for m in re.finditer(
            r"func \(node \*(\w+)\) computeSubtreeFacts\(\) SubtreeFacts \{\n(.*?)\n\}",
            src_all, re.S):
        compute[m.group(1)] = m.group(2)

    for sname in sorted(compute):
        if sname not in node_structs:
            continue
        out.append(f"inline SubtreeFacts computeSubtreeFacts_{sname}(const {sname}* n) {{\n")
        for ln in facts_body(sname, compute[sname]):
            out.append("\t" + ln + "\n")
        out.append("}\n\n")

    out.append("inline SubtreeFacts Node::computeSubtreeFacts() const {\n\tswitch (kind) {\n")
    seen_kinds = set()
    for sname in sorted(compute):
        if sname not in node_structs:
            continue
        out.append(kinds_case(sname, seen_kinds))
        out.append(f"\t\t\treturn computeSubtreeFacts_{sname}(static_cast<const {sname}*>(this));\n")
    out.append("\t\tdefault:\n\t\t\treturn SubtreeFactsNone;\n\t}\n}\n\n")
    node_decls.append("\tSubtreeFacts computeSubtreeFacts() const;\n")

    out.append(
        "inline SubtreeFacts Node::subtreeFacts() const {\n\tswitch (kind) {\n")
    seen_kinds = set()
    for sname in sorted(node_structs):
        if has_field(sname, "facts"):
            out.append(kinds_case(sname, seen_kinds))
            out.append(f"\t\t\t{{ auto* n = static_cast<const {sname}*>(this);\n"
                       "\t\t\t\tuint32_t f = n->facts.load(std::memory_order_acquire);\n"
                       "\t\t\t\tif (!(f & SubtreeFactsComputed)) {\n"
                       "\t\t\t\t\tf = computeSubtreeFacts() | SubtreeFactsComputed;\n"
                       "\t\t\t\t\tn->facts.store(f, std::memory_order_release);\n"
                       "\t\t\t\t}\n"
                       "\t\t\t\treturn f & ~SubtreeFactsComputed; }\n")
    out.append("\t\tdefault:\n\t\t\treturn computeSubtreeFacts();\n\t}\n}\n\n")
    node_decls.append("\tSubtreeFacts subtreeFacts() const;\n")

    out.append("\n}  // namespace tsc\n")
    def fix_flag_cmp(t):
        # Go `a & b != 0` parses as `(a & b) != 0`; C++ binds `!=` first.
        # Rewrite `ATOM [&|^] ATOM [...] ==/!= RHS` into a parenthesized group.
        atom = (r"(?:\([^()]*(?:\([^()]*\)[^()]*)*\)"
                r"|\{[^}]*\}"
                r"|[\w:>\-~]+(?:\(\))?)")
        pat = re.compile(
            r"(?<![\w>)\]:.])"
            r"((?:" + atom + r"\s*[&|^]\s*)+" + atom + r")"
            r"\s*(!=|==)\s*(\w+)")
        def repl(m):
            return "(" + m.group(1).strip() + ") " + m.group(2) + " " + m.group(3)
        prev = None
        while prev != t:
            prev = t
            t = pat.sub(repl, t)
        return t

    out_path = os.path.join(OUT, "ast", "nodes_generated.h")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    open(out_path, "w").write(fix_flag_cmp("".join(out)))
    open(os.path.join(OUT, "ast", "nodes_factory_decl.inc"), "w").write("".join(decls))
    open(os.path.join(OUT, "ast", "nodes_node_decl.inc"), "w").write("".join(node_decls))
    print(f"wrote {out_path} (+ node/factory decl includes)")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "all"
    if cmd in ("kinds", "all"):
        gen_kinds()
    if cmd in ("diagnostics", "all"):
        gen_diagnostics()
    if cmd in ("unicode", "all"):
        gen_unicode()
    if cmd in ("nodes", "all"):
        gen_nodes()
