#!/usr/bin/env python3
"""genloc.py — generates cpp/internal/diagnostics/loc_generated.h.

Mirrors tsc/internal/diagnostics/loc/*.generated.json: embeds each locale's
message table into a per-locale function returning a
std::unordered_map<Key, std::string>, the equivalent of Go's embedded
localized message maps. Values are escaped byte-wise so UTF-8 round-trips
exactly as stored in the JSON files.
"""
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LOC = os.path.join(REPO, "tsc", "internal", "diagnostics", "loc")
OUT = os.path.join(REPO, "cpp", "internal", "diagnostics", "loc_generated.h")


def c_escape(data: str) -> str:
    out = []
    for b in data.encode("utf-8"):
        if b == 0x5C:
            out.append("\\\\")
        elif b == 0x22:
            out.append('\\"')
        elif b == 0x0A:
            out.append("\\n")
        elif b == 0x0D:
            out.append("\\r")
        elif b == 0x09:
            out.append("\\t")
        elif 32 <= b < 127:
            out.append(chr(b))
        else:
            out.append(f"\\{b:03o}")
    return "".join(out)


# Emission order mirrors tsc/internal/diagnostics/loc/loc_generated.go.
LOCALE_ORDER = [
    "zh-CN", "zh-TW", "cs-CZ", "de-DE", "es-ES", "fr-FR", "it-IT",
    "ja-JP", "ko-KR", "pl-PL", "pt-BR", "ru-RU", "tr-TR",
]


def main() -> int:
    names = [f"{loc}.generated.json" for loc in LOCALE_ORDER]
    with open(OUT, "w") as f:
        f.write("// Code generated by tools/genloc.py; DO NOT EDIT.\n")
        f.write("// Mirrors tsc/internal/diagnostics/loc/*.generated.json.\n")
        f.write("#pragma once\n\n")
        f.write("namespace tsc::localized_messages {\n\n")
        for name in names:
            locale = name[: -len(".generated.json")].replace("-", "_")
            with open(os.path.join(LOC, name), encoding="utf-8") as j:
                table = json.load(j)
            f.write("inline const std::unordered_map<Key, std::string>& "
                    f"{locale}() {{\n")
            f.write("static const std::unordered_map<Key, std::string> t_{\n")
            for key in sorted(table):
                f.write(f'    {{"{key}", "{c_escape(table[key])}"}},\n')
            f.write("}; return t_; }\n\n")
        f.write("} // namespace tsc::localized_messages\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
