// Port of tsc/internal/ast/deepclone_test.go.
#include <string>
#include <vector>

#include "internal/ast/ast.h"
#include "internal/ast/visitor.h"
#include "internal/gostd/testing.h"
#include "internal/testutil/parsetestutil/parsetestutil.h"
#include "internal/testutil/testutil.h"
#include "internal/testutil/unittests/registry.h"

using tsc::gostd::testing::T;
using namespace tsc;

struct NodeComparisonWorkItem {
	Node* original;
	Node* copy;
};

static std::vector<Node*> getChildren(Node* node) {
	std::vector<Node*> children;
	auto* v = newNodeVisitor(
		[&children](Node* child) -> Node* {
			children.push_back(child);
			return child;
		},
		nullptr, NodeVisitorHooks{});
	node->visitEachChild(*v);
	delete v;
	return children;
}

static void TestDeepCloneNodeSanityCheck(T* t) {
	t->Parallel();
	struct Rec {
		const char* title;
		const char* input;
	};
	static const Rec data[] = {
		{"StringLiteral#1", R"TS(;"test")TS"},
		{"StringLiteral#2", R"TS(;'test')TS"},
		{"NumericLiteral", R"TS(0)TS"},
		{"BigIntLiteral", R"TS(0n)TS"},
		{"BooleanLiteral#1", R"TS(true)TS"},
		{"BooleanLiteral#2", R"TS(false)TS"},
		{"NoSubstitutionTemplateLiteral", "``"},
		{"RegularExpressionLiteral#1", R"TS(/a/)TS"},
		{"RegularExpressionLiteral#2", R"TS(/a/g)TS"},
		{"NullLiteral", R"TS(null)TS"},
		{"ThisExpression", R"TS(this)TS"},
		{"SuperExpression", R"TS(super())TS"},
		{"ImportExpression", R"TS(import())TS"},
		{"PropertyAccess#1", R"TS(a.b)TS"},
		{"PropertyAccess#2", R"TS(a.#b)TS"},
		{"PropertyAccess#3", R"TS(a?.b)TS"},
		{"PropertyAccess#4", R"TS(a?.b.c)TS"},
		{"PropertyAccess#5", R"TS(1..b)TS"},
		{"PropertyAccess#6", R"TS(1.0.b)TS"},
		{"PropertyAccess#7", R"TS(0x1.b)TS"},
		{"PropertyAccess#8", R"TS(0b1.b)TS"},
		{"PropertyAccess#9", R"TS(0o1.b)TS"},
		{"PropertyAccess#10", R"TS(10e1.b)TS"},
		{"PropertyAccess#11", R"TS(10E1.b)TS"},
		{"ElementAccess#1", R"TS(a[b])TS"},
		{"ElementAccess#2", R"TS(a?.[b])TS"},
		{"ElementAccess#3", R"TS(a?.[b].c)TS"},
		{"CallExpression#1", R"TS(a())TS"},
		{"CallExpression#2", R"TS(a<T>())TS"},
		{"CallExpression#3", R"TS(a(b))TS"},
		{"CallExpression#4", R"TS(a<T>(b))TS"},
		{"CallExpression#5", R"TS(a(b).c)TS"},
		{"CallExpression#6", R"TS(a<T>(b).c)TS"},
		{"CallExpression#7", R"TS(a?.(b))TS"},
		{"CallExpression#8", R"TS(a?.<T>(b))TS"},
		{"CallExpression#9", R"TS(a?.(b).c)TS"},
		{"CallExpression#10", R"TS(a?.<T>(b).c)TS"},
		{"CallExpression#11", R"TS(a<T, U>())TS"},
		{"CallExpression#12", R"TS(a<T,>())TS"},
		{"NewExpression#1", R"TS(new a)TS"},
		{"NewExpression#2", R"TS(new a.b)TS"},
		{"NewExpression#3", R"TS(new a())TS"},
		{"NewExpression#4", R"TS(new a.b())TS"},
		{"NewExpression#5", R"TS(new a<T>())TS"},
		{"NewExpression#6", R"TS(new a.b<T>())TS"},
		{"NewExpression#7", R"TS(new a(b))TS"},
		{"NewExpression#8", R"TS(new a.b(c))TS"},
		{"NewExpression#9", R"TS(new a<T>(b))TS"},
		{"NewExpression#10", R"TS(new a.b<T>(c))TS"},
		{"NewExpression#11", R"TS(new a(b).c)TS"},
		{"NewExpression#12", R"TS(new a<T>(b).c)TS"},
		{"TaggedTemplateExpression#1", "tag``"},
		{"TaggedTemplateExpression#2", "tag<T>``"},
		{"TypeAssertionExpression#1", R"TS(<T>a)TS"},
		{"FunctionExpression#1", R"TS((function(){}))TS"},
		{"FunctionExpression#2", R"TS((function f(){}))TS"},
		{"FunctionExpression#3", R"TS((function*f(){}))TS"},
		{"FunctionExpression#4", R"TS((async function f(){}))TS"},
		{"FunctionExpression#5", R"TS((async function*f(){}))TS"},
		{"FunctionExpression#6", R"TS((function<T>(){}))TS"},
		{"FunctionExpression#7", R"TS((function(a){}))TS"},
		{"FunctionExpression#8", R"TS((function():T{}))TS"},
		{"ArrowFunction#1", R"TS(a=>{})TS"},
		{"ArrowFunction#2", R"TS(()=>{})TS"},
		{"ArrowFunction#3", R"TS((a)=>{})TS"},
		{"ArrowFunction#4", R"TS(<T>(a)=>{})TS"},
		{"ArrowFunction#5", R"TS(async a=>{})TS"},
		{"ArrowFunction#6", R"TS(async()=>{})TS"},
		{"ArrowFunction#7", R"TS(async<T>()=>{})TS"},
		{"ArrowFunction#8", R"TS(():T=>{})TS"},
		{"ArrowFunction#9", R"TS(()=>a)TS"},
		{"DeleteExpression", R"TS(delete a)TS"},
		{"TypeOfExpression", R"TS(typeof a)TS"},
		{"VoidExpression", R"TS(void a)TS"},
		{"AwaitExpression", R"TS(await a)TS"},
		{"PrefixUnaryExpression#1", R"TS(+a)TS"},
		{"PrefixUnaryExpression#2", R"TS(++a)TS"},
		{"PrefixUnaryExpression#3", R"TS(+ +a)TS"},
		{"PrefixUnaryExpression#4", R"TS(+ ++a)TS"},
		{"PrefixUnaryExpression#5", R"TS(-a)TS"},
		{"PrefixUnaryExpression#6", R"TS(--a)TS"},
		{"PrefixUnaryExpression#7", R"TS(- -a)TS"},
		{"PrefixUnaryExpression#8", R"TS(- --a)TS"},
		{"PrefixUnaryExpression#9", R"TS(+-a)TS"},
		{"PrefixUnaryExpression#10", R"TS(+--a)TS"},
		{"PrefixUnaryExpression#11", R"TS(-+a)TS"},
		{"PrefixUnaryExpression#12", R"TS(-++a)TS"},
		{"PrefixUnaryExpression#13", R"TS(~a)TS"},
		{"PrefixUnaryExpression#14", R"TS(!a)TS"},
		{"PostfixUnaryExpression#1", R"TS(a++)TS"},
		{"PostfixUnaryExpression#2", R"TS(a--)TS"},
		{"BinaryExpression#1", R"TS(a,b)TS"},
		{"BinaryExpression#2", R"TS(a+b)TS"},
		{"BinaryExpression#3", R"TS(a**b)TS"},
		{"BinaryExpression#4", R"TS(a instanceof b)TS"},
		{"BinaryExpression#5", R"TS(a in b)TS"},
		{"ConditionalExpression", R"TS(a?b:c)TS"},
		{"TemplateExpression#1", "`a${b}c`"},
		{"TemplateExpression#2", "`a${b}c${d}e`"},
		{"YieldExpression#1", R"TS((function*() { yield }))TS"},
		{"YieldExpression#2", R"TS((function*() { yield a }))TS"},
		{"YieldExpression#3", R"TS((function*() { yield*a }))TS"},
		{"SpreadElement", R"TS([...a])TS"},
		{"ClassExpression#1", R"TS((class {}))TS"},
		{"ClassExpression#2", R"TS((class a {}))TS"},
		{"ClassExpression#3", R"TS((class<T>{}))TS"},
		{"ClassExpression#4", R"TS((class a<T>{}))TS"},
		{"ClassExpression#5", R"TS((class extends b {}))TS"},
		{"ClassExpression#6", R"TS((class a extends b {}))TS"},
		{"ClassExpression#7", R"TS((class implements b {}))TS"},
		{"ClassExpression#8", R"TS((class a implements b {}))TS"},
		{"ClassExpression#9", R"TS((class implements b, c {}))TS"},
		{"ClassExpression#10", R"TS((class a implements b, c {}))TS"},
		{"ClassExpression#11", R"TS((class extends b implements c, d {}))TS"},
		{"ClassExpression#12", R"TS((class a extends b implements c, d {}))TS"},
		{"ClassExpression#13", R"TS((@a class {}))TS"},
		{"OmittedExpression", R"TS([,])TS"},
		{"ExpressionWithTypeArguments", R"TS(a<T>)TS"},
		{"AsExpression", R"TS(a as T)TS"},
		{"SatisfiesExpression", R"TS(a satisfies T)TS"},
		{"NonNullExpression", R"TS(a!)TS"},
		{"MetaProperty#1", R"TS(new.target)TS"},
		{"MetaProperty#2", R"TS(import.meta)TS"},
		{"ArrayLiteralExpression#1", R"TS([])TS"},
		{"ArrayLiteralExpression#2", R"TS([a])TS"},
		{"ArrayLiteralExpression#3", R"TS([a,])TS"},
		{"ArrayLiteralExpression#4", R"TS([,a])TS"},
		{"ArrayLiteralExpression#5", R"TS([...a])TS"},
		{"ObjectLiteralExpression#1", R"TS(({}))TS"},
		{"ObjectLiteralExpression#2", R"TS(({a,}))TS"},
		{"ShorthandPropertyAssignment", R"TS(({a}))TS"},
		{"PropertyAssignment", R"TS(({a:b}))TS"},
		{"SpreadAssignment", R"TS(({...a}))TS"},
		{"Block", R"TS({})TS"},
		{"VariableStatement#1", R"TS(var a)TS"},
		{"VariableStatement#2", R"TS(let a)TS"},
		{"VariableStatement#3", R"TS(const a = b)TS"},
		{"VariableStatement#4", R"TS(using a = b)TS"},
		{"VariableStatement#5", R"TS(await using a = b)TS"},
		{"EmptyStatement", R"TS(;)TS"},
		{"IfStatement#1", R"TS(if(a);)TS"},
		{"IfStatement#2", R"TS(if(a);else;)TS"},
		{"IfStatement#3", R"TS(if(a);else{})TS"},
		{"IfStatement#4", R"TS(if(a);else if(b);)TS"},
		{"IfStatement#5", R"TS(if(a);else if(b) {})TS"},
		{"IfStatement#6", R"TS(if(a) {})TS"},
		{"IfStatement#7", R"TS(if(a) {} else;)TS"},
		{"IfStatement#8", R"TS(if(a) {} else {})TS"},
		{"IfStatement#9", R"TS(if(a) {} else if(b);)TS"},
		{"IfStatement#10", R"TS(if(a) {} else if(b){})TS"},
		{"DoStatement#1", R"TS(do;while(a);)TS"},
		{"DoStatement#2", R"TS(do {} while(a);)TS"},
		{"WhileStatement#1", R"TS(while(a);)TS"},
		{"WhileStatement#2", R"TS(while(a) {})TS"},
		{"ForStatement#1", R"TS(for(;;);)TS"},
		{"ForStatement#2", R"TS(for(a;;);)TS"},
		{"ForStatement#3", R"TS(for(var a;;);)TS"},
		{"ForStatement#4", R"TS(for(;a;);)TS"},
		{"ForStatement#5", R"TS(for(;;a);)TS"},
		{"ForStatement#6", R"TS(for(;;){})TS"},
		{"ForInStatement#1", R"TS(for(a in b);)TS"},
		{"ForInStatement#2", R"TS(for(var a in b);)TS"},
		{"ForInStatement#3", R"TS(for(a in b){})TS"},
		{"ForOfStatement#1", R"TS(for(a of b);)TS"},
		{"ForOfStatement#2", R"TS(for(var a of b);)TS"},
		{"ForOfStatement#3", R"TS(for(a of b){})TS"},
		{"ForOfStatement#4", R"TS(for await(a of b);)TS"},
		{"ForOfStatement#5", R"TS(for await(var a of b);)TS"},
		{"ForOfStatement#6", R"TS(for await(a of b){})TS"},
		{"ContinueStatement#1", R"TS(continue)TS"},
		{"ContinueStatement#2", R"TS(continue a)TS"},
		{"BreakStatement#1", R"TS(break)TS"},
		{"BreakStatement#2", R"TS(break a)TS"},
		{"ReturnStatement#1", R"TS(return)TS"},
		{"ReturnStatement#2", R"TS(return a)TS"},
		{"WithStatement#1", R"TS(with(a);)TS"},
		{"WithStatement#2", R"TS(with(a){})TS"},
		{"SwitchStatement", R"TS(switch (a) {})TS"},
		{"CaseClause#1", R"TS(switch (a) {case b:})TS"},
		{"CaseClause#2", R"TS(switch (a) {case b:;})TS"},
		{"DefaultClause#1", R"TS(switch (a) {default:})TS"},
		{"DefaultClause#2", R"TS(switch (a) {default:;})TS"},
		{"LabeledStatement", R"TS(a:;)TS"},
		{"ThrowStatement", R"TS(throw a)TS"},
		{"TryStatement#1", R"TS(try {} catch {})TS"},
		{"TryStatement#2", R"TS(try {} finally {})TS"},
		{"TryStatement#3", R"TS(try {} catch {} finally {})TS"},
		{"DebuggerStatement", R"TS(debugger)TS"},
		{"FunctionDeclaration#1", R"TS(export default function(){})TS"},
		{"FunctionDeclaration#2", R"TS(function f(){})TS"},
		{"FunctionDeclaration#3", R"TS(function*f(){})TS"},
		{"FunctionDeclaration#4", R"TS(async function f(){})TS"},
		{"FunctionDeclaration#5", R"TS(async function*f(){})TS"},
		{"FunctionDeclaration#6", R"TS(function f<T>(){})TS"},
		{"FunctionDeclaration#7", R"TS(function f(a){})TS"},
		{"FunctionDeclaration#8", R"TS(function f():T{})TS"},
		{"FunctionDeclaration#9", R"TS(function f();)TS"},
		{"ClassDeclaration#1", R"TS(class a {})TS"},
		{"ClassDeclaration#2", R"TS(class a<T>{})TS"},
		{"ClassDeclaration#3", R"TS(class a extends b {})TS"},
		{"ClassDeclaration#4", R"TS(class a implements b {})TS"},
		{"ClassDeclaration#5", R"TS(class a implements b, c {})TS"},
		{"ClassDeclaration#6", R"TS(class a extends b implements c, d {})TS"},
		{"ClassDeclaration#7", R"TS(export default class {})TS"},
		{"ClassDeclaration#8", R"TS(export default class<T>{})TS"},
		{"ClassDeclaration#9", R"TS(export default class extends b {})TS"},
		{"ClassDeclaration#10", R"TS(export default class implements b {})TS"},
		{"ClassDeclaration#11", R"TS(export default class implements b, c {})TS"},
		{"ClassDeclaration#12", R"TS(export default class extends b implements c, d {})TS"},
		{"ClassDeclaration#13", R"TS(@a class b {})TS"},
		{"ClassDeclaration#14", R"TS(@a export class b {})TS"},
		{"ClassDeclaration#15", R"TS(export @a class b {})TS"},
		{"InterfaceDeclaration#1", R"TS(interface a {})TS"},
		{"InterfaceDeclaration#2", R"TS(interface a<T>{})TS"},
		{"InterfaceDeclaration#3", R"TS(interface a extends b {})TS"},
		{"InterfaceDeclaration#4", R"TS(interface a extends b, c {})TS"},
		{"TypeAliasDeclaration#1", R"TS(type a = b)TS"},
		{"TypeAliasDeclaration#2", R"TS(type a<T> = b)TS"},
		{"EnumDeclaration#1", R"TS(enum a{})TS"},
		{"EnumDeclaration#2", R"TS(enum a{b})TS"},
		{"EnumDeclaration#3", R"TS(enum a{b=c})TS"},
		{"ModuleDeclaration#1", R"TS(module a{})TS"},
		{"ModuleDeclaration#2", R"TS(module a.b{})TS"},
		{"ModuleDeclaration#3", R"TS(module "a";)TS"},
		{"ModuleDeclaration#4", R"TS(module "a"{})TS"},
		{"ModuleDeclaration#5", R"TS(namespace a{})TS"},
		{"ModuleDeclaration#6", R"TS(namespace a.b{})TS"},
		{"ModuleDeclaration#7", R"TS(global;)TS"},
		{"ModuleDeclaration#8", R"TS(global{})TS"},
		{"ImportEqualsDeclaration#1", R"TS(import a = b)TS"},
		{"ImportEqualsDeclaration#2", R"TS(import a = b.c)TS"},
		{"ImportEqualsDeclaration#3", R"TS(import a = require("b"))TS"},
		{"ImportEqualsDeclaration#4", R"TS(export import a = b)TS"},
		{"ImportEqualsDeclaration#5", R"TS(export import a = require("b"))TS"},
		{"ImportEqualsDeclaration#6", R"TS(import type a = b)TS"},
		{"ImportEqualsDeclaration#7", R"TS(import type a = b.c)TS"},
		{"ImportEqualsDeclaration#8", R"TS(import type a = require("b"))TS"},
		{"ImportDeclaration#1", R"TS(import "a")TS"},
		{"ImportDeclaration#2", R"TS(import a from "b")TS"},
		{"ImportDeclaration#3", R"TS(import type a from "b")TS"},
		{"ImportDeclaration#4", R"TS(import * as a from "b")TS"},
		{"ImportDeclaration#5", R"TS(import type * as a from "b")TS"},
		{"ImportDeclaration#6", R"TS(import {} from "b")TS"},
		{"ImportDeclaration#7", R"TS(import type {} from "b")TS"},
		{"ImportDeclaration#8", R"TS(import { a } from "b")TS"},
		{"ImportDeclaration#9", R"TS(import type { a } from "b")TS"},
		{"ImportDeclaration#8", R"TS(import { a as b } from "c")TS"},
		{"ImportDeclaration#9", R"TS(import type { a as b } from "c")TS"},
		{"ImportDeclaration#10", R"TS(import { "a" as b } from "c")TS"},
		{"ImportDeclaration#11", R"TS(import type { "a" as b } from "c")TS"},
		{"ImportDeclaration#12", R"TS(import a, {} from "b")TS"},
		{"ImportDeclaration#13", R"TS(import a, * as b from "c")TS"},
		{"ImportDeclaration#14", R"TS(import {} from "a" with {})TS"},
		{"ImportDeclaration#15", R"TS(import {} from "a" with { b: "c" })TS"},
		{"ImportDeclaration#16", R"TS(import {} from "a" with { "b": "c" })TS"},
		{"ExportAssignment#1", R"TS(export = a)TS"},
		{"ExportAssignment#2", R"TS(export default a)TS"},
		{"NamespaceExportDeclaration", R"TS(export as namespace a)TS"},
		{"ExportDeclaration#1", R"TS(export * from "a")TS"},
		{"ExportDeclaration#2", R"TS(export type * from "a")TS"},
		{"ExportDeclaration#3", R"TS(export * as a from "b")TS"},
		{"ExportDeclaration#4", R"TS(export type * as a from "b")TS"},
		{"ExportDeclaration#5", R"TS(export { } from "a")TS"},
		{"ExportDeclaration#6", R"TS(export type { } from "a")TS"},
		{"ExportDeclaration#7", R"TS(export { a } from "b")TS"},
		{"ExportDeclaration#8", R"TS(export { type a } from "b")TS"},
		{"ExportDeclaration#9", R"TS(export type { a } from "b")TS"},
		{"ExportDeclaration#10", R"TS(export { a as b } from "c")TS"},
		{"ExportDeclaration#11", R"TS(export { type a as b } from "c")TS"},
		{"ExportDeclaration#12", R"TS(export type { a as b } from "c")TS"},
		{"ExportDeclaration#13", R"TS(export { a as "b" } from "c")TS"},
		{"ExportDeclaration#14", R"TS(export { type a as "b" } from "c")TS"},
		{"ExportDeclaration#15", R"TS(export type { a as "b" } from "c")TS"},
		{"ExportDeclaration#16", R"TS(export { "a" } from "b")TS"},
		{"ExportDeclaration#17", R"TS(export { type "a" } from "b")TS"},
		{"ExportDeclaration#18", R"TS(export type { "a" } from "b")TS"},
		{"ExportDeclaration#19", R"TS(export { "a" as b } from "c")TS"},
		{"ExportDeclaration#20", R"TS(export { type "a" as b } from "c")TS"},
		{"ExportDeclaration#21", R"TS(export type { "a" as b } from "c")TS"},
		{"ExportDeclaration#22", R"TS(export { "a" as "b" } from "c")TS"},
		{"ExportDeclaration#23", R"TS(export { type "a" as "b" } from "c")TS"},
		{"ExportDeclaration#24", R"TS(export type { "a" as "b" } from "c")TS"},
		{"ExportDeclaration#25", R"TS(export { })TS"},
		{"ExportDeclaration#26", R"TS(export type { })TS"},
		{"ExportDeclaration#27", R"TS(export { a })TS"},
		{"ExportDeclaration#28", R"TS(export { type a })TS"},
		{"ExportDeclaration#29", R"TS(export type { a })TS"},
		{"ExportDeclaration#30", R"TS(export { a as b })TS"},
		{"ExportDeclaration#31", R"TS(export { type a as b })TS"},
		{"ExportDeclaration#32", R"TS(export type { a as b })TS"},
		{"ExportDeclaration#33", R"TS(export { a as "b" })TS"},
		{"ExportDeclaration#34", R"TS(export { type a as "b" })TS"},
		{"ExportDeclaration#35", R"TS(export type { a as "b" })TS"},
		{"ExportDeclaration#36", R"TS(export {} from "a" with {})TS"},
		{"ExportDeclaration#37", R"TS(export {} from "a" with { b: "c" })TS"},
		{"ExportDeclaration#38", R"TS(export {} from "a" with { "b": "c" })TS"},
		{"KeywordTypeNode#1", R"TS(type T = any)TS"},
		{"KeywordTypeNode#2", R"TS(type T = unknown)TS"},
		{"KeywordTypeNode#3", R"TS(type T = never)TS"},
		{"KeywordTypeNode#4", R"TS(type T = void)TS"},
		{"KeywordTypeNode#5", R"TS(type T = undefined)TS"},
		{"KeywordTypeNode#6", R"TS(type T = null)TS"},
		{"KeywordTypeNode#7", R"TS(type T = object)TS"},
		{"KeywordTypeNode#8", R"TS(type T = string)TS"},
		{"KeywordTypeNode#9", R"TS(type T = symbol)TS"},
		{"KeywordTypeNode#10", R"TS(type T = number)TS"},
		{"KeywordTypeNode#11", R"TS(type T = bigint)TS"},
		{"KeywordTypeNode#12", R"TS(type T = boolean)TS"},
		{"KeywordTypeNode#13", R"TS(type T = intrinsic)TS"},
		{"TypePredicateNode#1", R"TS(function f(): asserts a)TS"},
		{"TypePredicateNode#2", R"TS(function f(): asserts a is b)TS"},
		{"TypePredicateNode#3", R"TS(function f(): asserts this)TS"},
		{"TypePredicateNode#4", R"TS(function f(): asserts this is b)TS"},
		{"TypeReferenceNode#1", R"TS(type T = a)TS"},
		{"TypeReferenceNode#2", R"TS(type T = a.b)TS"},
		{"TypeReferenceNode#3", R"TS(type T = a<U>)TS"},
		{"TypeReferenceNode#4", R"TS(type T = a.b<U>)TS"},
		{"FunctionTypeNode#1", R"TS(type T = () => a)TS"},
		{"FunctionTypeNode#2", R"TS(type T = <T>() => a)TS"},
		{"FunctionTypeNode#3", R"TS(type T = (a) => b)TS"},
		{"ConstructorTypeNode#1", R"TS(type T = new () => a)TS"},
		{"ConstructorTypeNode#2", R"TS(type T = new <T>() => a)TS"},
		{"ConstructorTypeNode#3", R"TS(type T = new (a) => b)TS"},
		{"ConstructorTypeNode#4", R"TS(type T = abstract new () => a)TS"},
		{"TypeQueryNode#1", R"TS(type T = typeof a)TS"},
		{"TypeQueryNode#2", R"TS(type T = typeof a.b)TS"},
		{"TypeQueryNode#3", R"TS(type T = typeof a<U>)TS"},
		{"TypeLiteralNode#1", R"TS(type T = {})TS"},
		{"TypeLiteralNode#2", R"TS(type T = {a})TS"},
		{"ArrayTypeNode", R"TS(type T = a[])TS"},
		{"TupleTypeNode#1", R"TS(type T = [])TS"},
		{"TupleTypeNode#2", R"TS(type T = [a])TS"},
		{"TupleTypeNode#3", R"TS(type T = [a,])TS"},
		{"RestTypeNode", R"TS(type T = [...a])TS"},
		{"OptionalTypeNode", R"TS(type T = [a?])TS"},
		{"NamedTupleMember#1", R"TS(type T = [a: b])TS"},
		{"NamedTupleMember#2", R"TS(type T = [a?: b])TS"},
		{"NamedTupleMember#3", R"TS(type T = [...a: b])TS"},
		{"UnionTypeNode#1", R"TS(type T = a | b)TS"},
		{"UnionTypeNode#2", R"TS(type T = a | b | c)TS"},
		{"UnionTypeNode#3", R"TS(type T = | a | b)TS"},
		{"IntersectionTypeNode#1", R"TS(type T = a & b)TS"},
		{"IntersectionTypeNode#2", R"TS(type T = a & b & c)TS"},
		{"IntersectionTypeNode#3", R"TS(type T = & a & b)TS"},
		{"ConditionalTypeNode", R"TS(type T = a extends b ? c : d)TS"},
		{"InferTypeNode#1", R"TS(type T = a extends infer b ? c : d)TS"},
		{"InferTypeNode#2", R"TS(type T = a extends infer b extends c ? d : e)TS"},
		{"ParenthesizedTypeNode", R"TS(type T = (U))TS"},
		{"ThisTypeNode", R"TS(type T = this)TS"},
		{"TypeOperatorNode#1", R"TS(type T = keyof U)TS"},
		{"TypeOperatorNode#2", R"TS(type T = readonly U[])TS"},
		{"TypeOperatorNode#3", R"TS(type T = unique symbol)TS"},
		{"IndexedAccessTypeNode", R"TS(type T = a[b])TS"},
		{"MappedTypeNode#1", R"TS(type T = { [a in b]: c })TS"},
		{"MappedTypeNode#2", R"TS(type T = { [a in b as c]: d })TS"},
		{"MappedTypeNode#3", R"TS(type T = { readonly [a in b]: c })TS"},
		{"MappedTypeNode#4", R"TS(type T = { +readonly [a in b]: c })TS"},
		{"MappedTypeNode#5", R"TS(type T = { -readonly [a in b]: c })TS"},
		{"MappedTypeNode#6", R"TS(type T = { [a in b]?: c })TS"},
		{"MappedTypeNode#7", R"TS(type T = { [a in b]+?: c })TS"},
		{"MappedTypeNode#8", R"TS(type T = { [a in b]-?: c })TS"},
		{"MappedTypeNode#9", R"TS(type T = { [a in b]: c; d })TS"},
		{"LiteralTypeNode#1", R"TS(type T = null)TS"},
		{"LiteralTypeNode#2", R"TS(type T = true)TS"},
		{"LiteralTypeNode#3", R"TS(type T = false)TS"},
		{"LiteralTypeNode#4", R"TS(type T = "")TS"},
		{"LiteralTypeNode#5", "type T = ''"},
		{"LiteralTypeNode#6", "type T = ``"},
		{"LiteralTypeNode#7", R"TS(type T = 0)TS"},
		{"LiteralTypeNode#8", R"TS(type T = 0n)TS"},
		{"LiteralTypeNode#9", R"TS(type T = -0)TS"},
		{"LiteralTypeNode#10", R"TS(type T = -0n)TS"},
		{"TemplateTypeNode#1", "type T = `a${b}c`"},
		{"TemplateTypeNode#2", "type T = `a${b}c${d}e`"},
		{"ImportTypeNode#1", R"TS(type T = import(a))TS"},
		{"ImportTypeNode#2", R"TS(type T = import(a).b)TS"},
		{"ImportTypeNode#3", R"TS(type T = import(a).b<U>)TS"},
		{"ImportTypeNode#4", R"TS(type T = typeof import(a))TS"},
		{"ImportTypeNode#5", R"TS(type T = typeof import(a).b)TS"},
		{"ImportTypeNode#6", R"TS(type T = import(a, { with: { } }))TS"},
		{"ImportTypeNode#6", R"TS(type T = import(a, { with: { b: "c" } }))TS"},
		{"ImportTypeNode#7", R"TS(type T = import(a, { with: { "b": "c" } }))TS"},
		{"PropertySignature#1", "interface I {a}"},
		{"PropertySignature#2", "interface I {readonly a}"},
		{"PropertySignature#3", "interface I {\"a\"}"},
		{"PropertySignature#4", "interface I {'a'}"},
		{"PropertySignature#5", "interface I {0}"},
		{"PropertySignature#6", "interface I {0n}"},
		{"PropertySignature#7", "interface I {[a]}"},
		{"PropertySignature#8", "interface I {a?}"},
		{"PropertySignature#9", "interface I {a: b}"},
		{"MethodSignature#1", "interface I {a()}"},
		{"MethodSignature#2", "interface I {\"a\"()}"},
		{"MethodSignature#3", "interface I {'a'()}"},
		{"MethodSignature#4", "interface I {0()}"},
		{"MethodSignature#5", "interface I {0n()}"},
		{"MethodSignature#6", "interface I {[a]()}"},
		{"MethodSignature#7", "interface I {a?()}"},
		{"MethodSignature#8", "interface I {a<T>()}"},
		{"MethodSignature#9", "interface I {a(): b}"},
		{"MethodSignature#10", "interface I {a(b): c}"},
		{"CallSignature#1", "interface I {()}"},
		{"CallSignature#2", "interface I {():a}"},
		{"CallSignature#3", "interface I {(p)}"},
		{"CallSignature#4", "interface I {<T>()}"},
		{"ConstructSignature#1", "interface I {new ()}"},
		{"ConstructSignature#2", "interface I {new ():a}"},
		{"ConstructSignature#3", "interface I {new (p)}"},
		{"ConstructSignature#4", "interface I {new <T>()}"},
		{"IndexSignatureDeclaration#1", "interface I {[a]}"},
		{"IndexSignatureDeclaration#2", "interface I {[a: b]}"},
		{"IndexSignatureDeclaration#3", "interface I {[a: b]: c}"},
		{"PropertyDeclaration#1", "class C {a}"},
		{"PropertyDeclaration#2", "class C {readonly a}"},
		{"PropertyDeclaration#3", "class C {static a}"},
		{"PropertyDeclaration#4", "class C {accessor a}"},
		{"PropertyDeclaration#5", "class C {\"a\"}"},
		{"PropertyDeclaration#6", "class C {'a'}"},
		{"PropertyDeclaration#7", "class C {0}"},
		{"PropertyDeclaration#8", "class C {0n}"},
		{"PropertyDeclaration#9", "class C {[a]}"},
		{"PropertyDeclaration#10", "class C {#a}"},
		{"PropertyDeclaration#11", "class C {a?}"},
		{"PropertyDeclaration#12", "class C {a!}"},
		{"PropertyDeclaration#13", "class C {a: b}"},
		{"PropertyDeclaration#14", "class C {a = b}"},
		{"PropertyDeclaration#15", "class C {@a b}"},
		{"MethodDeclaration#1", "class C {a()}"},
		{"MethodDeclaration#2", "class C {\"a\"()}"},
		{"MethodDeclaration#3", "class C {'a'()}"},
		{"MethodDeclaration#4", "class C {0()}"},
		{"MethodDeclaration#5", "class C {0n()}"},
		{"MethodDeclaration#6", "class C {[a]()}"},
		{"MethodDeclaration#7", "class C {#a()}"},
		{"MethodDeclaration#8", "class C {a?()}"},
		{"MethodDeclaration#9", "class C {a<T>()}"},
		{"MethodDeclaration#10", "class C {a(): b}"},
		{"MethodDeclaration#11", "class C {a(b): c}"},
		{"MethodDeclaration#12", "class C {a() {} }"},
		{"MethodDeclaration#13", "class C {@a b() {} }"},
		{"MethodDeclaration#14", "class C {static a() {} }"},
		{"MethodDeclaration#15", "class C {async a() {} }"},
		{"GetAccessorDeclaration#1", "class C {get a()}"},
		{"GetAccessorDeclaration#2", "class C {get \"a\"()}"},
		{"GetAccessorDeclaration#3", "class C {get 'a'()}"},
		{"GetAccessorDeclaration#4", "class C {get 0()}"},
		{"GetAccessorDeclaration#5", "class C {get 0n()}"},
		{"GetAccessorDeclaration#6", "class C {get [a]()}"},
		{"GetAccessorDeclaration#7", "class C {get #a()}"},
		{"GetAccessorDeclaration#8", "class C {get a(): b}"},
		{"GetAccessorDeclaration#9", "class C {get a(b): c}"},
		{"GetAccessorDeclaration#10", "class C {get a() {} }"},
		{"GetAccessorDeclaration#11", "class C {@a get b() {} }"},
		{"GetAccessorDeclaration#12", "class C {static get a() {} }"},
		{"SetAccessorDeclaration#1", "class C {set a()}"},
		{"SetAccessorDeclaration#2", "class C {set \"a\"()}"},
		{"SetAccessorDeclaration#3", "class C {set 'a'()}"},
		{"SetAccessorDeclaration#4", "class C {set 0()}"},
		{"SetAccessorDeclaration#5", "class C {set 0n()}"},
		{"SetAccessorDeclaration#6", "class C {set [a]()}"},
		{"SetAccessorDeclaration#7", "class C {set #a()}"},
		{"SetAccessorDeclaration#8", "class C {set a(): b}"},
		{"SetAccessorDeclaration#9", "class C {set a(b): c}"},
		{"SetAccessorDeclaration#10", "class C {set a() {} }"},
		{"SetAccessorDeclaration#11", "class C {@a set b() {} }"},
		{"SetAccessorDeclaration#12", "class C {static set a() {} }"},
		{"ConstructorDeclaration#1", "class C {constructor()}"},
		{"ConstructorDeclaration#2", "class C {constructor(): b}"},
		{"ConstructorDeclaration#3", "class C {constructor(b): c}"},
		{"ConstructorDeclaration#4", "class C {constructor() {} }"},
		{"ConstructorDeclaration#5", "class C {@a constructor() {} }"},
		{"ConstructorDeclaration#6", "class C {private constructor() {} }"},
		{"ClassStaticBlockDeclaration", "class C {static { }}"},
		{"SemicolonClassElement#1", "class C {;}"},
		{"ParameterDeclaration#1", "function f(a)"},
		{"ParameterDeclaration#2", "function f(a: b)"},
		{"ParameterDeclaration#3", "function f(a = b)"},
		{"ParameterDeclaration#4", "function f(a?)"},
		{"ParameterDeclaration#5", "function f(...a)"},
		{"ParameterDeclaration#6", "function f(this)"},
		{"ParameterDeclaration#7", "function f(a,)"},
		{"ObjectBindingPattern#1", "function f({})"},
		{"ObjectBindingPattern#2", "function f({a})"},
		{"ObjectBindingPattern#3", "function f({a = b})"},
		{"ObjectBindingPattern#4", "function f({a: b})"},
		{"ObjectBindingPattern#5", "function f({a: b = c})"},
		{"ObjectBindingPattern#6", "function f({\"a\": b})"},
		{"ObjectBindingPattern#7", "function f({'a': b})"},
		{"ObjectBindingPattern#8", "function f({0: b})"},
		{"ObjectBindingPattern#9", "function f({[a]: b})"},
		{"ObjectBindingPattern#10", "function f({...a})"},
		{"ObjectBindingPattern#11", "function f({a: {}})"},
		{"ObjectBindingPattern#12", "function f({a: []})"},
		{"ArrayBindingPattern#1", "function f([])"},
		{"ArrayBindingPattern#2", "function f([,])"},
		{"ArrayBindingPattern#3", "function f([a])"},
		{"ArrayBindingPattern#4", "function f([a, b])"},
		{"ArrayBindingPattern#5", "function f([a, , b])"},
		{"ArrayBindingPattern#6", "function f([a = b])"},
		{"ArrayBindingPattern#7", "function f([...a])"},
		{"ArrayBindingPattern#8", "function f([{}])"},
		{"ArrayBindingPattern#9", "function f([[]])"},
		{"TypeParameterDeclaration#1", "function f<T>();"},
		{"TypeParameterDeclaration#2", "function f<in T>();"},
		{"TypeParameterDeclaration#3", "function f<T extends U>();"},
		{"TypeParameterDeclaration#4", "function f<T = U>();"},
		{"TypeParameterDeclaration#5", "function f<T extends U = V>();"},
		{"TypeParameterDeclaration#6", "function f<T, U>();"},
		{"TypeParameterDeclaration#7", "function f<T,>();"},
		{"JsxElement1", "<a></a>"},
		{"JsxElement2", "<this></this>"},
		{"JsxElement3", "<a:b></a:b>"},
		{"JsxElement4", "<a.b></a.b>"},
		{"JsxElement5", "<a<b>></a>"},
		{"JsxElement6", "<a b></a>"},
		{"JsxElement7", "<a>b</a>"},
		{"JsxElement8", "<a>{b}</a>"},
		{"JsxElement9", "<a><b></b></a>"},
		{"JsxElement10", "<a><b /></a>"},
		{"JsxElement11", "<a><></></a>"},
		{"JsxSelfClosingElement1", "<a />"},
		{"JsxSelfClosingElement2", "<this />"},
		{"JsxSelfClosingElement3", "<a:b />"},
		{"JsxSelfClosingElement4", "<a.b />"},
		{"JsxSelfClosingElement5", "<a<b> />"},
		{"JsxSelfClosingElement6", "<a b/>"},
		{"JsxFragment1", "<></>"},
		{"JsxFragment2", "<>b</>"},
		{"JsxFragment3", "<>{b}</>"},
		{"JsxFragment4", "<><b></b></>"},
		{"JsxFragment5", "<><b /></>"},
		{"JsxFragment6", "<><></></>"},
		{"JsxAttribute1", "<a b/>"},
		{"JsxAttribute2", "<a b:c/>"},
		{"JsxAttribute3", "<a b=\"c\"/>"},
		{"JsxAttribute4", "<a b='c'/>"},
		{"JsxAttribute5", "<a b={c}/>"},
		{"JsxAttribute6", "<a b=<c></c>/>"},
		{"JsxAttribute7", "<a b=<c />/>"},
		{"JsxAttribute8", "<a b=<></>/>"},
		{"JsxSpreadAttribute", "<a {...b}/>"},
	};
	for (auto& rec : data) {
		std::string title = rec.title;
		std::string input = rec.input;
		t->Run("Clone " + title, [input](T* t) {
			t->Parallel();

			auto* factory = new NodeFactory();
			Node* file = testutil::parsetestutil::ParseTypeScript(input, false)->asNode();
			Node* clone = deepCloneNode(*factory, file->asNode())->asNode();

			std::vector<NodeComparisonWorkItem> work{{file, clone}};

			while (!work.empty()) {
				std::vector<NodeComparisonWorkItem> nextWork;
				for (auto& item : work) {
					gotest::assert::Assert(t, item.original != item.copy);
					std::vector<Node*> originalChildren =
						getChildren(item.original);
					std::vector<Node*> copyChildren = getChildren(item.copy);
					gotest::assert::Equal(
						t, (int)originalChildren.size(),
						(int)copyChildren.size());
					for (size_t i = 0; i < originalChildren.size(); i++) {
						nextWork.push_back(
							{originalChildren[i], copyChildren[i]});
					}
				}
				work = nextWork;
			}
			delete factory;
		});
	}
}

REGISTER_UNIT_TEST("ast.TestDeepCloneNodeSanityCheck",
				   TestDeepCloneNodeSanityCheck);
