// Code generated by tools/scripts/tsc/generate-encoder.ts. DO NOT EDIT.
// (Ported output of decoder_generated.go — keep in sync with the generator.)

#include "internal/api/encoder/encoder_internal.h"

namespace tsc::api::encoder {

std::tuple<Node*, gostd::Error> astDecoder::createStringNode(Kind kind,
                                                           uint32_t data,
                                                           uint8_t commonData) {
	uint32_t strIdx = data & NodeDataStringIndexMask;
	std::string text{getString(strIdx)};

	switch (kind) {
	case Kind::Identifier:
		return {factory->newIdentifier(text), nullptr};
	case Kind::PrivateIdentifier:
		return {factory->newPrivateIdentifier(text), nullptr};
	case Kind::JsxText: {
		bool containsOnlyTriviaWhiteSpaces = (commonData & 1) != 0;
		return {factory->newJsxText(text, containsOnlyTriviaWhiteSpaces),
		        nullptr};
	}
	case Kind::JSDocText:
		return {factory->newJSDocText({text}), nullptr};
	case Kind::JSDocLink:
		return {factory->newJSDocLink(nullptr, {text}), nullptr};
	case Kind::JSDocLinkPlain:
		return {factory->newJSDocLinkPlain(nullptr, {text}), nullptr};
	case Kind::JSDocLinkCode:
		return {factory->newJSDocLinkCode(nullptr, {text}), nullptr};
	default:
		return {nullptr,
		        gostd::errorf("unknown string node kind %d",
		                      {static_cast<int>(kind)})};
	}
}

std::tuple<Node*, gostd::Error> astDecoder::createExtendedNode(
    Kind kind, uint32_t data, const std::vector<int>& childIndices,
    uint8_t commonData) {
	switch (kind) {
	case Kind::StringLiteral:
		return decodeExtendedData_StringLiteral(data, childIndices, commonData);
	case Kind::NumericLiteral:
		return decodeExtendedData_NumericLiteral(data, childIndices,
		                                         commonData);
	case Kind::BigIntLiteral:
		return decodeExtendedData_BigIntLiteral(data, childIndices, commonData);
	case Kind::RegularExpressionLiteral:
		return decodeExtendedData_RegularExpressionLiteral(data, childIndices,
		                                                   commonData);
	case Kind::NoSubstitutionTemplateLiteral:
		return decodeExtendedData_NoSubstitutionTemplateLiteral(
		    data, childIndices, commonData);
	case Kind::TemplateHead:
		return decodeExtendedData_TemplateHead(data, childIndices, commonData);
	case Kind::TemplateMiddle:
		return decodeExtendedData_TemplateMiddle(data, childIndices,
		                                         commonData);
	case Kind::TemplateTail:
		return decodeExtendedData_TemplateTail(data, childIndices, commonData);
	case Kind::SourceFile:
		return decodeExtendedData_SourceFile(data, childIndices, commonData);
	default:
		return {nullptr,
		        gostd::errorf("unknown extended data node kind %d",
		                      {static_cast<int>(kind)})};
	}
}

std::tuple<Node*, gostd::Error> astDecoder::createChildrenNode(
    Kind kind, uint32_t data, const std::vector<int>& childIndices,
    uint8_t commonData) {
	uint8_t mask = static_cast<uint8_t>(data & NodeDataChildMask);
	Node* ok_ = nullptr; // success helper
	(void)ok_;

	switch (kind) {
	case Kind::Unknown:
	case Kind::EndOfFile:
	case Kind::SingleLineCommentTrivia:
	case Kind::MultiLineCommentTrivia:
	case Kind::NewLineTrivia:
	case Kind::WhitespaceTrivia:
	case Kind::ConflictMarkerTrivia:
	case Kind::NonTextFileMarkerTrivia:
	case Kind::NumericLiteral:
	case Kind::BigIntLiteral:
	case Kind::StringLiteral:
	case Kind::JsxText:
	case Kind::JsxTextAllWhiteSpaces:
	case Kind::RegularExpressionLiteral:
	case Kind::NoSubstitutionTemplateLiteral:
	case Kind::TemplateHead:
	case Kind::TemplateMiddle:
	case Kind::TemplateTail:
	case Kind::OpenBraceToken:
	case Kind::CloseBraceToken:
	case Kind::OpenParenToken:
	case Kind::CloseParenToken:
	case Kind::OpenBracketToken:
	case Kind::CloseBracketToken:
	case Kind::DotToken:
	case Kind::DotDotDotToken:
	case Kind::SemicolonToken:
	case Kind::CommaToken:
	case Kind::QuestionDotToken:
	case Kind::LessThanToken:
	case Kind::LessThanSlashToken:
	case Kind::GreaterThanToken:
	case Kind::LessThanEqualsToken:
	case Kind::GreaterThanEqualsToken:
	case Kind::EqualsEqualsToken:
	case Kind::ExclamationEqualsToken:
	case Kind::EqualsEqualsEqualsToken:
	case Kind::ExclamationEqualsEqualsToken:
	case Kind::EqualsGreaterThanToken:
	case Kind::PlusToken:
	case Kind::MinusToken:
	case Kind::AsteriskToken:
	case Kind::AsteriskAsteriskToken:
	case Kind::SlashToken:
	case Kind::PercentToken:
	case Kind::PlusPlusToken:
	case Kind::MinusMinusToken:
	case Kind::LessThanLessThanToken:
	case Kind::GreaterThanGreaterThanToken:
	case Kind::GreaterThanGreaterThanGreaterThanToken:
	case Kind::AmpersandToken:
	case Kind::BarToken:
	case Kind::CaretToken:
	case Kind::ExclamationToken:
	case Kind::TildeToken:
	case Kind::AmpersandAmpersandToken:
	case Kind::BarBarToken:
	case Kind::QuestionToken:
	case Kind::ColonToken:
	case Kind::AtToken:
	case Kind::QuestionQuestionToken:
	case Kind::BacktickToken:
	case Kind::HashToken:
	case Kind::EqualsToken:
	case Kind::PlusEqualsToken:
	case Kind::MinusEqualsToken:
	case Kind::AsteriskEqualsToken:
	case Kind::AsteriskAsteriskEqualsToken:
	case Kind::SlashEqualsToken:
	case Kind::PercentEqualsToken:
	case Kind::LessThanLessThanEqualsToken:
	case Kind::GreaterThanGreaterThanEqualsToken:
	case Kind::GreaterThanGreaterThanGreaterThanEqualsToken:
	case Kind::AmpersandEqualsToken:
	case Kind::BarEqualsToken:
	case Kind::BarBarEqualsToken:
	case Kind::AmpersandAmpersandEqualsToken:
	case Kind::QuestionQuestionEqualsToken:
	case Kind::CaretEqualsToken:
	case Kind::Identifier:
	case Kind::PrivateIdentifier:
	case Kind::JSDocCommentTextToken:
	case Kind::BreakKeyword:
	case Kind::CaseKeyword:
	case Kind::CatchKeyword:
	case Kind::ClassKeyword:
	case Kind::ConstKeyword:
	case Kind::ContinueKeyword:
	case Kind::DebuggerKeyword:
	case Kind::DefaultKeyword:
	case Kind::DeleteKeyword:
	case Kind::DoKeyword:
	case Kind::ElseKeyword:
	case Kind::EnumKeyword:
	case Kind::ExportKeyword:
	case Kind::ExtendsKeyword:
	case Kind::FinallyKeyword:
	case Kind::ForKeyword:
	case Kind::FunctionKeyword:
	case Kind::IfKeyword:
	case Kind::InKeyword:
	case Kind::InstanceOfKeyword:
	case Kind::NewKeyword:
	case Kind::ReturnKeyword:
	case Kind::SwitchKeyword:
	case Kind::ThrowKeyword:
	case Kind::TryKeyword:
	case Kind::TypeOfKeyword:
	case Kind::VarKeyword:
	case Kind::WhileKeyword:
	case Kind::WithKeyword:
	case Kind::ImplementsKeyword:
	case Kind::InterfaceKeyword:
	case Kind::LetKeyword:
	case Kind::PackageKeyword:
	case Kind::PrivateKeyword:
	case Kind::ProtectedKeyword:
	case Kind::PublicKeyword:
	case Kind::StaticKeyword:
	case Kind::YieldKeyword:
	case Kind::AbstractKeyword:
	case Kind::AccessorKeyword:
	case Kind::AsKeyword:
	case Kind::AssertsKeyword:
	case Kind::AssertKeyword:
	case Kind::AsyncKeyword:
	case Kind::AwaitKeyword:
	case Kind::ConstructorKeyword:
	case Kind::DeclareKeyword:
	case Kind::GetKeyword:
	case Kind::ImmediateKeyword:
	case Kind::InferKeyword:
	case Kind::IsKeyword:
	case Kind::KeyOfKeyword:
	case Kind::ModuleKeyword:
	case Kind::NamespaceKeyword:
	case Kind::OutKeyword:
	case Kind::ReadonlyKeyword:
	case Kind::RequireKeyword:
	case Kind::SatisfiesKeyword:
	case Kind::SetKeyword:
	case Kind::TypeKeyword:
	case Kind::UniqueKeyword:
	case Kind::UsingKeyword:
	case Kind::FromKeyword:
	case Kind::GlobalKeyword:
	case Kind::OverrideKeyword:
	case Kind::OfKeyword:
	case Kind::DeferKeyword:
		return {factory->newToken(kind), nullptr};
	case Kind::QualifiedName: {
		childIterator it{childIndices, 0};
		Node* left = nodeAt(it.nextIf(mask, 0));
		Node* right = nodeAt(it.nextIf(mask, 1));
		return {factory->newQualifiedName(left, right), nullptr};
	}
	case Kind::ComputedPropertyName:
		return {factory->newComputedPropertyName(singleChild(childIndices)),
		        nullptr};
	case Kind::Decorator:
		return {factory->newDecorator(singleChild(childIndices)), nullptr};
	case Kind::EmptyStatement:
		return {factory->newEmptyStatement(), nullptr};
	case Kind::IfStatement: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		Node* thenStatement = nodeAt(it.nextIf(mask, 1));
		Node* elseStatement = nodeAt(it.nextIf(mask, 2));
		return {factory->newIfStatement(expression, thenStatement,
		                                elseStatement),
		        nullptr};
	}
	case Kind::DoStatement: {
		childIterator it{childIndices, 0};
		Node* statement = nodeAt(it.nextIf(mask, 0));
		Node* expression = nodeAt(it.nextIf(mask, 1));
		return {factory->newDoStatement(statement, expression), nullptr};
	}
	case Kind::WhileStatement: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		Node* statement = nodeAt(it.nextIf(mask, 1));
		return {factory->newWhileStatement(expression, statement), nullptr};
	}
	case Kind::ForStatement: {
		childIterator it{childIndices, 0};
		Node* initializer = nodeAt(it.nextIf(mask, 0));
		Node* condition = nodeAt(it.nextIf(mask, 1));
		Node* incrementor = nodeAt(it.nextIf(mask, 2));
		Node* statement = nodeAt(it.nextIf(mask, 3));
		return {factory->newForStatement(initializer, condition, incrementor,
		                                 statement),
		        nullptr};
	}
	case Kind::ForInStatement:
	case Kind::ForOfStatement: {
		childIterator it{childIndices, 0};
		Node* awaitModifier = nodeAt(it.nextIf(mask, 0));
		Node* initializer = nodeAt(it.nextIf(mask, 1));
		Node* expression = nodeAt(it.nextIf(mask, 2));
		Node* statement = nodeAt(it.nextIf(mask, 3));
		return {factory->newForInOrOfStatement(kind, awaitModifier, initializer,
		                                       expression, statement),
		        nullptr};
	}
	case Kind::BreakStatement:
		return {factory->newBreakStatement(singleChild(childIndices)), nullptr};
	case Kind::ContinueStatement:
		return {factory->newContinueStatement(singleChild(childIndices)),
		        nullptr};
	case Kind::ReturnStatement:
		return {factory->newReturnStatement(singleChild(childIndices)),
		        nullptr};
	case Kind::WithStatement: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		Node* statement = nodeAt(it.nextIf(mask, 1));
		return {factory->newWithStatement(expression, statement), nullptr};
	}
	case Kind::SwitchStatement: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		Node* caseBlock = nodeAt(it.nextIf(mask, 1));
		return {factory->newSwitchStatement(expression, caseBlock), nullptr};
	}
	case Kind::CaseBlock:
		return {factory->newCaseBlock(singleNodeListChild(childIndices)),
		        nullptr};
	case Kind::CaseClause:
	case Kind::DefaultClause: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		NodeList* statements = nodeListAt(it.nextIf(mask, 1));
		return {factory->newCaseOrDefaultClause(kind, expression, statements),
		        nullptr};
	}
	case Kind::ThrowStatement:
		return {factory->newThrowStatement(singleChild(childIndices)), nullptr};
	case Kind::TryStatement: {
		childIterator it{childIndices, 0};
		Node* tryBlock = nodeAt(it.nextIf(mask, 0));
		Node* catchClause = nodeAt(it.nextIf(mask, 1));
		Node* finallyBlock = nodeAt(it.nextIf(mask, 2));
		return {factory->newTryStatement(tryBlock, catchClause, finallyBlock),
		        nullptr};
	}
	case Kind::CatchClause: {
		childIterator it{childIndices, 0};
		Node* variableDeclaration = nodeAt(it.nextIf(mask, 0));
		Node* block = nodeAt(it.nextIf(mask, 1));
		return {factory->newCatchClause(variableDeclaration, block), nullptr};
	}
	case Kind::DebuggerStatement:
		return {factory->newDebuggerStatement(), nullptr};
	case Kind::LabeledStatement: {
		childIterator it{childIndices, 0};
		Node* label = nodeAt(it.nextIf(mask, 0));
		Node* statement = nodeAt(it.nextIf(mask, 1));
		return {factory->newLabeledStatement(label, statement), nullptr};
	}
	case Kind::ExpressionStatement:
		return {factory->newExpressionStatement(singleChild(childIndices)),
		        nullptr};
	case Kind::Block: {
		bool multiLine = (commonData & 1) != 0;
		NodeList* list = nullptr;
		if (!childIndices.empty()) {
			list = nodeListAt(childIndices[0]);
		}
		return {factory->newBlock(list, multiLine), nullptr};
	}
	case Kind::VariableStatement: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* declarationList = nodeAt(it.nextIf(mask, 1));
		return {factory->newVariableStatement(modifiers, declarationList),
		        nullptr};
	}
	case Kind::VariableDeclaration: {
		childIterator it{childIndices, 0};
		Node* name = nodeAt(it.nextIf(mask, 0));
		Node* exclamationToken = nodeAt(it.nextIf(mask, 1));
		Node* typeNode = nodeAt(it.nextIf(mask, 2));
		Node* initializer = nodeAt(it.nextIf(mask, 3));
		return {factory->newVariableDeclaration(name, exclamationToken,
		                                        typeNode, initializer),
		        nullptr};
	}
	case Kind::VariableDeclarationList:
		return {factory->newVariableDeclarationList(
		            singleNodeListChild(childIndices), NodeFlagsNone),
		        nullptr};
	case Kind::ObjectBindingPattern:
	case Kind::ArrayBindingPattern:
		return {factory->newBindingPattern(kind,
		                                   singleNodeListChild(childIndices)),
		        nullptr};
	case Kind::Parameter: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* dotDotDotToken = nodeAt(it.nextIf(mask, 1));
		Node* name = nodeAt(it.nextIf(mask, 2));
		Node* questionToken = nodeAt(it.nextIf(mask, 3));
		Node* typeNode = nodeAt(it.nextIf(mask, 4));
		Node* initializer = nodeAt(it.nextIf(mask, 5));
		return {factory->newParameterDeclaration(modifiers, dotDotDotToken,
		                                         name, questionToken, typeNode,
		                                         initializer),
		        nullptr};
	}
	case Kind::BindingElement: {
		childIterator it{childIndices, 0};
		Node* dotDotDotToken = nodeAt(it.nextIf(mask, 0));
		Node* propertyName = nodeAt(it.nextIf(mask, 1));
		Node* name = nodeAt(it.nextIf(mask, 2));
		Node* initializer = nodeAt(it.nextIf(mask, 3));
		return {factory->newBindingElement(dotDotDotToken, propertyName, name,
		                                   initializer),
		        nullptr};
	}
	case Kind::MissingDeclaration: {
		ModifierList* mods = nullptr;
		if (!childIndices.empty()) {
			mods = modifierListAt(childIndices[0]);
		}
		return {factory->newMissingDeclaration(mods), nullptr};
	}
	case Kind::FunctionDeclaration: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* asteriskToken = nodeAt(it.nextIf(mask, 1));
		Node* name = nodeAt(it.nextIf(mask, 2));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 3));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 4));
		Node* typeNode = nodeAt(it.nextIf(mask, 5));
		Node* body = nodeAt(it.nextIf(mask, 6));
		return {factory->newFunctionDeclaration(modifiers, asteriskToken, name,
		                                        typeParameters, parameters,
		                                        typeNode, nullptr, body),
		        nullptr};
	}
	case Kind::ClassDeclaration: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 2));
		NodeList* heritageClauses = nodeListAt(it.nextIf(mask, 3));
		NodeList* members = nodeListAt(it.nextIf(mask, 4));
		return {factory->newClassDeclaration(modifiers, name, typeParameters,
		                                     heritageClauses, members),
		        nullptr};
	}
	case Kind::ClassExpression: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 2));
		NodeList* heritageClauses = nodeListAt(it.nextIf(mask, 3));
		NodeList* members = nodeListAt(it.nextIf(mask, 4));
		return {factory->newClassExpression(modifiers, name, typeParameters,
		                                    heritageClauses, members),
		        nullptr};
	}
	case Kind::HeritageClause: {
		Kind token = Kind::ExtendsKeyword;
		if ((commonData & 1) != 0) {
			token = Kind::ImplementsKeyword;
		}
		return {factory->newHeritageClause(token,
		                                   singleNodeListChild(childIndices)),
		        nullptr};
	}
	case Kind::InterfaceDeclaration: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 2));
		NodeList* heritageClauses = nodeListAt(it.nextIf(mask, 3));
		NodeList* members = nodeListAt(it.nextIf(mask, 4));
		return {factory->newInterfaceDeclaration(modifiers, name,
		                                         typeParameters,
		                                         heritageClauses, members),
		        nullptr};
	}
	case Kind::TypeAliasDeclaration:
	case Kind::JSTypeAliasDeclaration: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 2));
		Node* typeNode = nodeAt(it.nextIf(mask, 3));
		if (kind == Kind::JSTypeAliasDeclaration) {
			return {factory->newJSTypeAliasDeclaration(modifiers, name,
			                                           typeParameters,
			                                           typeNode),
			        nullptr};
		}
		return {factory->newTypeAliasDeclaration(modifiers, name,
		                                         typeParameters, typeNode),
		        nullptr};
	}
	case Kind::EnumMember: {
		childIterator it{childIndices, 0};
		Node* name = nodeAt(it.nextIf(mask, 0));
		Node* initializer = nodeAt(it.nextIf(mask, 1));
		return {factory->newEnumMember(name, initializer), nullptr};
	}
	case Kind::EnumDeclaration: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		NodeList* members = nodeListAt(it.nextIf(mask, 2));
		return {factory->newEnumDeclaration(modifiers, name, members), nullptr};
	}
	case Kind::ModuleBlock:
		return {factory->newModuleBlock(singleNodeListChild(childIndices)),
		        nullptr};
	case Kind::NotEmittedStatement:
		return {factory->newNotEmittedStatement(), nullptr};
	case Kind::NotEmittedTypeElement:
		return {factory->newNotEmittedTypeElement(), nullptr};
	case Kind::ImportDeclaration:
	case Kind::JSImportDeclaration: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* importClause = nodeAt(it.nextIf(mask, 1));
		Node* moduleSpecifier = nodeAt(it.nextIf(mask, 2));
		Node* attributes = nodeAt(it.nextIf(mask, 3));
		if (kind == Kind::JSImportDeclaration) {
			return {factory->newJSImportDeclaration(modifiers, importClause,
			                                        moduleSpecifier, attributes),
			        nullptr};
		}
		return {factory->newImportDeclaration(modifiers, importClause,
		                                      moduleSpecifier, attributes),
		        nullptr};
	}
	case Kind::ExternalModuleReference:
		return {factory->newExternalModuleReference(singleChild(childIndices)),
		        nullptr};
	case Kind::NamespaceImport:
		return {factory->newNamespaceImport(singleChild(childIndices)),
		        nullptr};
	case Kind::NamedImports:
		return {factory->newNamedImports(singleNodeListChild(childIndices)),
		        nullptr};
	case Kind::ExportAssignment: {
		bool isExportEquals = (commonData & 1) != 0;
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* typeNode = nodeAt(it.nextIf(mask, 1));
		Node* expression = nodeAt(it.nextIf(mask, 2));
		return {factory->newExportAssignment(modifiers, isExportEquals,
		                                     typeNode, expression),
		        nullptr};
	}
	case Kind::NamespaceExportDeclaration: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		return {factory->newNamespaceExportDeclaration(modifiers, name),
		        nullptr};
	}
	case Kind::NamespaceExport:
		return {factory->newNamespaceExport(singleChild(childIndices)),
		        nullptr};
	case Kind::NamedExports:
		return {factory->newNamedExports(singleNodeListChild(childIndices)),
		        nullptr};
	case Kind::ExportSpecifier: {
		bool isTypeOnly = (commonData & 1) != 0;
		childIterator it{childIndices, 0};
		Node* propertyName = nodeAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		return {factory->newExportSpecifier(isTypeOnly, propertyName, name),
		        nullptr};
	}
	case Kind::CallSignature: {
		childIterator it{childIndices, 0};
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 0));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 1));
		Node* typeNode = nodeAt(it.nextIf(mask, 2));
		return {factory->newCallSignatureDeclaration(typeParameters, parameters,
		                                             typeNode),
		        nullptr};
	}
	case Kind::ConstructSignature: {
		childIterator it{childIndices, 0};
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 0));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 1));
		Node* typeNode = nodeAt(it.nextIf(mask, 2));
		return {factory->newConstructSignatureDeclaration(typeParameters,
		                                                  parameters, typeNode),
		        nullptr};
	}
	case Kind::Constructor: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 1));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 2));
		Node* typeNode = nodeAt(it.nextIf(mask, 3));
		Node* body = nodeAt(it.nextIf(mask, 4));
		return {factory->newConstructorDeclaration(modifiers, typeParameters,
		                                           parameters, typeNode,
		                                           nullptr, body),
		        nullptr};
	}
	case Kind::GetAccessor: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 2));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 3));
		Node* typeNode = nodeAt(it.nextIf(mask, 4));
		Node* body = nodeAt(it.nextIf(mask, 5));
		return {factory->newGetAccessorDeclaration(modifiers, name,
		                                           typeParameters, parameters,
		                                           typeNode, nullptr, body),
		        nullptr};
	}
	case Kind::SetAccessor: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 2));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 3));
		Node* typeNode = nodeAt(it.nextIf(mask, 4));
		Node* body = nodeAt(it.nextIf(mask, 5));
		return {factory->newSetAccessorDeclaration(modifiers, name,
		                                           typeParameters, parameters,
		                                           typeNode, nullptr, body),
		        nullptr};
	}
	case Kind::IndexSignature: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 1));
		Node* typeNode = nodeAt(it.nextIf(mask, 2));
		return {factory->newIndexSignatureDeclaration(modifiers, parameters,
		                                              typeNode),
		        nullptr};
	}
	case Kind::MethodSignature: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		Node* postfixToken = nodeAt(it.nextIf(mask, 2));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 3));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 4));
		Node* typeNode = nodeAt(it.nextIf(mask, 5));
		return {factory->newMethodSignatureDeclaration(modifiers, name,
		                                               postfixToken,
		                                               typeParameters,
		                                               parameters, typeNode),
		        nullptr};
	}
	case Kind::MethodDeclaration: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* asteriskToken = nodeAt(it.nextIf(mask, 1));
		Node* name = nodeAt(it.nextIf(mask, 2));
		Node* postfixToken = nodeAt(it.nextIf(mask, 3));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 4));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 5));
		Node* typeNode = nodeAt(it.nextIf(mask, 6));
		Node* body = nodeAt(it.nextIf(mask, 7));
		return {factory->newMethodDeclaration(modifiers, asteriskToken, name,
		                                      postfixToken, typeParameters,
		                                      parameters, typeNode, nullptr,
		                                      body),
		        nullptr};
	}
	case Kind::PropertySignature: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		Node* postfixToken = nodeAt(it.nextIf(mask, 2));
		Node* typeNode = nodeAt(it.nextIf(mask, 3));
		Node* initializer = nodeAt(it.nextIf(mask, 4));
		return {factory->newPropertySignatureDeclaration(modifiers, name,
		                                                 postfixToken, typeNode,
		                                                 initializer),
		        nullptr};
	}
	case Kind::PropertyDeclaration: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		Node* postfixToken = nodeAt(it.nextIf(mask, 2));
		Node* typeNode = nodeAt(it.nextIf(mask, 3));
		Node* initializer = nodeAt(it.nextIf(mask, 4));
		return {factory->newPropertyDeclaration(modifiers, name, postfixToken,
		                                        typeNode, initializer),
		        nullptr};
	}
	case Kind::SemicolonClassElement:
		return {factory->newSemicolonClassElement(), nullptr};
	case Kind::ClassStaticBlockDeclaration: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* body = nodeAt(it.nextIf(mask, 1));
		return {factory->newClassStaticBlockDeclaration(modifiers, body),
		        nullptr};
	}
	case Kind::OmittedExpression:
		return {factory->newOmittedExpression(), nullptr};
	case Kind::FalseKeyword:
	case Kind::ImportKeyword:
	case Kind::NullKeyword:
	case Kind::SuperKeyword:
	case Kind::ThisKeyword:
	case Kind::TrueKeyword:
		return {factory->newKeywordExpression(kind), nullptr};
	case Kind::BinaryExpression: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* left = nodeAt(it.nextIf(mask, 1));
		Node* typeNode = nodeAt(it.nextIf(mask, 2));
		Node* operatorToken = nodeAt(it.nextIf(mask, 3));
		Node* right = nodeAt(it.nextIf(mask, 4));
		return {factory->newBinaryExpression(modifiers, left, typeNode,
		                                     operatorToken, right),
		        nullptr};
	}
	case Kind::PrefixUnaryExpression: {
		Kind operator_ = Kind::Unknown;
		switch (commonData & 7) {
		case 0: operator_ = Kind::PlusToken; break;
		case 1: operator_ = Kind::MinusToken; break;
		case 2: operator_ = Kind::TildeToken; break;
		case 3: operator_ = Kind::ExclamationToken; break;
		case 4: operator_ = Kind::PlusPlusToken; break;
		case 5: operator_ = Kind::MinusMinusToken; break;
		default: break;
		}
		return {factory->newPrefixUnaryExpression(operator_,
		                                          singleChild(childIndices)),
		        nullptr};
	}
	case Kind::PostfixUnaryExpression: {
		Kind operator_ = Kind::PlusPlusToken;
		if ((commonData & 1) != 0) {
			operator_ = Kind::MinusMinusToken;
		}
		return {factory->newPostfixUnaryExpression(singleChild(childIndices),
		                                           operator_),
		        nullptr};
	}
	case Kind::YieldExpression: {
		childIterator it{childIndices, 0};
		Node* asteriskToken = nodeAt(it.nextIf(mask, 0));
		Node* expression = nodeAt(it.nextIf(mask, 1));
		return {factory->newYieldExpression(asteriskToken, expression),
		        nullptr};
	}
	case Kind::ArrowFunction: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 1));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 2));
		Node* typeNode = nodeAt(it.nextIf(mask, 3));
		Node* equalsGreaterThanToken = nodeAt(it.nextIf(mask, 4));
		Node* body = nodeAt(it.nextIf(mask, 5));
		return {factory->newArrowFunction(modifiers, typeParameters, parameters,
		                                  typeNode, nullptr,
		                                  equalsGreaterThanToken, body),
		        nullptr};
	}
	case Kind::FunctionExpression: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* asteriskToken = nodeAt(it.nextIf(mask, 1));
		Node* name = nodeAt(it.nextIf(mask, 2));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 3));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 4));
		Node* typeNode = nodeAt(it.nextIf(mask, 5));
		Node* body = nodeAt(it.nextIf(mask, 6));
		return {factory->newFunctionExpression(modifiers, asteriskToken, name,
		                                       typeParameters, parameters,
		                                       typeNode, nullptr, body),
		        nullptr};
	}
	case Kind::AsExpression: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		Node* typeNode = nodeAt(it.nextIf(mask, 1));
		return {factory->newAsExpression(expression, typeNode), nullptr};
	}
	case Kind::SatisfiesExpression: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		Node* typeNode = nodeAt(it.nextIf(mask, 1));
		return {factory->newSatisfiesExpression(expression, typeNode), nullptr};
	}
	case Kind::ConditionalExpression: {
		childIterator it{childIndices, 0};
		Node* condition = nodeAt(it.nextIf(mask, 0));
		Node* questionToken = nodeAt(it.nextIf(mask, 1));
		Node* whenTrue = nodeAt(it.nextIf(mask, 2));
		Node* colonToken = nodeAt(it.nextIf(mask, 3));
		Node* whenFalse = nodeAt(it.nextIf(mask, 4));
		return {factory->newConditionalExpression(condition, questionToken,
		                                          whenTrue, colonToken,
		                                          whenFalse),
		        nullptr};
	}
	case Kind::PropertyAccessExpression: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		Node* questionDotToken = nodeAt(it.nextIf(mask, 1));
		Node* name = nodeAt(it.nextIf(mask, 2));
		return {factory->newPropertyAccessExpression(expression,
		                                             questionDotToken, name,
		                                             NodeFlagsNone),
		        nullptr};
	}
	case Kind::ElementAccessExpression: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		Node* questionDotToken = nodeAt(it.nextIf(mask, 1));
		Node* argumentExpression = nodeAt(it.nextIf(mask, 2));
		return {factory->newElementAccessExpression(expression, questionDotToken,
		                                            argumentExpression,
		                                            NodeFlagsNone),
		        nullptr};
	}
	case Kind::CallExpression: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		Node* questionDotToken = nodeAt(it.nextIf(mask, 1));
		NodeList* typeArguments = nodeListAt(it.nextIf(mask, 2));
		NodeList* arguments = nodeListAt(it.nextIf(mask, 3));
		return {factory->newCallExpression(expression, questionDotToken,
		                                   typeArguments, arguments,
		                                   NodeFlagsNone),
		        nullptr};
	}
	case Kind::NewExpression: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		NodeList* typeArguments = nodeListAt(it.nextIf(mask, 1));
		NodeList* arguments = nodeListAt(it.nextIf(mask, 2));
		return {factory->newNewExpression(expression, typeArguments, arguments),
		        nullptr};
	}
	case Kind::MetaProperty: {
		Kind keywordToken = Kind::ImportKeyword;
		if ((commonData & 1) != 0) {
			keywordToken = Kind::NewKeyword;
		}
		return {factory->newMetaProperty(keywordToken,
		                                 singleChild(childIndices)),
		        nullptr};
	}
	case Kind::NonNullExpression:
		return {factory->newNonNullExpression(singleChild(childIndices),
		                                      NodeFlagsNone),
		        nullptr};
	case Kind::SpreadElement:
		return {factory->newSpreadElement(singleChild(childIndices)), nullptr};
	case Kind::TemplateExpression: {
		childIterator it{childIndices, 0};
		Node* head = nodeAt(it.nextIf(mask, 0));
		NodeList* templateSpans = nodeListAt(it.nextIf(mask, 1));
		return {factory->newTemplateExpression(head, templateSpans), nullptr};
	}
	case Kind::TemplateSpan: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		Node* literal = nodeAt(it.nextIf(mask, 1));
		return {factory->newTemplateSpan(expression, literal), nullptr};
	}
	case Kind::TaggedTemplateExpression: {
		childIterator it{childIndices, 0};
		Node* tag = nodeAt(it.nextIf(mask, 0));
		Node* questionDotToken = nodeAt(it.nextIf(mask, 1));
		NodeList* typeArguments = nodeListAt(it.nextIf(mask, 2));
		Node* template_ = nodeAt(it.nextIf(mask, 3));
		return {factory->newTaggedTemplateExpression(tag, questionDotToken,
		                                             typeArguments, template_,
		                                             NodeFlagsNone),
		        nullptr};
	}
	case Kind::ParenthesizedExpression:
		return {factory->newParenthesizedExpression(singleChild(childIndices)),
		        nullptr};
	case Kind::ArrayLiteralExpression: {
		bool multiLine = (commonData & 1) != 0;
		NodeList* list = nullptr;
		if (!childIndices.empty()) {
			list = nodeListAt(childIndices[0]);
		}
		return {factory->newArrayLiteralExpression(list, multiLine), nullptr};
	}
	case Kind::ObjectLiteralExpression: {
		bool multiLine = (commonData & 1) != 0;
		NodeList* list = nullptr;
		if (!childIndices.empty()) {
			list = nodeListAt(childIndices[0]);
		}
		return {factory->newObjectLiteralExpression(list, multiLine), nullptr};
	}
	case Kind::SpreadAssignment:
		return {factory->newSpreadAssignment(singleChild(childIndices)),
		        nullptr};
	case Kind::PropertyAssignment: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		Node* postfixToken = nodeAt(it.nextIf(mask, 2));
		Node* typeNode = nodeAt(it.nextIf(mask, 3));
		Node* initializer = nodeAt(it.nextIf(mask, 4));
		return {factory->newPropertyAssignment(modifiers, name, postfixToken,
		                                       typeNode, initializer),
		        nullptr};
	}
	case Kind::ShorthandPropertyAssignment: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		Node* postfixToken = nodeAt(it.nextIf(mask, 2));
		Node* typeNode = nodeAt(it.nextIf(mask, 3));
		Node* equalsToken = nodeAt(it.nextIf(mask, 4));
		Node* objectAssignmentInitializer = nodeAt(it.nextIf(mask, 5));
		return {factory->newShorthandPropertyAssignment(
		            modifiers, name, postfixToken, typeNode, equalsToken,
		            objectAssignmentInitializer),
		        nullptr};
	}
	case Kind::DeleteExpression:
		return {factory->newDeleteExpression(singleChild(childIndices)),
		        nullptr};
	case Kind::TypeOfExpression:
		return {factory->newTypeOfExpression(singleChild(childIndices)),
		        nullptr};
	case Kind::VoidExpression:
		return {factory->newVoidExpression(singleChild(childIndices)), nullptr};
	case Kind::AwaitExpression:
		return {factory->newAwaitExpression(singleChild(childIndices)),
		        nullptr};
	case Kind::TypeAssertionExpression: {
		childIterator it{childIndices, 0};
		Node* typeNode = nodeAt(it.nextIf(mask, 0));
		Node* expression = nodeAt(it.nextIf(mask, 1));
		return {factory->newTypeAssertion(typeNode, expression), nullptr};
	}
	case Kind::VoidKeyword:
	case Kind::AnyKeyword:
	case Kind::BooleanKeyword:
	case Kind::IntrinsicKeyword:
	case Kind::NeverKeyword:
	case Kind::NumberKeyword:
	case Kind::ObjectKeyword:
	case Kind::StringKeyword:
	case Kind::SymbolKeyword:
	case Kind::UndefinedKeyword:
	case Kind::UnknownKeyword:
	case Kind::BigIntKeyword:
		return {factory->newKeywordTypeNode(kind), nullptr};
	case Kind::UnionType:
		return {factory->newUnionTypeNode(singleNodeListChild(childIndices)),
		        nullptr};
	case Kind::IntersectionType:
		return {factory->newIntersectionTypeNode(
		            singleNodeListChild(childIndices)),
		        nullptr};
	case Kind::ConditionalType: {
		childIterator it{childIndices, 0};
		Node* checkType = nodeAt(it.nextIf(mask, 0));
		Node* extendsType = nodeAt(it.nextIf(mask, 1));
		Node* trueType = nodeAt(it.nextIf(mask, 2));
		Node* falseType = nodeAt(it.nextIf(mask, 3));
		return {factory->newConditionalTypeNode(checkType, extendsType, trueType,
		                                        falseType),
		        nullptr};
	}
	case Kind::TypeOperator: {
		Kind operator_ = Kind::Unknown;
		switch (commonData & 3) {
		case 0: operator_ = Kind::KeyOfKeyword; break;
		case 1: operator_ = Kind::ReadonlyKeyword; break;
		case 2: operator_ = Kind::UniqueKeyword; break;
		default: break;
		}
		return {factory->newTypeOperatorNode(operator_,
		                                     singleChild(childIndices)),
		        nullptr};
	}
	case Kind::InferType:
		return {factory->newInferTypeNode(singleChild(childIndices)), nullptr};
	case Kind::ArrayType:
		return {factory->newArrayTypeNode(singleChild(childIndices)), nullptr};
	case Kind::IndexedAccessType: {
		childIterator it{childIndices, 0};
		Node* objectType = nodeAt(it.nextIf(mask, 0));
		Node* indexType = nodeAt(it.nextIf(mask, 1));
		return {factory->newIndexedAccessTypeNode(objectType, indexType),
		        nullptr};
	}
	case Kind::TypeReference: {
		childIterator it{childIndices, 0};
		Node* typeName = nodeAt(it.nextIf(mask, 0));
		NodeList* typeArguments = nodeListAt(it.nextIf(mask, 1));
		return {factory->newTypeReferenceNode(typeName, typeArguments),
		        nullptr};
	}
	case Kind::ExpressionWithTypeArguments: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		NodeList* typeArguments = nodeListAt(it.nextIf(mask, 1));
		return {factory->newExpressionWithTypeArguments(expression,
		                                                typeArguments),
		        nullptr};
	}
	case Kind::LiteralType:
		return {factory->newLiteralTypeNode(singleChild(childIndices)),
		        nullptr};
	case Kind::ThisType:
		return {factory->newThisTypeNode(), nullptr};
	case Kind::TypePredicate: {
		childIterator it{childIndices, 0};
		Node* assertsModifier = nodeAt(it.nextIf(mask, 0));
		Node* parameterName = nodeAt(it.nextIf(mask, 1));
		Node* typeNode = nodeAt(it.nextIf(mask, 2));
		return {factory->newTypePredicateNode(assertsModifier, parameterName,
		                                      typeNode),
		        nullptr};
	}
	case Kind::ImportAttribute: {
		childIterator it{childIndices, 0};
		Node* name = nodeAt(it.nextIf(mask, 0));
		Node* value = nodeAt(it.nextIf(mask, 1));
		return {factory->newImportAttribute(name, value), nullptr};
	}
	case Kind::ImportAttributes: {
		bool multiLine = (commonData & 1) != 0;
		Kind token = Kind::WithKeyword;
		if (((commonData >> 1) & 1) != 0) {
			token = Kind::AssertKeyword;
		}
		NodeList* list = nullptr;
		if (!childIndices.empty()) {
			list = nodeListAt(childIndices[0]);
		}
		return {factory->newImportAttributes(token, list, multiLine), nullptr};
	}
	case Kind::TypeQuery: {
		childIterator it{childIndices, 0};
		Node* exprName = nodeAt(it.nextIf(mask, 0));
		NodeList* typeArguments = nodeListAt(it.nextIf(mask, 1));
		return {factory->newTypeQueryNode(exprName, typeArguments), nullptr};
	}
	case Kind::MappedType: {
		childIterator it{childIndices, 0};
		Node* readonlyToken = nodeAt(it.nextIf(mask, 0));
		Node* typeParameter = nodeAt(it.nextIf(mask, 1));
		Node* nameType = nodeAt(it.nextIf(mask, 2));
		Node* questionToken = nodeAt(it.nextIf(mask, 3));
		Node* typeNode = nodeAt(it.nextIf(mask, 4));
		NodeList* members = nodeListAt(it.nextIf(mask, 5));
		return {factory->newMappedTypeNode(readonlyToken, typeParameter,
		                                   nameType, questionToken, typeNode,
		                                   members),
		        nullptr};
	}
	case Kind::TypeLiteral:
		return {factory->newTypeLiteralNode(singleNodeListChild(childIndices)),
		        nullptr};
	case Kind::TupleType:
		return {factory->newTupleTypeNode(singleNodeListChild(childIndices)),
		        nullptr};
	case Kind::NamedTupleMember: {
		childIterator it{childIndices, 0};
		Node* dotDotDotToken = nodeAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		Node* questionToken = nodeAt(it.nextIf(mask, 2));
		Node* typeNode = nodeAt(it.nextIf(mask, 3));
		return {factory->newNamedTupleMember(dotDotDotToken, name, questionToken,
		                                     typeNode),
		        nullptr};
	}
	case Kind::OptionalType:
		return {factory->newOptionalTypeNode(singleChild(childIndices)),
		        nullptr};
	case Kind::RestType:
		return {factory->newRestTypeNode(singleChild(childIndices)), nullptr};
	case Kind::ParenthesizedType:
		return {factory->newParenthesizedTypeNode(singleChild(childIndices)),
		        nullptr};
	case Kind::FunctionType: {
		childIterator it{childIndices, 0};
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 0));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 1));
		Node* typeNode = nodeAt(it.nextIf(mask, 2));
		return {factory->newFunctionTypeNode(typeParameters, parameters,
		                                     typeNode),
		        nullptr};
	}
	case Kind::ConstructorType: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 1));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 2));
		Node* typeNode = nodeAt(it.nextIf(mask, 3));
		return {factory->newConstructorTypeNode(modifiers, typeParameters,
		                                        parameters, typeNode),
		        nullptr};
	}
	case Kind::TemplateLiteralType: {
		childIterator it{childIndices, 0};
		Node* head = nodeAt(it.nextIf(mask, 0));
		NodeList* templateSpans = nodeListAt(it.nextIf(mask, 1));
		return {factory->newTemplateLiteralTypeNode(head, templateSpans),
		        nullptr};
	}
	case Kind::TemplateLiteralTypeSpan: {
		childIterator it{childIndices, 0};
		Node* typeNode = nodeAt(it.nextIf(mask, 0));
		Node* literal = nodeAt(it.nextIf(mask, 1));
		return {factory->newTemplateLiteralTypeSpan(typeNode, literal),
		        nullptr};
	}
	case Kind::SyntheticExpression: {
		auto [typeNode, isSpread] =
		    decodeNodeCommonData_SyntheticExpression(commonData);
		return {factory->newSyntheticExpression(typeNode, isSpread,
		                                        singleChild(childIndices)),
		        nullptr};
	}
	case Kind::PartiallyEmittedExpression:
		return {factory->newPartiallyEmittedExpression(
		            singleChild(childIndices)),
		        nullptr};
	case Kind::JsxElement: {
		childIterator it{childIndices, 0};
		Node* openingElement = nodeAt(it.nextIf(mask, 0));
		NodeList* children = nodeListAt(it.nextIf(mask, 1));
		Node* closingElement = nodeAt(it.nextIf(mask, 2));
		return {factory->newJsxElement(openingElement, children, closingElement),
		        nullptr};
	}
	case Kind::JsxAttributes:
		return {factory->newJsxAttributes(singleNodeListChild(childIndices)),
		        nullptr};
	case Kind::JsxNamespacedName: {
		childIterator it{childIndices, 0};
		Node* namespace_ = nodeAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		return {factory->newJsxNamespacedName(namespace_, name), nullptr};
	}
	case Kind::JsxOpeningElement: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		NodeList* typeArguments = nodeListAt(it.nextIf(mask, 1));
		Node* attributes = nodeAt(it.nextIf(mask, 2));
		return {factory->newJsxOpeningElement(tagName, typeArguments,
		                                      attributes),
		        nullptr};
	}
	case Kind::JsxSelfClosingElement: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		NodeList* typeArguments = nodeListAt(it.nextIf(mask, 1));
		Node* attributes = nodeAt(it.nextIf(mask, 2));
		return {factory->newJsxSelfClosingElement(tagName, typeArguments,
		                                          attributes),
		        nullptr};
	}
	case Kind::JsxFragment: {
		childIterator it{childIndices, 0};
		Node* openingFragment = nodeAt(it.nextIf(mask, 0));
		NodeList* children = nodeListAt(it.nextIf(mask, 1));
		Node* closingFragment = nodeAt(it.nextIf(mask, 2));
		return {factory->newJsxFragment(openingFragment, children,
		                                closingFragment),
		        nullptr};
	}
	case Kind::JsxOpeningFragment:
		return {factory->newJsxOpeningFragment(), nullptr};
	case Kind::JsxClosingFragment:
		return {factory->newJsxClosingFragment(), nullptr};
	case Kind::JsxAttribute: {
		childIterator it{childIndices, 0};
		Node* name = nodeAt(it.nextIf(mask, 0));
		Node* initializer = nodeAt(it.nextIf(mask, 1));
		return {factory->newJsxAttribute(name, initializer), nullptr};
	}
	case Kind::JsxSpreadAttribute:
		return {factory->newJsxSpreadAttribute(singleChild(childIndices)),
		        nullptr};
	case Kind::JsxClosingElement:
		return {factory->newJsxClosingElement(singleChild(childIndices)),
		        nullptr};
	case Kind::JsxExpression: {
		childIterator it{childIndices, 0};
		Node* dotDotDotToken = nodeAt(it.nextIf(mask, 0));
		Node* expression = nodeAt(it.nextIf(mask, 1));
		return {factory->newJsxExpression(dotDotDotToken, expression), nullptr};
	}
	case Kind::SyntaxList: {
		std::vector<Node*> nodes;
		nodes.resize(childIndices.size());
		for (size_t i = 0; i < childIndices.size(); i++) {
			nodes[i] = this->nodes[childIndices[i]];
		}
		return {factory->newSyntaxList(std::move(nodes)), nullptr};
	}
	case Kind::JSDoc: {
		childIterator it{childIndices, 0};
		NodeList* comment = nodeListAt(it.nextIf(mask, 0));
		NodeList* tags = nodeListAt(it.nextIf(mask, 1));
		return {factory->newJSDoc(comment, tags), nullptr};
	}
	case Kind::JSDocTypeExpression:
		return {factory->newJSDocTypeExpression(singleChild(childIndices)),
		        nullptr};
	case Kind::JSDocNonNullableType:
		return {factory->newJSDocNonNullableType(singleChild(childIndices)),
		        nullptr};
	case Kind::JSDocNullableType:
		return {factory->newJSDocNullableType(singleChild(childIndices)),
		        nullptr};
	case Kind::JSDocAllType:
		return {factory->newJSDocAllType(), nullptr};
	case Kind::JSDocVariadicType:
		return {factory->newJSDocVariadicType(singleChild(childIndices)),
		        nullptr};
	case Kind::JSDocOptionalType:
		return {factory->newJSDocOptionalType(singleChild(childIndices)),
		        nullptr};
	case Kind::JSDocTypeTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* typeExpression = nodeAt(it.nextIf(mask, 1));
		NodeList* comment = nodeListAt(it.nextIf(mask, 2));
		return {factory->newJSDocTypeTag(tagName, typeExpression, comment),
		        nullptr};
	}
	case Kind::JSDocUnknownTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		NodeList* comment = nodeListAt(it.nextIf(mask, 1));
		return {factory->newJSDocUnknownTag(tagName, comment), nullptr};
	}
	case Kind::JSDocTemplateTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* constraint = nodeAt(it.nextIf(mask, 1));
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 2));
		NodeList* comment = nodeListAt(it.nextIf(mask, 3));
		return {factory->newJSDocTemplateTag(tagName, constraint, typeParameters,
		                                    comment),
		        nullptr};
	}
	case Kind::JSDocReturnTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* typeExpression = nodeAt(it.nextIf(mask, 1));
		NodeList* comment = nodeListAt(it.nextIf(mask, 2));
		return {factory->newJSDocReturnTag(tagName, typeExpression, comment),
		        nullptr};
	}
	case Kind::JSDocPublicTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		NodeList* comment = nodeListAt(it.nextIf(mask, 1));
		return {factory->newJSDocPublicTag(tagName, comment), nullptr};
	}
	case Kind::JSDocPrivateTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		NodeList* comment = nodeListAt(it.nextIf(mask, 1));
		return {factory->newJSDocPrivateTag(tagName, comment), nullptr};
	}
	case Kind::JSDocProtectedTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		NodeList* comment = nodeListAt(it.nextIf(mask, 1));
		return {factory->newJSDocProtectedTag(tagName, comment), nullptr};
	}
	case Kind::JSDocReadonlyTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		NodeList* comment = nodeListAt(it.nextIf(mask, 1));
		return {factory->newJSDocReadonlyTag(tagName, comment), nullptr};
	}
	case Kind::JSDocOverrideTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		NodeList* comment = nodeListAt(it.nextIf(mask, 1));
		return {factory->newJSDocOverrideTag(tagName, comment), nullptr};
	}
	case Kind::JSDocDeprecatedTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		NodeList* comment = nodeListAt(it.nextIf(mask, 1));
		return {factory->newJSDocDeprecatedTag(tagName, comment), nullptr};
	}
	case Kind::JSDocSeeTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* nameExpression = nodeAt(it.nextIf(mask, 1));
		NodeList* comment = nodeListAt(it.nextIf(mask, 2));
		return {factory->newJSDocSeeTag(tagName, nameExpression, comment),
		        nullptr};
	}
	case Kind::JSDocImplementsTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* className = nodeAt(it.nextIf(mask, 1));
		NodeList* comment = nodeListAt(it.nextIf(mask, 2));
		return {factory->newJSDocImplementsTag(tagName, className, comment),
		        nullptr};
	}
	case Kind::JSDocAugmentsTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* className = nodeAt(it.nextIf(mask, 1));
		NodeList* comment = nodeListAt(it.nextIf(mask, 2));
		return {factory->newJSDocAugmentsTag(tagName, className, comment),
		        nullptr};
	}
	case Kind::JSDocSatisfiesTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* typeExpression = nodeAt(it.nextIf(mask, 1));
		NodeList* comment = nodeListAt(it.nextIf(mask, 2));
		return {factory->newJSDocSatisfiesTag(tagName, typeExpression, comment),
		        nullptr};
	}
	case Kind::JSDocThrowsTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* typeExpression = nodeAt(it.nextIf(mask, 1));
		NodeList* comment = nodeListAt(it.nextIf(mask, 2));
		return {factory->newJSDocThrowsTag(tagName, typeExpression, comment),
		        nullptr};
	}
	case Kind::JSDocThisTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* typeExpression = nodeAt(it.nextIf(mask, 1));
		NodeList* comment = nodeListAt(it.nextIf(mask, 2));
		return {factory->newJSDocThisTag(tagName, typeExpression, comment),
		        nullptr};
	}
	case Kind::JSDocImportTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* importClause = nodeAt(it.nextIf(mask, 1));
		Node* moduleSpecifier = nodeAt(it.nextIf(mask, 2));
		Node* attributes = nodeAt(it.nextIf(mask, 3));
		NodeList* comment = nodeListAt(it.nextIf(mask, 4));
		return {factory->newJSDocImportTag(tagName, importClause,
		                                 moduleSpecifier, attributes, comment),
		        nullptr};
	}
	case Kind::JSDocCallbackTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* typeExpression = nodeAt(it.nextIf(mask, 1));
		Node* name = nodeAt(it.nextIf(mask, 2));
		NodeList* comment = nodeListAt(it.nextIf(mask, 3));
		return {factory->newJSDocCallbackTag(tagName, typeExpression, name,
		                                    comment),
		        nullptr};
	}
	case Kind::JSDocOverloadTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* typeExpression = nodeAt(it.nextIf(mask, 1));
		NodeList* comment = nodeListAt(it.nextIf(mask, 2));
		return {factory->newJSDocOverloadTag(tagName, typeExpression, comment),
		        nullptr};
	}
	case Kind::JSDocTypedefTag: {
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* typeExpression = nodeAt(it.nextIf(mask, 1));
		Node* name = nodeAt(it.nextIf(mask, 2));
		NodeList* comment = nodeListAt(it.nextIf(mask, 3));
		return {factory->newJSDocTypedefTag(tagName, typeExpression, name,
		                                   comment),
		        nullptr};
	}
	case Kind::JSDocSignature: {
		childIterator it{childIndices, 0};
		NodeList* typeParameters = nodeListAt(it.nextIf(mask, 0));
		NodeList* parameters = nodeListAt(it.nextIf(mask, 1));
		Node* typeNode = nodeAt(it.nextIf(mask, 2));
		return {factory->newJSDocSignature(typeParameters, parameters,
		                                   typeNode),
		        nullptr};
	}
	case Kind::JSDocNameReference:
		return {factory->newJSDocNameReference(singleChild(childIndices)),
		        nullptr};
	case Kind::ModuleDeclaration: {
		Kind keyword = Kind::ModuleKeyword;
		if ((commonData & 1) != 0) {
			keyword = Kind::NamespaceKeyword;
		}
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		Node* attributes = nodeAt(it.nextIf(mask, 2));
		Node* body = nodeAt(it.nextIf(mask, 3));
		return {factory->newModuleDeclaration(modifiers, keyword, name,
		                                      attributes, body),
		        nullptr};
	}
	case Kind::ImportEqualsDeclaration: {
		bool isTypeOnly = (commonData & 1) != 0;
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		Node* moduleReference = nodeAt(it.nextIf(mask, 2));
		return {factory->newImportEqualsDeclaration(modifiers, isTypeOnly, name,
		                                            moduleReference),
		        nullptr};
	}
	case Kind::ExportDeclaration: {
		bool isTypeOnly = (commonData & 1) != 0;
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* exportClause = nodeAt(it.nextIf(mask, 1));
		Node* moduleSpecifier = nodeAt(it.nextIf(mask, 2));
		Node* attributes = nodeAt(it.nextIf(mask, 3));
		return {factory->newExportDeclaration(modifiers, isTypeOnly,
		                                      exportClause, moduleSpecifier,
		                                      attributes),
		        nullptr};
	}
	case Kind::ImportType: {
		bool isTypeOf = (commonData & 1) != 0;
		childIterator it{childIndices, 0};
		Node* argument = nodeAt(it.nextIf(mask, 0));
		Node* attributes = nodeAt(it.nextIf(mask, 1));
		Node* qualifier = nodeAt(it.nextIf(mask, 2));
		NodeList* typeArguments = nodeListAt(it.nextIf(mask, 3));
		return {factory->newImportTypeNode(isTypeOf, argument, attributes,
		                                   qualifier, typeArguments),
		        nullptr};
	}
	case Kind::ImportClause: {
		Kind phaseModifier = Kind::Unknown;
		switch (commonData & 3) {
		case 1: phaseModifier = Kind::TypeKeyword; break;
		case 2: phaseModifier = Kind::DeferKeyword; break;
		default: break;
		}
		childIterator it{childIndices, 0};
		Node* name = nodeAt(it.nextIf(mask, 0));
		Node* namedBindings = nodeAt(it.nextIf(mask, 1));
		return {factory->newImportClause(phaseModifier, name, namedBindings),
		        nullptr};
	}
	case Kind::ImportSpecifier: {
		bool isTypeOnly = (commonData & 1) != 0;
		childIterator it{childIndices, 0};
		Node* propertyName = nodeAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		return {factory->newImportSpecifier(isTypeOnly, propertyName, name),
		        nullptr};
	}
	case Kind::TypeParameter: {
		childIterator it{childIndices, 0};
		ModifierList* modifiers = modifierListAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		Node* constraint = nodeAt(it.nextIf(mask, 2));
		Node* expression = nodeAt(it.nextIf(mask, 3));
		Node* defaultType = nodeAt(it.nextIf(mask, 4));
		return {factory->newTypeParameterDeclaration(modifiers, name,
		                                             constraint, expression,
		                                             defaultType),
		        nullptr};
	}
	case Kind::SyntheticReferenceExpression: {
		childIterator it{childIndices, 0};
		Node* expression = nodeAt(it.nextIf(mask, 0));
		Node* thisArg = nodeAt(it.nextIf(mask, 1));
		return {factory->newSyntheticReferenceExpression(expression, thisArg),
		        nullptr};
	}
	case Kind::JSDocTypeLiteral: {
		bool isArrayType = (commonData & 1) != 0;
		std::vector<Node*> nodes;
		nodes.resize(childIndices.size());
		for (size_t i = 0; i < childIndices.size(); i++) {
			nodes[i] = this->nodes[childIndices[i]];
		}
		return {factory->newJSDocTypeLiteral(std::move(nodes), isArrayType),
		        nullptr};
	}
	case Kind::JSDocParameterTag:
	case Kind::JSDocPropertyTag: {
		bool isBracketed = (commonData & 1) != 0;
		bool isNameFirst = (commonData & 2) != 0;
		childIterator it{childIndices, 0};
		Node* tagName = nodeAt(it.nextIf(mask, 0));
		Node* name = nodeAt(it.nextIf(mask, 1));
		Node* typeExpression = nodeAt(it.nextIf(mask, 2));
		NodeList* comment = nodeListAt(it.nextIf(mask, 3));
		return {factory->newJSDocParameterOrPropertyTag(kind, tagName, name,
		                                                isBracketed,
		                                                typeExpression,
		                                                isNameFirst, comment),
		        nullptr};
	}
	default:
		return {nullptr,
		        gostd::errorf("unhandled node kind %d with %d children",
		                      {static_cast<int>(kind),
		                       static_cast<int64_t>(childIndices.size())})};
	}
}

}  // namespace tsc::api::encoder
