// Code generated by tools/scripts/tsc/generate-encoder.ts. DO NOT EDIT.
// (Ported output of encoder_generated.go — keep in sync with the generator.)

#include "internal/api/encoder/encoder_internal.h"

namespace tsc::api::encoder {

uint32_t getNodeDataType(Node* node) {
	switch (node->kind) {
	case Kind::Identifier:
	case Kind::PrivateIdentifier:
	case Kind::JsxText:
	case Kind::JSDocText:
	case Kind::JSDocLink:
	case Kind::JSDocLinkPlain:
	case Kind::JSDocLinkCode:
		return NodeDataTypeString;
	case Kind::StringLiteral:
	case Kind::NumericLiteral:
	case Kind::BigIntLiteral:
	case Kind::RegularExpressionLiteral:
	case Kind::NoSubstitutionTemplateLiteral:
	case Kind::TemplateHead:
	case Kind::TemplateMiddle:
	case Kind::TemplateTail:
	case Kind::SourceFile:
		return NodeDataTypeExtendedData;
	default:
		return NodeDataTypeChildren;
	}
}

uint8_t getChildrenPropertyMask(Node* node) {
	switch (node->kind) {
	case Kind::QualifiedName: {
		auto* n = node->as<QualifiedName>();
		return (boolToByte(n->Left != nullptr) << 0) |
		       (boolToByte(n->Right != nullptr) << 1);
	}
	case Kind::ComputedPropertyName: {
		auto* n = node->as<ComputedPropertyName>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::Decorator: {
		auto* n = node->as<Decorator>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::IfStatement: {
		auto* n = node->as<IfStatement>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->ThenStatement != nullptr) << 1) |
		       (boolToByte(n->ElseStatement != nullptr) << 2);
	}
	case Kind::DoStatement: {
		auto* n = node->as<DoStatement>();
		return (boolToByte(n->Statement != nullptr) << 0) |
		       (boolToByte(n->Expression != nullptr) << 1);
	}
	case Kind::WhileStatement: {
		auto* n = node->as<WhileStatement>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->Statement != nullptr) << 1);
	}
	case Kind::ForStatement: {
		auto* n = node->as<ForStatement>();
		return (boolToByte(n->Initializer != nullptr) << 0) |
		       (boolToByte(n->Condition != nullptr) << 1) |
		       (boolToByte(n->Incrementor != nullptr) << 2) |
		       (boolToByte(n->Statement != nullptr) << 3);
	}
	case Kind::ForInStatement:
	case Kind::ForOfStatement: {
		auto* n = node->as<ForInOrOfStatement>();
		return (boolToByte(n->AwaitModifier != nullptr) << 0) |
		       (boolToByte(n->Initializer != nullptr) << 1) |
		       (boolToByte(n->Expression != nullptr) << 2) |
		       (boolToByte(n->Statement != nullptr) << 3);
	}
	case Kind::BreakStatement: {
		auto* n = node->as<BreakStatement>();
		return (boolToByte(n->Label != nullptr) << 0);
	}
	case Kind::ContinueStatement: {
		auto* n = node->as<ContinueStatement>();
		return (boolToByte(n->Label != nullptr) << 0);
	}
	case Kind::ReturnStatement: {
		auto* n = node->as<ReturnStatement>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::WithStatement: {
		auto* n = node->as<WithStatement>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->Statement != nullptr) << 1);
	}
	case Kind::SwitchStatement: {
		auto* n = node->as<SwitchStatement>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->CaseBlock != nullptr) << 1);
	}
	case Kind::CaseBlock: {
		auto* n = node->as<CaseBlock>();
		return (boolToByte(n->Clauses != nullptr) << 0);
	}
	case Kind::CaseClause:
	case Kind::DefaultClause: {
		auto* n = node->as<CaseOrDefaultClause>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->Statements != nullptr) << 1);
	}
	case Kind::ThrowStatement: {
		auto* n = node->as<ThrowStatement>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::TryStatement: {
		auto* n = node->as<TryStatement>();
		return (boolToByte(n->TryBlock != nullptr) << 0) |
		       (boolToByte(n->CatchClause != nullptr) << 1) |
		       (boolToByte(n->FinallyBlock != nullptr) << 2);
	}
	case Kind::CatchClause: {
		auto* n = node->as<CatchClause>();
		return (boolToByte(n->VariableDeclaration != nullptr) << 0) |
		       (boolToByte(n->Block != nullptr) << 1);
	}
	case Kind::LabeledStatement: {
		auto* n = node->as<LabeledStatement>();
		return (boolToByte(n->Label != nullptr) << 0) |
		       (boolToByte(n->Statement != nullptr) << 1);
	}
	case Kind::ExpressionStatement: {
		auto* n = node->as<ExpressionStatement>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::Block: {
		auto* n = node->as<Block>();
		return (boolToByte(n->Statements != nullptr) << 0);
	}
	case Kind::VariableStatement: {
		auto* n = node->as<VariableStatement>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->DeclarationList != nullptr) << 1);
	}
	case Kind::VariableDeclaration: {
		auto* n = node->as<VariableDeclaration>();
		return (boolToByte(n->name != nullptr) << 0) |
		       (boolToByte(n->ExclamationToken != nullptr) << 1) |
		       (boolToByte(n->Type != nullptr) << 2) |
		       (boolToByte(n->Initializer != nullptr) << 3);
	}
	case Kind::VariableDeclarationList: {
		auto* n = node->as<VariableDeclarationList>();
		return (boolToByte(n->Declarations != nullptr) << 0);
	}
	case Kind::ObjectBindingPattern:
	case Kind::ArrayBindingPattern: {
		auto* n = node->as<BindingPattern>();
		return (boolToByte(n->Elements != nullptr) << 0);
	}
	case Kind::Parameter: {
		auto* n = node->as<ParameterDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->DotDotDotToken != nullptr) << 1) |
		       (boolToByte(n->name != nullptr) << 2) |
		       (boolToByte(n->QuestionToken != nullptr) << 3) |
		       (boolToByte(n->Type != nullptr) << 4) |
		       (boolToByte(n->Initializer != nullptr) << 5);
	}
	case Kind::BindingElement: {
		auto* n = node->as<BindingElement>();
		return (boolToByte(n->DotDotDotToken != nullptr) << 0) |
		       (boolToByte(n->PropertyName != nullptr) << 1) |
		       (boolToByte(n->name != nullptr) << 2) |
		       (boolToByte(n->Initializer != nullptr) << 3);
	}
	case Kind::MissingDeclaration: {
		auto* n = node->as<MissingDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0);
	}
	case Kind::FunctionDeclaration: {
		auto* n = node->as<FunctionDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->AsteriskToken != nullptr) << 1) |
		       (boolToByte(n->name != nullptr) << 2) |
		       (boolToByte(n->TypeParameters != nullptr) << 3) |
		       (boolToByte(n->Parameters != nullptr) << 4) |
		       (boolToByte(n->Type != nullptr) << 5) |
		       (boolToByte(n->Body != nullptr) << 6);
	}
	case Kind::ClassDeclaration: {
		auto* n = node->as<ClassDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->TypeParameters != nullptr) << 2) |
		       (boolToByte(n->HeritageClauses != nullptr) << 3) |
		       (boolToByte(n->Members != nullptr) << 4);
	}
	case Kind::ClassExpression: {
		auto* n = node->as<ClassExpression>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->TypeParameters != nullptr) << 2) |
		       (boolToByte(n->HeritageClauses != nullptr) << 3) |
		       (boolToByte(n->Members != nullptr) << 4);
	}
	case Kind::HeritageClause: {
		auto* n = node->as<HeritageClause>();
		return (boolToByte(n->Types != nullptr) << 0);
	}
	case Kind::InterfaceDeclaration: {
		auto* n = node->as<InterfaceDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->TypeParameters != nullptr) << 2) |
		       (boolToByte(n->HeritageClauses != nullptr) << 3) |
		       (boolToByte(n->Members != nullptr) << 4);
	}
	case Kind::TypeAliasDeclaration:
	case Kind::JSTypeAliasDeclaration: {
		auto* n = node->as<TypeAliasDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->TypeParameters != nullptr) << 2) |
		       (boolToByte(n->Type != nullptr) << 3);
	}
	case Kind::EnumMember: {
		auto* n = node->as<EnumMember>();
		return (boolToByte(n->name != nullptr) << 0) |
		       (boolToByte(n->Initializer != nullptr) << 1);
	}
	case Kind::EnumDeclaration: {
		auto* n = node->as<EnumDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->Members != nullptr) << 2);
	}
	case Kind::ModuleBlock: {
		auto* n = node->as<ModuleBlock>();
		return (boolToByte(n->Statements != nullptr) << 0);
	}
	case Kind::ImportDeclaration:
	case Kind::JSImportDeclaration: {
		auto* n = node->as<ImportDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->ImportClause != nullptr) << 1) |
		       (boolToByte(n->ModuleSpecifier != nullptr) << 2) |
		       (boolToByte(n->Attributes != nullptr) << 3);
	}
	case Kind::ExternalModuleReference: {
		auto* n = node->as<ExternalModuleReference>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::NamespaceImport: {
		auto* n = node->as<NamespaceImport>();
		return (boolToByte(n->name != nullptr) << 0);
	}
	case Kind::NamedImports: {
		auto* n = node->as<NamedImports>();
		return (boolToByte(n->Elements != nullptr) << 0);
	}
	case Kind::ExportAssignment: {
		auto* n = node->as<ExportAssignment>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->Type != nullptr) << 1) |
		       (boolToByte(n->Expression != nullptr) << 2);
	}
	case Kind::NamespaceExportDeclaration: {
		auto* n = node->as<NamespaceExportDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1);
	}
	case Kind::NamespaceExport: {
		auto* n = node->as<NamespaceExport>();
		return (boolToByte(n->name != nullptr) << 0);
	}
	case Kind::NamedExports: {
		auto* n = node->as<NamedExports>();
		return (boolToByte(n->Elements != nullptr) << 0);
	}
	case Kind::ExportSpecifier: {
		auto* n = node->as<ExportSpecifier>();
		return (boolToByte(n->PropertyName != nullptr) << 0) |
		       (boolToByte(n->name != nullptr) << 1);
	}
	case Kind::CallSignature: {
		auto* n = node->as<CallSignatureDeclaration>();
		return (boolToByte(n->TypeParameters != nullptr) << 0) |
		       (boolToByte(n->Parameters != nullptr) << 1) |
		       (boolToByte(n->Type != nullptr) << 2);
	}
	case Kind::ConstructSignature: {
		auto* n = node->as<ConstructSignatureDeclaration>();
		return (boolToByte(n->TypeParameters != nullptr) << 0) |
		       (boolToByte(n->Parameters != nullptr) << 1) |
		       (boolToByte(n->Type != nullptr) << 2);
	}
	case Kind::Constructor: {
		auto* n = node->as<ConstructorDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->TypeParameters != nullptr) << 1) |
		       (boolToByte(n->Parameters != nullptr) << 2) |
		       (boolToByte(n->Type != nullptr) << 3) |
		       (boolToByte(n->Body != nullptr) << 4);
	}
	case Kind::GetAccessor: {
		auto* n = node->as<GetAccessorDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->TypeParameters != nullptr) << 2) |
		       (boolToByte(n->Parameters != nullptr) << 3) |
		       (boolToByte(n->Type != nullptr) << 4) |
		       (boolToByte(n->Body != nullptr) << 5);
	}
	case Kind::SetAccessor: {
		auto* n = node->as<SetAccessorDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->TypeParameters != nullptr) << 2) |
		       (boolToByte(n->Parameters != nullptr) << 3) |
		       (boolToByte(n->Type != nullptr) << 4) |
		       (boolToByte(n->Body != nullptr) << 5);
	}
	case Kind::IndexSignature: {
		auto* n = node->as<IndexSignatureDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->Parameters != nullptr) << 1) |
		       (boolToByte(n->Type != nullptr) << 2);
	}
	case Kind::MethodSignature: {
		auto* n = node->as<MethodSignatureDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->PostfixToken != nullptr) << 2) |
		       (boolToByte(n->TypeParameters != nullptr) << 3) |
		       (boolToByte(n->Parameters != nullptr) << 4) |
		       (boolToByte(n->Type != nullptr) << 5);
	}
	case Kind::MethodDeclaration: {
		auto* n = node->as<MethodDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->AsteriskToken != nullptr) << 1) |
		       (boolToByte(n->name != nullptr) << 2) |
		       (boolToByte(n->PostfixToken != nullptr) << 3) |
		       (boolToByte(n->TypeParameters != nullptr) << 4) |
		       (boolToByte(n->Parameters != nullptr) << 5) |
		       (boolToByte(n->Type != nullptr) << 6) |
		       (boolToByte(n->Body != nullptr) << 7);
	}
	case Kind::PropertySignature: {
		auto* n = node->as<PropertySignatureDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->PostfixToken != nullptr) << 2) |
		       (boolToByte(n->Type != nullptr) << 3) |
		       (boolToByte(n->Initializer != nullptr) << 4);
	}
	case Kind::PropertyDeclaration: {
		auto* n = node->as<PropertyDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->PostfixToken != nullptr) << 2) |
		       (boolToByte(n->Type != nullptr) << 3) |
		       (boolToByte(n->Initializer != nullptr) << 4);
	}
	case Kind::ClassStaticBlockDeclaration: {
		auto* n = node->as<ClassStaticBlockDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->Body != nullptr) << 1);
	}
	case Kind::BinaryExpression: {
		auto* n = node->as<BinaryExpression>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->Left != nullptr) << 1) |
		       (boolToByte(n->Type != nullptr) << 2) |
		       (boolToByte(n->OperatorToken != nullptr) << 3) |
		       (boolToByte(n->Right != nullptr) << 4);
	}
	case Kind::PrefixUnaryExpression: {
		auto* n = node->as<PrefixUnaryExpression>();
		return (boolToByte(n->Operand != nullptr) << 0);
	}
	case Kind::PostfixUnaryExpression: {
		auto* n = node->as<PostfixUnaryExpression>();
		return (boolToByte(n->Operand != nullptr) << 0);
	}
	case Kind::YieldExpression: {
		auto* n = node->as<YieldExpression>();
		return (boolToByte(n->AsteriskToken != nullptr) << 0) |
		       (boolToByte(n->Expression != nullptr) << 1);
	}
	case Kind::ArrowFunction: {
		auto* n = node->as<ArrowFunction>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->TypeParameters != nullptr) << 1) |
		       (boolToByte(n->Parameters != nullptr) << 2) |
		       (boolToByte(n->Type != nullptr) << 3) |
		       (boolToByte(n->EqualsGreaterThanToken != nullptr) << 4) |
		       (boolToByte(n->Body != nullptr) << 5);
	}
	case Kind::FunctionExpression: {
		auto* n = node->as<FunctionExpression>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->AsteriskToken != nullptr) << 1) |
		       (boolToByte(n->name != nullptr) << 2) |
		       (boolToByte(n->TypeParameters != nullptr) << 3) |
		       (boolToByte(n->Parameters != nullptr) << 4) |
		       (boolToByte(n->Type != nullptr) << 5) |
		       (boolToByte(n->Body != nullptr) << 6);
	}
	case Kind::AsExpression: {
		auto* n = node->as<AsExpression>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->Type != nullptr) << 1);
	}
	case Kind::SatisfiesExpression: {
		auto* n = node->as<SatisfiesExpression>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->Type != nullptr) << 1);
	}
	case Kind::ConditionalExpression: {
		auto* n = node->as<ConditionalExpression>();
		return (boolToByte(n->Condition != nullptr) << 0) |
		       (boolToByte(n->QuestionToken != nullptr) << 1) |
		       (boolToByte(n->WhenTrue != nullptr) << 2) |
		       (boolToByte(n->ColonToken != nullptr) << 3) |
		       (boolToByte(n->WhenFalse != nullptr) << 4);
	}
	case Kind::PropertyAccessExpression: {
		auto* n = node->as<PropertyAccessExpression>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->QuestionDotToken != nullptr) << 1) |
		       (boolToByte(n->name != nullptr) << 2);
	}
	case Kind::ElementAccessExpression: {
		auto* n = node->as<ElementAccessExpression>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->QuestionDotToken != nullptr) << 1) |
		       (boolToByte(n->ArgumentExpression != nullptr) << 2);
	}
	case Kind::CallExpression: {
		auto* n = node->as<CallExpression>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->QuestionDotToken != nullptr) << 1) |
		       (boolToByte(n->TypeArguments != nullptr) << 2) |
		       (boolToByte(n->Arguments != nullptr) << 3);
	}
	case Kind::NewExpression: {
		auto* n = node->as<NewExpression>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->TypeArguments != nullptr) << 1) |
		       (boolToByte(n->Arguments != nullptr) << 2);
	}
	case Kind::MetaProperty: {
		auto* n = node->as<MetaProperty>();
		return (boolToByte(n->name != nullptr) << 0);
	}
	case Kind::NonNullExpression: {
		auto* n = node->as<NonNullExpression>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::SpreadElement: {
		auto* n = node->as<SpreadElement>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::TemplateExpression: {
		auto* n = node->as<TemplateExpression>();
		return (boolToByte(n->Head != nullptr) << 0) |
		       (boolToByte(n->TemplateSpans != nullptr) << 1);
	}
	case Kind::TemplateSpan: {
		auto* n = node->as<TemplateSpan>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->Literal != nullptr) << 1);
	}
	case Kind::TaggedTemplateExpression: {
		auto* n = node->as<TaggedTemplateExpression>();
		return (boolToByte(n->Tag != nullptr) << 0) |
		       (boolToByte(n->QuestionDotToken != nullptr) << 1) |
		       (boolToByte(n->TypeArguments != nullptr) << 2) |
		       (boolToByte(n->Template != nullptr) << 3);
	}
	case Kind::ParenthesizedExpression: {
		auto* n = node->as<ParenthesizedExpression>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::ArrayLiteralExpression: {
		auto* n = node->as<ArrayLiteralExpression>();
		return (boolToByte(n->Elements != nullptr) << 0);
	}
	case Kind::ObjectLiteralExpression: {
		auto* n = node->as<ObjectLiteralExpression>();
		return (boolToByte(n->Properties != nullptr) << 0);
	}
	case Kind::SpreadAssignment: {
		auto* n = node->as<SpreadAssignment>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::PropertyAssignment: {
		auto* n = node->as<PropertyAssignment>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->PostfixToken != nullptr) << 2) |
		       (boolToByte(n->Type != nullptr) << 3) |
		       (boolToByte(n->Initializer != nullptr) << 4);
	}
	case Kind::ShorthandPropertyAssignment: {
		auto* n = node->as<ShorthandPropertyAssignment>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->PostfixToken != nullptr) << 2) |
		       (boolToByte(n->Type != nullptr) << 3) |
		       (boolToByte(n->EqualsToken != nullptr) << 4) |
		       (boolToByte(n->ObjectAssignmentInitializer != nullptr) << 5);
	}
	case Kind::DeleteExpression: {
		auto* n = node->as<DeleteExpression>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::TypeOfExpression: {
		auto* n = node->as<TypeOfExpression>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::VoidExpression: {
		auto* n = node->as<VoidExpression>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::AwaitExpression: {
		auto* n = node->as<AwaitExpression>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::TypeAssertionExpression: {
		auto* n = node->as<TypeAssertion>();
		return (boolToByte(n->Type != nullptr) << 0) |
		       (boolToByte(n->Expression != nullptr) << 1);
	}
	case Kind::UnionType: {
		auto* n = node->as<UnionTypeNode>();
		return (boolToByte(n->Types != nullptr) << 0);
	}
	case Kind::IntersectionType: {
		auto* n = node->as<IntersectionTypeNode>();
		return (boolToByte(n->Types != nullptr) << 0);
	}
	case Kind::ConditionalType: {
		auto* n = node->as<ConditionalTypeNode>();
		return (boolToByte(n->CheckType != nullptr) << 0) |
		       (boolToByte(n->ExtendsType != nullptr) << 1) |
		       (boolToByte(n->TrueType != nullptr) << 2) |
		       (boolToByte(n->FalseType != nullptr) << 3);
	}
	case Kind::TypeOperator: {
		auto* n = node->as<TypeOperatorNode>();
		return (boolToByte(n->Type != nullptr) << 0);
	}
	case Kind::InferType: {
		auto* n = node->as<InferTypeNode>();
		return (boolToByte(n->TypeParameter != nullptr) << 0);
	}
	case Kind::ArrayType: {
		auto* n = node->as<ArrayTypeNode>();
		return (boolToByte(n->ElementType != nullptr) << 0);
	}
	case Kind::IndexedAccessType: {
		auto* n = node->as<IndexedAccessTypeNode>();
		return (boolToByte(n->ObjectType != nullptr) << 0) |
		       (boolToByte(n->IndexType != nullptr) << 1);
	}
	case Kind::TypeReference: {
		auto* n = node->as<TypeReferenceNode>();
		return (boolToByte(n->TypeName != nullptr) << 0) |
		       (boolToByte(n->TypeArguments != nullptr) << 1);
	}
	case Kind::ExpressionWithTypeArguments: {
		auto* n = node->as<ExpressionWithTypeArguments>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->TypeArguments != nullptr) << 1);
	}
	case Kind::LiteralType: {
		auto* n = node->as<LiteralTypeNode>();
		return (boolToByte(n->Literal != nullptr) << 0);
	}
	case Kind::TypePredicate: {
		auto* n = node->as<TypePredicateNode>();
		return (boolToByte(n->AssertsModifier != nullptr) << 0) |
		       (boolToByte(n->ParameterName != nullptr) << 1) |
		       (boolToByte(n->Type != nullptr) << 2);
	}
	case Kind::ImportAttribute: {
		auto* n = node->as<ImportAttribute>();
		return (boolToByte(n->name != nullptr) << 0) |
		       (boolToByte(n->Value != nullptr) << 1);
	}
	case Kind::ImportAttributes: {
		auto* n = node->as<ImportAttributes>();
		return (boolToByte(n->Attributes != nullptr) << 0);
	}
	case Kind::TypeQuery: {
		auto* n = node->as<TypeQueryNode>();
		return (boolToByte(n->ExprName != nullptr) << 0) |
		       (boolToByte(n->TypeArguments != nullptr) << 1);
	}
	case Kind::MappedType: {
		auto* n = node->as<MappedTypeNode>();
		return (boolToByte(n->ReadonlyToken != nullptr) << 0) |
		       (boolToByte(n->TypeParameter != nullptr) << 1) |
		       (boolToByte(n->NameType != nullptr) << 2) |
		       (boolToByte(n->QuestionToken != nullptr) << 3) |
		       (boolToByte(n->Type != nullptr) << 4) |
		       (boolToByte(n->Members != nullptr) << 5);
	}
	case Kind::TypeLiteral: {
		auto* n = node->as<TypeLiteralNode>();
		return (boolToByte(n->Members != nullptr) << 0);
	}
	case Kind::TupleType: {
		auto* n = node->as<TupleTypeNode>();
		return (boolToByte(n->Elements != nullptr) << 0);
	}
	case Kind::NamedTupleMember: {
		auto* n = node->as<NamedTupleMember>();
		return (boolToByte(n->DotDotDotToken != nullptr) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->QuestionToken != nullptr) << 2) |
		       (boolToByte(n->Type != nullptr) << 3);
	}
	case Kind::OptionalType: {
		auto* n = node->as<OptionalTypeNode>();
		return (boolToByte(n->Type != nullptr) << 0);
	}
	case Kind::RestType: {
		auto* n = node->as<RestTypeNode>();
		return (boolToByte(n->Type != nullptr) << 0);
	}
	case Kind::ParenthesizedType: {
		auto* n = node->as<ParenthesizedTypeNode>();
		return (boolToByte(n->Type != nullptr) << 0);
	}
	case Kind::FunctionType: {
		auto* n = node->as<FunctionTypeNode>();
		return (boolToByte(n->TypeParameters != nullptr) << 0) |
		       (boolToByte(n->Parameters != nullptr) << 1) |
		       (boolToByte(n->Type != nullptr) << 2);
	}
	case Kind::ConstructorType: {
		auto* n = node->as<ConstructorTypeNode>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->TypeParameters != nullptr) << 1) |
		       (boolToByte(n->Parameters != nullptr) << 2) |
		       (boolToByte(n->Type != nullptr) << 3);
	}
	case Kind::TemplateLiteralType: {
		auto* n = node->as<TemplateLiteralTypeNode>();
		return (boolToByte(n->Head != nullptr) << 0) |
		       (boolToByte(n->TemplateSpans != nullptr) << 1);
	}
	case Kind::TemplateLiteralTypeSpan: {
		auto* n = node->as<TemplateLiteralTypeSpan>();
		return (boolToByte(n->Type != nullptr) << 0) |
		       (boolToByte(n->Literal != nullptr) << 1);
	}
	case Kind::SyntheticExpression: {
		auto* n = node->as<SyntheticExpression>();
		return (boolToByte(n->TupleNameSource != nullptr) << 0);
	}
	case Kind::PartiallyEmittedExpression: {
		auto* n = node->as<PartiallyEmittedExpression>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::JsxElement: {
		auto* n = node->as<JsxElement>();
		return (boolToByte(n->OpeningElement != nullptr) << 0) |
		       (boolToByte(n->Children != nullptr) << 1) |
		       (boolToByte(n->ClosingElement != nullptr) << 2);
	}
	case Kind::JsxAttributes: {
		auto* n = node->as<JsxAttributes>();
		return (boolToByte(n->Properties != nullptr) << 0);
	}
	case Kind::JsxNamespacedName: {
		auto* n = node->as<JsxNamespacedName>();
		return (boolToByte(n->Namespace != nullptr) << 0) |
		       (boolToByte(n->name != nullptr) << 1);
	}
	case Kind::JsxOpeningElement: {
		auto* n = node->as<JsxOpeningElement>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->TypeArguments != nullptr) << 1) |
		       (boolToByte(n->Attributes != nullptr) << 2);
	}
	case Kind::JsxSelfClosingElement: {
		auto* n = node->as<JsxSelfClosingElement>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->TypeArguments != nullptr) << 1) |
		       (boolToByte(n->Attributes != nullptr) << 2);
	}
	case Kind::JsxFragment: {
		auto* n = node->as<JsxFragment>();
		return (boolToByte(n->OpeningFragment != nullptr) << 0) |
		       (boolToByte(n->Children != nullptr) << 1) |
		       (boolToByte(n->ClosingFragment != nullptr) << 2);
	}
	case Kind::JsxAttribute: {
		auto* n = node->as<JsxAttribute>();
		return (boolToByte(n->name != nullptr) << 0) |
		       (boolToByte(n->Initializer != nullptr) << 1);
	}
	case Kind::JsxSpreadAttribute: {
		auto* n = node->as<JsxSpreadAttribute>();
		return (boolToByte(n->Expression != nullptr) << 0);
	}
	case Kind::JsxClosingElement: {
		auto* n = node->as<JsxClosingElement>();
		return (boolToByte(n->TagName != nullptr) << 0);
	}
	case Kind::JsxExpression: {
		auto* n = node->as<JsxExpression>();
		return (boolToByte(n->DotDotDotToken != nullptr) << 0) |
		       (boolToByte(n->Expression != nullptr) << 1);
	}
	case Kind::SyntaxList: {
		auto* n = node->as<SyntaxList>();
		return (boolToByte(!n->Children.empty()) << 0);
	}
	case Kind::JSDoc: {
		auto* n = node->as<JSDoc>();
		return (boolToByte(n->Comment != nullptr) << 0) |
		       (boolToByte(n->Tags != nullptr) << 1);
	}
	case Kind::JSDocTypeExpression: {
		auto* n = node->as<JSDocTypeExpression>();
		return (boolToByte(n->Type != nullptr) << 0);
	}
	case Kind::JSDocNonNullableType: {
		auto* n = node->as<JSDocNonNullableType>();
		return (boolToByte(n->Type != nullptr) << 0);
	}
	case Kind::JSDocNullableType: {
		auto* n = node->as<JSDocNullableType>();
		return (boolToByte(n->Type != nullptr) << 0);
	}
	case Kind::JSDocVariadicType: {
		auto* n = node->as<JSDocVariadicType>();
		return (boolToByte(n->Type != nullptr) << 0);
	}
	case Kind::JSDocOptionalType: {
		auto* n = node->as<JSDocOptionalType>();
		return (boolToByte(n->Type != nullptr) << 0);
	}
	case Kind::JSDocTypeTag: {
		auto* n = node->as<JSDocTypeTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->TypeExpression != nullptr) << 1) |
		       (boolToByte(n->Comment != nullptr) << 2);
	}
	case Kind::JSDocUnknownTag: {
		auto* n = node->as<JSDocUnknownTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->Comment != nullptr) << 1);
	}
	case Kind::JSDocTemplateTag: {
		auto* n = node->as<JSDocTemplateTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->Constraint != nullptr) << 1) |
		       (boolToByte(n->TypeParameters != nullptr) << 2) |
		       (boolToByte(n->Comment != nullptr) << 3);
	}
	case Kind::JSDocReturnTag: {
		auto* n = node->as<JSDocReturnTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->TypeExpression != nullptr) << 1) |
		       (boolToByte(n->Comment != nullptr) << 2);
	}
	case Kind::JSDocPublicTag: {
		auto* n = node->as<JSDocPublicTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->Comment != nullptr) << 1);
	}
	case Kind::JSDocPrivateTag: {
		auto* n = node->as<JSDocPrivateTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->Comment != nullptr) << 1);
	}
	case Kind::JSDocProtectedTag: {
		auto* n = node->as<JSDocProtectedTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->Comment != nullptr) << 1);
	}
	case Kind::JSDocReadonlyTag: {
		auto* n = node->as<JSDocReadonlyTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->Comment != nullptr) << 1);
	}
	case Kind::JSDocOverrideTag: {
		auto* n = node->as<JSDocOverrideTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->Comment != nullptr) << 1);
	}
	case Kind::JSDocDeprecatedTag: {
		auto* n = node->as<JSDocDeprecatedTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->Comment != nullptr) << 1);
	}
	case Kind::JSDocSeeTag: {
		auto* n = node->as<JSDocSeeTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->NameExpression != nullptr) << 1) |
		       (boolToByte(n->Comment != nullptr) << 2);
	}
	case Kind::JSDocImplementsTag: {
		auto* n = node->as<JSDocImplementsTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->ClassName != nullptr) << 1) |
		       (boolToByte(n->Comment != nullptr) << 2);
	}
	case Kind::JSDocAugmentsTag: {
		auto* n = node->as<JSDocAugmentsTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->ClassName != nullptr) << 1) |
		       (boolToByte(n->Comment != nullptr) << 2);
	}
	case Kind::JSDocSatisfiesTag: {
		auto* n = node->as<JSDocSatisfiesTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->TypeExpression != nullptr) << 1) |
		       (boolToByte(n->Comment != nullptr) << 2);
	}
	case Kind::JSDocThrowsTag: {
		auto* n = node->as<JSDocThrowsTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->TypeExpression != nullptr) << 1) |
		       (boolToByte(n->Comment != nullptr) << 2);
	}
	case Kind::JSDocThisTag: {
		auto* n = node->as<JSDocThisTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->TypeExpression != nullptr) << 1) |
		       (boolToByte(n->Comment != nullptr) << 2);
	}
	case Kind::JSDocImportTag: {
		auto* n = node->as<JSDocImportTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->ImportClause != nullptr) << 1) |
		       (boolToByte(n->ModuleSpecifier != nullptr) << 2) |
		       (boolToByte(n->Attributes != nullptr) << 3) |
		       (boolToByte(n->Comment != nullptr) << 4);
	}
	case Kind::JSDocCallbackTag: {
		auto* n = node->as<JSDocCallbackTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->TypeExpression != nullptr) << 1) |
		       (boolToByte(n->name != nullptr) << 2) |
		       (boolToByte(n->Comment != nullptr) << 3);
	}
	case Kind::JSDocOverloadTag: {
		auto* n = node->as<JSDocOverloadTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->TypeExpression != nullptr) << 1) |
		       (boolToByte(n->Comment != nullptr) << 2);
	}
	case Kind::JSDocTypedefTag: {
		auto* n = node->as<JSDocTypedefTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->TypeExpression != nullptr) << 1) |
		       (boolToByte(n->name != nullptr) << 2) |
		       (boolToByte(n->Comment != nullptr) << 3);
	}
	case Kind::JSDocSignature: {
		auto* n = node->as<JSDocSignature>();
		return (boolToByte(n->TypeParameters != nullptr) << 0) |
		       (boolToByte(n->Parameters != nullptr) << 1) |
		       (boolToByte(n->Type != nullptr) << 2);
	}
	case Kind::JSDocNameReference: {
		auto* n = node->as<JSDocNameReference>();
		return (boolToByte(n->name != nullptr) << 0);
	}
	case Kind::ModuleDeclaration: {
		auto* n = node->as<ModuleDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->Attributes != nullptr) << 2) |
		       (boolToByte(n->Body != nullptr) << 3);
	}
	case Kind::ImportEqualsDeclaration: {
		auto* n = node->as<ImportEqualsDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->ModuleReference != nullptr) << 2);
	}
	case Kind::ExportDeclaration: {
		auto* n = node->as<ExportDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->ExportClause != nullptr) << 1) |
		       (boolToByte(n->ModuleSpecifier != nullptr) << 2) |
		       (boolToByte(n->Attributes != nullptr) << 3);
	}
	case Kind::ImportType: {
		auto* n = node->as<ImportTypeNode>();
		return (boolToByte(n->Argument != nullptr) << 0) |
		       (boolToByte(n->Attributes != nullptr) << 1) |
		       (boolToByte(n->Qualifier != nullptr) << 2) |
		       (boolToByte(n->TypeArguments != nullptr) << 3);
	}
	case Kind::ImportClause: {
		auto* n = node->as<ImportClause>();
		return (boolToByte(n->name != nullptr) << 0) |
		       (boolToByte(n->NamedBindings != nullptr) << 1);
	}
	case Kind::ImportSpecifier: {
		auto* n = node->as<ImportSpecifier>();
		return (boolToByte(n->PropertyName != nullptr) << 0) |
		       (boolToByte(n->name != nullptr) << 1);
	}
	case Kind::JSDocLink: {
		auto* n = node->as<JSDocLink>();
		return (boolToByte(n->name != nullptr) << 0);
	}
	case Kind::JSDocLinkPlain: {
		auto* n = node->as<JSDocLinkPlain>();
		return (boolToByte(n->name != nullptr) << 0);
	}
	case Kind::JSDocLinkCode: {
		auto* n = node->as<JSDocLinkCode>();
		return (boolToByte(n->name != nullptr) << 0);
	}
	case Kind::TypeParameter: {
		auto* n = node->as<TypeParameterDeclaration>();
		return (boolToByte(hasModifiers(n->modifiers)) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->Constraint != nullptr) << 2) |
		       (boolToByte(n->Expression != nullptr) << 3) |
		       (boolToByte(n->DefaultType != nullptr) << 4);
	}
	case Kind::SyntheticReferenceExpression: {
		auto* n = node->as<SyntheticReferenceExpression>();
		return (boolToByte(n->Expression != nullptr) << 0) |
		       (boolToByte(n->ThisArg != nullptr) << 1);
	}
	case Kind::JSDocTypeLiteral: {
		auto* n = node->as<JSDocTypeLiteral>();
		return (boolToByte(!n->JSDocPropertyTags.empty()) << 0);
	}
	case Kind::JSDocParameterTag:
	case Kind::JSDocPropertyTag: {
		auto* n = node->as<JSDocParameterOrPropertyTag>();
		return (boolToByte(n->TagName != nullptr) << 0) |
		       (boolToByte(n->name != nullptr) << 1) |
		       (boolToByte(n->TypeExpression != nullptr) << 2) |
		       (boolToByte(n->Comment != nullptr) << 3);
	}
	default:
		return 0;
	}
}

uint32_t getNodeCommonData(Node* node) {
	switch (node->kind) {
	case Kind::Block: {
		auto* n = node->as<Block>();
		return static_cast<uint32_t>(boolToByte(n->MultiLine)) << 24;
	}
	case Kind::HeritageClause: {
		auto* n = node->as<HeritageClause>();
		uint32_t tokenIdx = 0;
		switch (n->Token) {
		case Kind::ImplementsKeyword:
			tokenIdx = 1;
		default: break;
		}
		return tokenIdx << 24;
	}
	case Kind::ExportAssignment: {
		auto* n = node->as<ExportAssignment>();
		return static_cast<uint32_t>(boolToByte(n->IsExportEquals)) << 24;
	}
	case Kind::ExportSpecifier: {
		auto* n = node->as<ExportSpecifier>();
		return static_cast<uint32_t>(boolToByte(n->IsTypeOnly)) << 24;
	}
	case Kind::PrefixUnaryExpression: {
		auto* n = node->as<PrefixUnaryExpression>();
		uint32_t operatorIdx = 0;
		switch (n->Operator) {
		case Kind::MinusToken: operatorIdx = 1; break;
		case Kind::TildeToken: operatorIdx = 2; break;
		case Kind::ExclamationToken: operatorIdx = 3; break;
		case Kind::PlusPlusToken: operatorIdx = 4; break;
		case Kind::MinusMinusToken: operatorIdx = 5; break;
		default: break;
		}
		return operatorIdx << 24;
	}
	case Kind::PostfixUnaryExpression: {
		auto* n = node->as<PostfixUnaryExpression>();
		uint32_t operatorIdx = 0;
		switch (n->Operator) {
		case Kind::MinusMinusToken: operatorIdx = 1; break;
		default: break;
		}
		return operatorIdx << 24;
	}
	case Kind::MetaProperty: {
		auto* n = node->as<MetaProperty>();
		uint32_t keywordTokenIdx = 0;
		switch (n->KeywordToken) {
		case Kind::NewKeyword: keywordTokenIdx = 1; break;
		default: break;
		}
		return keywordTokenIdx << 24;
	}
	case Kind::ArrayLiteralExpression: {
		auto* n = node->as<ArrayLiteralExpression>();
		return static_cast<uint32_t>(boolToByte(n->MultiLine)) << 24;
	}
	case Kind::ObjectLiteralExpression: {
		auto* n = node->as<ObjectLiteralExpression>();
		return static_cast<uint32_t>(boolToByte(n->MultiLine)) << 24;
	}
	case Kind::TypeOperator: {
		auto* n = node->as<TypeOperatorNode>();
		uint32_t operatorIdx = 0;
		switch (n->Operator) {
		case Kind::ReadonlyKeyword: operatorIdx = 1; break;
		case Kind::UniqueKeyword: operatorIdx = 2; break;
		default: break;
		}
		return operatorIdx << 24;
	}
	case Kind::ImportAttributes: {
		auto* n = node->as<ImportAttributes>();
		uint32_t tokenIdx = 0;
		switch (n->Token) {
		case Kind::AssertKeyword: tokenIdx = 1; break;
		default: break;
		}
		return static_cast<uint32_t>(boolToByte(n->MultiLine)) << 24 |
		       tokenIdx << 25;
	}
	case Kind::SyntheticExpression:
		return getNodeCommonData_SyntheticExpression(node);
	case Kind::JsxText: {
		auto* n = node->as<JsxText>();
		return static_cast<uint32_t>(boolToByte(
		                                 n->ContainsOnlyTriviaWhiteSpaces))
		       << 24;
	}
	case Kind::ModuleDeclaration: {
		auto* n = node->as<ModuleDeclaration>();
		uint32_t keywordIdx = 0;
		switch (n->Keyword) {
		case Kind::NamespaceKeyword: keywordIdx = 1; break;
		default: break;
		}
		return keywordIdx << 24;
	}
	case Kind::ImportEqualsDeclaration: {
		auto* n = node->as<ImportEqualsDeclaration>();
		return static_cast<uint32_t>(boolToByte(n->IsTypeOnly)) << 24;
	}
	case Kind::ExportDeclaration: {
		auto* n = node->as<ExportDeclaration>();
		return static_cast<uint32_t>(boolToByte(n->IsTypeOnly)) << 24;
	}
	case Kind::ImportType: {
		auto* n = node->as<ImportTypeNode>();
		return static_cast<uint32_t>(boolToByte(n->IsTypeOf)) << 24;
	}
	case Kind::ImportClause: {
		auto* n = node->as<ImportClause>();
		uint32_t phaseModifierIdx = 0;
		switch (n->PhaseModifier) {
		case Kind::TypeKeyword: phaseModifierIdx = 1; break;
		case Kind::DeferKeyword: phaseModifierIdx = 2; break;
		case Kind::SourceKeyword: phaseModifierIdx = 3; break;
		default: break;
		}
		return phaseModifierIdx << 24;
	}
	case Kind::ImportSpecifier: {
		auto* n = node->as<ImportSpecifier>();
		return static_cast<uint32_t>(boolToByte(n->IsTypeOnly)) << 24;
	}
	case Kind::JSDocTypeLiteral: {
		auto* n = node->as<JSDocTypeLiteral>();
		return static_cast<uint32_t>(boolToByte(n->IsArrayType)) << 24;
	}
	case Kind::JSDocParameterTag:
	case Kind::JSDocPropertyTag: {
		auto* n = node->as<JSDocParameterOrPropertyTag>();
		return static_cast<uint32_t>(boolToByte(n->IsBracketed)) << 24 |
		       static_cast<uint32_t>(boolToByte(n->IsNameFirst)) << 25;
	}
	default:
		break;
	}
	return 0;
}

// encoder.go:914 — forward decl; defined in encoder.cpp (hand-written).
uint32_t getNodeCommonData_SyntheticExpression(Node* node);

uint32_t recordNodeStrings(Node* node, stringTable* strs) {
	switch (node->kind) {
	case Kind::Identifier:
		return strs->add(node->as<Identifier>()->Text, node->kind, node->pos(),
		                 node->end());
	case Kind::PrivateIdentifier:
		return strs->add(node->as<PrivateIdentifier>()->Text, node->kind,
		                 node->pos(), node->end());
	case Kind::JsxText:
		return strs->add(node->as<JsxText>()->Text, node->kind, node->pos(),
		                 node->end());
	// JSDocCommentBase.Text() is Node::text() — joins the text parts.
	case Kind::JSDocText:
	case Kind::JSDocLink:
	case Kind::JSDocLinkPlain:
	case Kind::JSDocLinkCode:
		return strs->add(node->text(), node->kind, node->pos(), node->end());
	default:
		TSC_UNREACHABLE("unexpected node kind in recordNodeStrings");
	}
}

uint32_t recordExtendedData(Node* node, stringTable* strs,
                            PositionMap* positionMap,
                            std::vector<uint8_t>& extendedData,
                            std::vector<uint8_t>& structuredData) {
	uint32_t offset = static_cast<uint32_t>(extendedData.size());
	switch (node->kind) {
	case Kind::StringLiteral:
		recordExtendedData_StringLiteral(node, strs, positionMap, extendedData,
		                                 structuredData);
		break;
	case Kind::NumericLiteral:
		recordExtendedData_NumericLiteral(node, strs, positionMap, extendedData,
		                                  structuredData);
		break;
	case Kind::BigIntLiteral:
		recordExtendedData_BigIntLiteral(node, strs, positionMap, extendedData,
		                                 structuredData);
		break;
	case Kind::RegularExpressionLiteral:
		recordExtendedData_RegularExpressionLiteral(node, strs, positionMap,
		                                            extendedData, structuredData);
		break;
	case Kind::NoSubstitutionTemplateLiteral:
		recordExtendedData_NoSubstitutionTemplateLiteral(
		    node, strs, positionMap, extendedData, structuredData);
		break;
	case Kind::TemplateHead:
		recordExtendedData_TemplateHead(node, strs, positionMap, extendedData,
		                                structuredData);
		break;
	case Kind::TemplateMiddle:
		recordExtendedData_TemplateMiddle(node, strs, positionMap,
		                                  extendedData, structuredData);
		break;
	case Kind::TemplateTail:
		recordExtendedData_TemplateTail(node, strs, positionMap, extendedData,
		                                structuredData);
		break;
	case Kind::SourceFile:
		recordExtendedData_SourceFile(node, strs, positionMap, extendedData,
		                              structuredData);
		break;
	default:
		TSC_UNREACHABLE("unknown extended data node kind in recordExtendedData");
	}
	return offset;
}

}  // namespace tsc::api::encoder
