// project.go — Project + ID types + Kind/ProgramUpdateKind/PendingReload.
//
// project.h
#pragma once

#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

#include "internal/collections/collections.h"
#include "internal/compiler/program.h"
#include "internal/contentmapper/contentmapper.h"
#include "internal/core/types.h"
#include "internal/core/utilities.h"
#include "internal/gostd/gostd.h"
#include "internal/json/json.h"
#include "internal/module/resolver.h"
#include "internal/ls/crossproject.h" // ls::Project iface
#include "internal/project/ata/ata.h"
#include "internal/project/checkerpool.h"
#include "internal/project/watch.h"
#include "internal/tsoptions/tsoptions.h"
#include "internal/tspath/tspath.h"

namespace tsc::logging {
struct Logger;
struct LogTree;
} // namespace tsc::logging


namespace tsc::project {

// project.go:27-30 consts.
inline constexpr const char* inferredProjectName =
    "/dev/null/inferred"; // lowercase so toPath is a no-op regardless
                          // of settings
inline constexpr std::string_view syntheticProjectPrefix =
    "/dev/null/synthetic/";
inline constexpr const char* hr =
    "-----------------------------------------------";

// ID — project.go:32.
struct ID : std::string {
	using std::string::string;
	ID() = default;
	ID(const std::string& s) : std::string(s) {}
	ID(std::string_view s) : std::string(s) {}
};

// idString — (id ID) String(), project.go:53 (fmt.Stringer).
inline const std::string& idString(const ID& id) { return id; }

// ConfiguredProjectID — project.go:34.
struct ConfiguredProjectID : tspath::Path {
	using tspath::Path::Path;
	ConfiguredProjectID() = default;
	ConfiguredProjectID(const tspath::Path& p) : tspath::Path(p) {}

	// Path — project.go:36.
	tspath::Path Path() const { return *this; }
	// AsID — project.go:54.
	ID AsID() const { return ID(*this); }
};

// InferredProjectID — project.go:40.
struct InferredProjectID : std::string {
	using std::string::string;
	InferredProjectID() = default;
	InferredProjectID(const std::string& s) : std::string(s) {}
	InferredProjectID(std::string_view s) : std::string(s) {}

	// AsID — project.go:55.
	ID AsID() const { return ID(*this); }
};

// inferredProjectID — project.go:42.
inline const InferredProjectID inferredProjectID{inferredProjectName};

// SyntheticProjectID — project.go:44.
struct SyntheticProjectID : std::string {
	using std::string::string;
	SyntheticProjectID() = default;
	SyntheticProjectID(const std::string& s) : std::string(s) {}
	SyntheticProjectID(std::string_view s) : std::string(s) {}

	// AsID — project.go:56.
	ID AsID() const { return ID(*this); }

	// UnmarshalJSONFrom — project.go:84.
	gostd::Error UnmarshalJSONFrom(json::Decoder* dec);
};

// NewSyntheticProjectID — project.go:46.
inline SyntheticProjectID NewSyntheticProjectID(int id) {
	if (id <= 0) {
		TSC_UNREACHABLE("invalid synthetic project ID");
	}
	return SyntheticProjectID(std::string(syntheticProjectPrefix) +
	                          std::to_string(id));
}

// ParseSyntheticProjectID — project.go:97.
inline std::pair<SyntheticProjectID, bool>
ParseSyntheticProjectID(const std::string& value) {
	if (value.substr(0, syntheticProjectPrefix.size()) !=
	    syntheticProjectPrefix) {
		return {SyntheticProjectID(), false};
	}
	std::string suffix{value.substr(syntheticProjectPrefix.size())};
	int id = 0;
	try {
		size_t consumed = 0;
		id = std::stoi(suffix, &consumed);
		if (consumed != suffix.size()) {
			return {SyntheticProjectID(), false};
		}
	} catch (...) {
		return {SyntheticProjectID(), false};
	}
	if (id <= 0) {
		return {SyntheticProjectID(), false};
	}
	return {NewSyntheticProjectID(id), true};
}

// ParseConfiguredProjectID — project.go:62.
inline std::pair<ConfiguredProjectID, bool>
ParseConfiguredProjectID(const tspath::Path& value) {
	ID id{std::string(value)};
	if (id.empty()) {
		return {ConfiguredProjectID(), false};
	}
	if (id == inferredProjectID.AsID()) {
		return {ConfiguredProjectID(), false};
	}
	if (ParseSyntheticProjectID(id).second) {
		return {ConfiguredProjectID(), false};
	}
	return {ConfiguredProjectID(value), true};
}

// ID methods — project.go:58/76/80. Free functions to avoid the
// type-name/member-name shadow problem inside `struct ID`.
inline std::pair<ConfiguredProjectID, bool>
idConfigured(const ID& id) {
	return ParseConfiguredProjectID(tspath::Path(id));
}
inline std::pair<InferredProjectID, bool> idInferred(const ID& id) {
	return {inferredProjectID, id == inferredProjectID.AsID()};
}
inline std::pair<SyntheticProjectID, bool> idSynthetic(const ID& id) {
	return ParseSyntheticProjectID(id);
}

// Kind — project.go:111.
enum class Kind : int {
	Inferred = 0,
	Configured,
	Synthetic,
};
inline constexpr Kind KindInferred = Kind::Inferred;
inline constexpr Kind KindConfigured = Kind::Configured;
inline constexpr Kind KindSynthetic = Kind::Synthetic;

// Kind.String — project_stringer.go (generated by stringer).
inline std::string kindString(Kind k) {
	switch (k) {
	case Kind::Inferred:
		return "Inferred";
	case Kind::Configured:
		return "Configured";
	case Kind::Synthetic:
		return "Synthetic";
	}
	return "Kind(" + std::to_string(int(k)) + ")";
}

// ProgramUpdateKind — project.go:119.
enum class ProgramUpdateKind : int {
	None = 0,
	Cloned,
	SameFileNames,
	NewFiles,
};
inline constexpr ProgramUpdateKind ProgramUpdateKindNone =
    ProgramUpdateKind::None;
inline constexpr ProgramUpdateKind ProgramUpdateKindCloned =
    ProgramUpdateKind::Cloned;
inline constexpr ProgramUpdateKind ProgramUpdateKindSameFileNames =
    ProgramUpdateKind::SameFileNames;
inline constexpr ProgramUpdateKind ProgramUpdateKindNewFiles =
    ProgramUpdateKind::NewFiles;

// PendingReload — project.go:128.
enum class PendingReload : int {
	None = 0,
	FileNames,
	Full,
};
inline constexpr PendingReload PendingReloadNone = PendingReload::None;
inline constexpr PendingReload PendingReloadFileNames =
    PendingReload::FileNames;
inline constexpr PendingReload PendingReloadFull = PendingReload::Full;

struct ProjectCollectionBuilder;
struct compilerHost;
struct ProjectTreeRequest;
struct configuredProjectFactory;

// ModuleResolverFactory — snapshot.go:49. A factory for creating
// module resolvers along with a disposal function.
struct ModuleResolverFactory {
	virtual ~ModuleResolverFactory() = default;
	// NewResolver — returns (module.Resolver, dispose-func).
	virtual std::pair<module::Resolver*, std::function<void()>>
	NewResolver(const module::ResolverOptions& options) = 0;
};

// Project — project.go:138. If changing struct fields, also update
// the Clone method. Implements ls::Project (crossproject.go:17).
struct Project : ls::Project {
	project::Kind Kind = project::KindInferred;
	ID id;
	std::string currentDirectory;
	std::string configFileName;
	tspath::Path configFilePath;

	bool dirty = false;
	tspath::Path dirtyFilePath;

	compilerHost* host = nullptr;
	tsoptions::ParsedCommandLine* CommandLine = nullptr;
	tsoptions::ParsedCommandLine* commandLineWithTypingsFiles =
	    nullptr;
	std::once_flag commandLineWithTypingsFilesOnce;
	compiler::SimpleProgram* Program = nullptr;
	// The kind of update that was performed on the program last time
	// it was updated.
	project::ProgramUpdateKind ProgramUpdateKind =
	    project::ProgramUpdateKindNone;
	// The ID of the snapshot that created the program stored in this
	// project.
	uint64_t ProgramLastUpdate = 0;
	// Set of projects that this project could be referencing. Only
	// set before actually loading config file to get actual project
	// references.
	collections::Set<tspath::Path>* potentialProjectReferences =
	    nullptr;

	WatchedFiles<collections::SyncMap<tspath::Path, std::string>*>*
	    programFilesWatch = nullptr;
	WatchedFiles<PatternsAndIgnored>* typingsWatch = nullptr;
	WatchedFiles<std::vector<std::string>>* contentMapperWatch =
	    nullptr;
	collections::Set<tspath::Path>* contentMapperWatchedFiles =
	    nullptr;

	project::checkerPool* checkerPool = nullptr;

	ModuleResolverFactory* moduleResolverFactory = nullptr;
	uint64_t moduleResolverID = 0;

	// installedTypingsInfo is the value of
	// `project.ComputeTypingsInfo()` that was used during the most
	// recently completed typings installation.
	ata::TypingsInfo* installedTypingsInfo = nullptr;
	// typingsFiles are the root files added by the typings installer.
	std::vector<std::string> typingsFiles;

	// -------------------------------------------------------------------
	// project.go methods
	// -------------------------------------------------------------------

	// CurrentDirectory — project.go:312.
	const std::string& CurrentDirectory() const {
		return currentDirectory;
	}

	// DisplayName — project.go:320. A short, human-readable name for
	// the project, relative to the given workspace root directory.
	std::string DisplayName(const std::string& cwd) const;

	// ID — project.go:333.
	project::ID ID() const { return id; }
	// Id — ls::Project (crossproject.go:18) — same return as
	// project.go:353.
	std::string Id() const override { return std::string(id); }

	// ConfigFileName — project.go:338. Panics if not KindConfigured.
	const std::string& ConfigFileName() const;
	// ConfigFilePath — project.go:346. Panics if not KindConfigured.
	const tspath::Path& ConfigFilePath() const;

	// GetProgram — project.go:357.
	compiler::SimpleProgram* GetProgram() const override {
		return Program;
	}
	// IsDirty — project.go:361.
	bool IsDirty() const { return dirty; }

	// GetProjectDiagnostics — project.go:368. Program diagnostics
	// combined with any global diagnostics discovered during checking.
	// These are the diagnostics reported on the tsconfig.json file.
	std::vector<Diagnostic*> GetProjectDiagnostics();

	// HasFile — project.go:380.
	bool HasFile(const std::string& fileName) const override {
		return containsFile(toPath(fileName));
	}
	// containsFile — project.go:384.
	bool containsFile(const tspath::Path& path) const {
		return Program != nullptr &&
		       Program->GetSourceFileByPath(path) != nullptr;
	}
	// IsSourceFromProjectReference — project.go:388.
	bool IsSourceFromProjectReference(const tspath::Path& path) const {
		return Program != nullptr &&
		       Program->IsSourceFromProjectReference(path);
	}

	// Clone — project.go:392.
	Project* Clone() const;

	// SetCommandLine — project.go:433.
	void SetCommandLine(tsoptions::ParsedCommandLine* commandLine);

	// getCommandLineWithTypingsFiles — project.go:443. Returns the
	// command line augmented with typing files if ATA is enabled.
	tsoptions::ParsedCommandLine* getCommandLineWithTypingsFiles();

	// setPotentialProjectReference — project.go:468.
	void setPotentialProjectReference(const tspath::Path& configFilePath);
	// hasPotentialProjectReference — project.go:477.
	bool hasPotentialProjectReference(
	    const ProjectTreeRequest* projectTreeRequest) const;

	// CreateProgram — project.go:499.
	struct CreateProgramResult {
		compiler::SimpleProgram* Program = nullptr;
		project::ProgramUpdateKind UpdateKind =
		    project::ProgramUpdateKindNone;
	};
	CreateProgramResult CreateProgram();

	// CloneWatchers — project.go:593.
	WatchedFiles<collections::SyncMap<tspath::Path, std::string>*>* CloneWatchers();

	// toPath — project.go:601.
	tspath::Path toPath(const std::string& fileName) const;

	// log — project.go:597 (!!! — no-op in Go).
	void log(const std::string&) {}

	// print — project.go:605.
	std::string print(bool writeFileNames, bool writeFileExplanation);

	// GetTypeAcquisition — project.go:628. Type acquisition settings;
	// inferred and synthetic projects use defaults.
	::tsc::TypeAcquisition* GetTypeAcquisition() const;

	// GetUnresolvedImports — project.go:647.
	collections::Set<std::string>* GetUnresolvedImports();

	// ShouldTriggerATA — project.go:656.
	bool ShouldTriggerATA(uint64_t snapshotID);

	// ComputeTypingsInfo — project.go:675.
	ata::TypingsInfo ComputeTypingsInfo();
};

// NewConfiguredProject — project.go:180.
Project* NewConfiguredProject(const std::string& configFileName,
                              const tspath::Path& configFilePath,
                              ProjectCollectionBuilder* builder,
                              logging::LogTree* logger);

// NewInferredProject — project.go:196.
Project* NewInferredProject(
    const std::string& currentDirectory, CompilerOptions* compilerOptions,
    const std::vector<std::string>& rootFileNames,
    const std::vector<tsc::ProjectReference*>& projectReferences,
    const std::vector<contentmapper::Mapper*>& contentMappers,
    ProjectCollectionBuilder* builder, logging::LogTree* logger);

// newSyntheticProject — project.go:234.
Project* newSyntheticProject(
    SyntheticProjectID id, const std::string& currentDirectory,
    CompilerOptions* compilerOptions,
    const std::vector<std::string>& rootFileNames,
    const std::vector<tsc::ProjectReference*>& projectReferences,
    const std::vector<contentmapper::Mapper*>& contentMappers,
    ProjectCollectionBuilder* builder, logging::LogTree* logger);

// newInferredProjectCommandLine — project.go:258.
tsoptions::ParsedCommandLine* newInferredProjectCommandLine(
    CompilerOptions* compilerOptions,
    const std::vector<std::string>& rootFileNames,
    const std::vector<tsc::ProjectReference*>& projectReferences,
    const std::vector<contentmapper::Mapper*>& contentMappers,
    const tspath::ComparePathsOptions& comparePathsOptions);

// NewProject — project.go:270.
Project* NewProject(ID id, Kind kind,
                    const std::string& currentDirectory,
                    ProjectCollectionBuilder* builder,
                    logging::LogTree* logger);

} // namespace tsc::project

namespace std {
// hash specializations — the project ID types are std::string /
// tspath::Path subclasses; hash like their string values so unordered
// containers keyed by them work.
template <> struct hash<tsc::project::ID> {
	size_t operator()(const tsc::project::ID& id) const noexcept {
		return std::hash<std::string>{}(id);
	}
};
template <> struct hash<tsc::project::ConfiguredProjectID> {
	size_t operator()(const tsc::project::ConfiguredProjectID& id)
	    const noexcept {
		return std::hash<std::string>{}(id);
	}
};
template <> struct hash<tsc::project::InferredProjectID> {
	size_t operator()(const tsc::project::InferredProjectID& id)
	    const noexcept {
		return std::hash<std::string>{}(id);
	}
};
template <> struct hash<tsc::project::SyntheticProjectID> {
	size_t operator()(const tsc::project::SyntheticProjectID& id)
	    const noexcept {
		return std::hash<std::string>{}(id);
	}
};
} // namespace std
