// MessagePack protocol — protocol_msgpack.go. Custom msgpack-based tuple
// format: [MessageType, method, payload].
#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <string_view>

#include "internal/gostd/gostd.h"
#include "internal/ipc/ipc.h"
#include "internal/json/json.h"
#include "internal/jsonrpc/jsonrpc.h"

namespace tsc::api {

// MessageType represents the type of message in the msgpack protocol.
enum class MessageType : uint8_t {
	Unknown = 0,
	Request,
	CallResponse,
	CallError,
	Response,
	Error,
	Call,
};

constexpr bool IsValid(MessageType m) {
	return m >= MessageType::Request && m <= MessageType::Call;
}

// MessagePack format constants
inline constexpr uint8_t msgpackFixedArray3 = 0x93;
inline constexpr uint8_t msgpackBin8 = 0xC4;
inline constexpr uint8_t msgpackBin16 = 0xC5;
inline constexpr uint8_t msgpackBin32 = 0xC6;
inline constexpr uint8_t msgpackU8 = 0xCC;

// MessageType.String — stringer_generated.go (output ported faithfully;
// generated by `stringer -type=MessageType`).
std::string MessageTypeString(MessageType i);

// RawBinary is a marker type for binary data that should be written
// directly by MessagePackProtocol instead of being JSON-encoded.
using RawBinary = std::string;

// MessagePackProtocol implements the Protocol interface using a custom
// msgpack-based tuple format: [MessageType, method, payload].
class MessagePackProtocol : public ipc::Protocol {
	// NewMessagePackProtocol's shared_ptr<ReadWriteCloser> overload installs
	// ownedRw_.
	friend std::shared_ptr<MessagePackProtocol> NewMessagePackProtocol(
	    std::shared_ptr<gostd::io::ReadWriteCloser> rwc);
public:
	explicit MessagePackProtocol(gostd::io::ReadWriter* rw);

	std::pair<ipc::Message*, gostd::Error> ReadMessage() override;
	gostd::Error WriteRequest(const jsonrpc::ID* id, std::string_view method,
	                          const json::Value& params) override;
	gostd::Error WriteNotification(std::string_view method,
	                               const json::Value& params) override;
	gostd::Error WriteResponse(const jsonrpc::ID* id,
	                           const json::Value& result) override;
	gostd::Error WriteError(const jsonrpc::ID* id,
	                        const jsonrpc::ResponseError* err) override;

	// WriteResponseRaw handles the Go `result.(RawBinary)` dispatch — callers
	// that produce raw binary call this directly (Go type-asserts inside
	// WriteResponse; C++ splits it out since json::Value carries no tag).
	gostd::Error WriteResponseRaw(const jsonrpc::ID* id, const RawBinary& result);

private:
	gostd::io::ReadWriter* rw_;
	// ownedRw_ keeps the adapter alive when constructed from a
	// shared_ptr<ReadWriteCloser> (Go's io.ReadWriter arg).
	std::shared_ptr<gostd::io::ReadWriter> ownedRw_;
	// bufio equivalents (api/protocol_msgpack.cpp).
	struct BufReader;
	struct BufWriter;
	std::unique_ptr<BufReader> r;
	std::unique_ptr<BufWriter> w;

	// readTuple reads [msgType, method, payload].
	std::tuple<MessageType, std::string, std::string, gostd::Error> readTuple();
	// readBin reads a bin8/16/32 payload.
	std::pair<std::string, gostd::Error> readBin();
	gostd::Error writeTuple(MessageType msgType, std::string_view method,
	                        std::string_view payload);
	gostd::Error writeBin(std::string_view data);
};

// NewMessagePackProtocol creates a new msgpack protocol handler.
std::shared_ptr<MessagePackProtocol> NewMessagePackProtocol(
    gostd::io::ReadWriter* rw);
std::shared_ptr<MessagePackProtocol> NewMessagePackProtocol(
    std::shared_ptr<gostd::io::ReadWriteCloser> rwc);

}  // namespace tsc::api
