// MessagePack protocol — protocol_msgpack.go:1-281.
#include "internal/api/protocol_msgpack.h"

#include "internal/api/proto.h"

#include <cstdio>
#include <cstring>
#include <tuple>

namespace tsc::api {

// --- stringer_generated.go -------------------------------------------------
// MessageType.String — generated by `stringer -type=MessageType
// -output=stringer_generated.go`; output ported faithfully.
static const char _MessageType_name[] =
	"MessageTypeUnknownMessageTypeRequestMessageTypeCallResponseMessageTypeCallErrorMessageTypeResponseMessageTypeErrorMessageTypeCall";
static const uint8_t _MessageType_index[] = {0, 18, 36, 59, 79, 98, 114, 129};

std::string MessageTypeString(MessageType i) {
	int idx = static_cast<int>(i) - 0;
	if (static_cast<int>(i) < 0 || idx >= static_cast<int>(sizeof(_MessageType_index)) - 1) {
		return "MessageType(" + std::to_string(static_cast<int64_t>(i)) + ")";
	}
	return std::string(_MessageType_name + _MessageType_index[idx],
	                   _MessageType_index[idx + 1] - _MessageType_index[idx]);
}

// --- bufio.Reader/Writer equivalents ----------------------------------------

// BufReader — bufio.Reader over gostd::io::Reader.
struct MessagePackProtocol::BufReader {
	explicit BufReader(gostd::io::Reader* r) : r_(r) {}

	std::pair<uint8_t, gostd::Error> readByte() {
		if (pos_ >= buf_.size()) {
			if (auto err = fill(); err) return {0, err};
		}
		return {static_cast<uint8_t>(buf_[pos_++]), nullptr};
	}

	// readFull — io.ReadFull over the buffered reader: EOF when nothing was
	// read, ErrUnexpectedEOF on a partial read.
	gostd::Error readFull(std::string& out, size_t n) {
		size_t have = 0;
		while (have < n) {
			if (pos_ < buf_.size()) {
				size_t take = std::min(n - have, buf_.size() - pos_);
				out.append(buf_, pos_, take);
				pos_ += take;
				have += take;
				continue;
			}
			if (auto err = fill(); err) {
				return have == 0 ? err : gostd::io::errUnexpectedEOF;
			}
		}
		return nullptr;
	}

private:
	gostd::io::Reader* r_;
	std::string buf_;
	size_t pos_ = 0;

	gostd::Error fill() {
		char tmp[4096];
		auto [n, err] = r_->read({tmp, sizeof tmp});
		buf_.assign(tmp, n);
		pos_ = 0;
		if (err) return err;
		if (n == 0) return gostd::io::errEOF;
		return nullptr;
	}
};

// BufWriter — bufio.Writer over gostd::io::Writer. Writes accumulate until
// flush, matching bufio.Writer + explicit Flush in writeTuple.
struct MessagePackProtocol::BufWriter {
	explicit BufWriter(gostd::io::Writer* w) : w_(w) {}

	gostd::Error writeByte(uint8_t b) {
		buf_ += static_cast<char>(b);
		return nullptr;
	}
	gostd::Error write(std::string_view data) {
		buf_ += data;
		return nullptr;
	}
	gostd::Error flush() {
		if (buf_.empty()) return nullptr;
		std::string data = std::move(buf_);
		buf_.clear();
		size_t off = 0;
		while (off < data.size()) {
			auto [n, err] = w_->write(std::string_view(data).substr(off));
			if (err) return err;
			if (n <= 0) return gostd::io::errUnexpectedEOF;
			off += n;
		}
		return nullptr;
	}

private:
	gostd::io::Writer* w_;
	std::string buf_;
};

// NewMessagePackProtocol — protocol_msgpack.go:49.
MessagePackProtocol::MessagePackProtocol(gostd::io::ReadWriter* rw)
    : rw_(rw), r(std::make_unique<BufReader>(rw)),
      w(std::make_unique<BufWriter>(rw)) {}

std::shared_ptr<MessagePackProtocol> NewMessagePackProtocol(
    gostd::io::ReadWriter* rw) {
	return std::make_shared<MessagePackProtocol>(rw);
}

namespace {
// rwcAdapter adapts a ReadWriteCloser to the io.ReadWriter param — Go's
// ReadWriteCloser satisfies io.ReadWriter implicitly.
struct rwcAdapter : gostd::io::ReadWriter {
	std::shared_ptr<gostd::io::ReadWriteCloser> rwc;
	explicit rwcAdapter(std::shared_ptr<gostd::io::ReadWriteCloser> r)
	    : rwc(std::move(r)) {}
	std::pair<int, gostd::Error> read(std::span<char> buf) override {
		return rwc->read(buf);
	}
	std::pair<int, gostd::Error> write(std::string_view data) override {
		return rwc->write(data);
	}
};
} // namespace

std::shared_ptr<MessagePackProtocol> NewMessagePackProtocol(
    std::shared_ptr<gostd::io::ReadWriteCloser> rwc) {
	auto adapter = std::make_shared<rwcAdapter>(std::move(rwc));
	auto p = std::make_shared<MessagePackProtocol>(adapter.get());
	p->ownedRw_ = adapter;
	return p;
}

// ReadMessage — protocol_msgpack.go:56. Converts msgpack message types into
// JSON-RPC messages.
std::pair<ipc::Message*, gostd::Error> MessagePackProtocol::ReadMessage() {
	auto [msgType, method, payload, err] = readTuple();
	if (err) {
		return {nullptr, err};
	}

	// Convert msgpack message type to JSON-RPC message
	auto msg = std::make_unique<ipc::Message>();

	switch (msgType) {
	case MessageType::Request:
		// Client request - needs an ID for response
		// We use the method as a pseudo-ID since this protocol doesn't have explicit IDs
		msg->Id = jsonrpc::NewIDString(method);
		msg->Method = method;
		msg->Params = json::Value(std::move(payload));
		break;
	case MessageType::CallResponse:
		// Response to our Call - use method as ID
		// Note: Method must be empty for IsResponse() to return true
		msg->Id = jsonrpc::NewIDString(method);
		msg->Result = json::Value(std::move(payload));
		break;
	case MessageType::CallError:
		// Error response to our Call
		// Note: Method must be empty for IsResponse() to return true
		msg->Id = jsonrpc::NewIDString(method);
		msg->Error = jsonrpc::ResponseError{jsonrpc::CodeInternalError,
		                                    std::move(payload), json::Value{}};
		break;
	default:
		return {nullptr,
		        gostd::errorf("unexpected message type: %d",
		                      {static_cast<int64_t>(msgType)})};
	}

	return {msg.release(), nullptr};
}

// readTuple — protocol_msgpack.go:92.
std::tuple<MessageType, std::string, std::string, gostd::Error>
MessagePackProtocol::readTuple() {
	// Read fixed array marker (0x93 = 3-element array)
	auto [t, err] = r->readByte();
	if (err) {
		return {MessageType::Unknown, "", "", err};
	}
	if (t != msgpackFixedArray3) {
		return {MessageType::Unknown, "", "",
		        gostd::errorf("%w: expected fixed 3-element array (0x93), received: 0x%x",
		                      {ErrInvalidRequest, std::string(1, static_cast<char>(t))})};
	}

	// Read message type - can be positive fixint (0x00-0x7F) or uint8 (0xCC + value)
	auto [t2, err2] = r->readByte();
	if (err2) {
		return {MessageType::Unknown, "", "", err2};
	}
	uint8_t rawType;
	if (t2 <= 0x7F) {
		// Positive fixint - the byte IS the value
		rawType = t2;
	} else if (t2 == msgpackU8) {
		// uint8 marker - next byte is the value
		auto [b, e] = r->readByte();
		if (e) {
			return {MessageType::Unknown, "", "", e};
		}
		rawType = b;
	} else {
		return {MessageType::Unknown, "", "",
		        gostd::errorf("%w: expected positive fixint or uint8 marker, received: 0x%x",
		                      {ErrInvalidRequest, std::string(1, static_cast<char>(t2))})};
	}
	MessageType msgType = static_cast<MessageType>(rawType);
	if (!IsValid(msgType)) {
		return {MessageType::Unknown, "", "",
		        gostd::errorf("%w: unknown message type: %d",
		                      {ErrInvalidRequest, static_cast<int64_t>(msgType)})};
	}

	// Read method (binary)
	auto [methodBytes, err3] = readBin();
	if (err3) {
		return {MessageType::Unknown, "", "", err3};
	}
	std::string method = std::move(methodBytes);

	// Read payload (binary)
	auto [payload, err4] = readBin();
	if (err4) {
		return {MessageType::Unknown, "", "", err4};
	}

	return {msgType, std::move(method), std::move(payload), nullptr};
}

// readBin — protocol_msgpack.go:144.
std::pair<std::string, gostd::Error> MessagePackProtocol::readBin() {
	auto [t, err] = r->readByte();
	if (err) {
		return {"", err};
	}

	uint32_t size;
	switch (t) {
	case msgpackBin8: {
		auto [b, e] = r->readByte();
		if (e) return {"", e};
		size = b;
		break;
	}
	case msgpackBin16: {
		std::string tmp;
		if (auto e = r->readFull(tmp, 2); e) return {"", e};
		size = (static_cast<uint16_t>(static_cast<uint8_t>(tmp[0])) << 8) |
		       static_cast<uint8_t>(tmp[1]);
		break;
	}
	case msgpackBin32: {
		std::string tmp;
		if (auto e = r->readFull(tmp, 4); e) return {"", e};
		size = (static_cast<uint32_t>(static_cast<uint8_t>(tmp[0])) << 24) |
		       (static_cast<uint32_t>(static_cast<uint8_t>(tmp[1])) << 16) |
		       (static_cast<uint32_t>(static_cast<uint8_t>(tmp[2])) << 8) |
		       static_cast<uint8_t>(tmp[3]);
		break;
	}
	default:
		return {"", gostd::errorf("%w: expected binary data (0xc4-0xc6), received: 0x%x",
		                          {ErrInvalidRequest, std::string(1, static_cast<char>(t))})};
	}

	std::string payload;
	if (auto e = r->readFull(payload, size); e) {
		return {"", e};
	}
	return {std::move(payload), nullptr};
}

// WriteRequest — protocol_msgpack.go:182. For msgpack protocol, requests from
// server are "Call" type.
gostd::Error MessagePackProtocol::WriteRequest(const jsonrpc::ID* id,
                                               std::string_view method,
                                               const json::Value& params) {
	// Go: json.Marshal(params). params is already-marshaled JSON text; an
	// empty value encodes as null like a Go nil.
	return writeTuple(MessageType::Call, method,
	                  params.empty() ? std::string_view("null") : params);
}

// WriteNotification — protocol_msgpack.go:191. Msgpack protocol doesn't
// distinguish notifications from calls.
gostd::Error MessagePackProtocol::WriteNotification(std::string_view method,
                                                    const json::Value& params) {
	return WriteRequest(nullptr, method, params);
}

// WriteResponse — protocol_msgpack.go:196.
gostd::Error MessagePackProtocol::WriteResponse(const jsonrpc::ID* id,
                                                const json::Value& result) {
	std::string method;
	if (id != nullptr) {
		method = id->String();
	}
	// Go: json.Marshal(result) — already-JSON text passes through verbatim;
	// empty encodes as null.
	return writeTuple(MessageType::Response, method,
	                  result.empty() ? std::string_view("null") : result);
}

// WriteResponseRaw — the Go `result.(RawBinary)` branch of WriteResponse:
// binary payload written directly instead of being JSON-encoded.
gostd::Error MessagePackProtocol::WriteResponseRaw(const jsonrpc::ID* id,
                                                   const RawBinary& result) {
	std::string method;
	if (id != nullptr) {
		method = id->String();
	}
	return writeTuple(MessageType::Response, method, result);
}

// WriteError — protocol_msgpack.go:216.
gostd::Error MessagePackProtocol::WriteError(const jsonrpc::ID* id,
                                             const jsonrpc::ResponseError* respErr) {
	std::string method;
	if (id != nullptr) {
		method = id->String();
	}
	return writeTuple(MessageType::Error, method, respErr->Message);
}

// writeTuple — protocol_msgpack.go:225.
gostd::Error MessagePackProtocol::writeTuple(MessageType msgType,
                                             std::string_view method,
                                             std::string_view payload) {
	// Write fixed array marker
	if (auto err = w->writeByte(msgpackFixedArray3); err) {
		return err;
	}
	// Write message type as positive fixint (values 0-127 are written directly)
	if (auto err = w->writeByte(static_cast<uint8_t>(msgType)); err) {
		return err;
	}
	// Write method
	if (auto err = writeBin(method); err) {
		return err;
	}
	// Write payload
	if (auto err = writeBin(payload); err) {
		return err;
	}
	return w->flush();
}

// writeBin — protocol_msgpack.go:243.
gostd::Error MessagePackProtocol::writeBin(std::string_view data) {
	size_t length = data.size();
	if (length < 256) {
		if (auto err = w->writeByte(msgpackBin8); err) {
			return err;
		}
		if (auto err = w->writeByte(static_cast<uint8_t>(length)); err) {
			return err;
		}
	} else if (length < (1u << 16)) {
		if (auto err = w->writeByte(msgpackBin16); err) {
			return err;
		}
		// binary.Write(p.w, binary.BigEndian, uint16(length))
		if (auto err = w->writeByte(static_cast<uint8_t>(length >> 8)); err) {
			return err;
		}
		if (auto err = w->writeByte(static_cast<uint8_t>(length)); err) {
			return err;
		}
	} else {
		if (auto err = w->writeByte(msgpackBin32); err) {
			return err;
		}
		// binary.Write(p.w, binary.BigEndian, uint32(length))
		if (auto err = w->writeByte(static_cast<uint8_t>(length >> 24)); err) {
			return err;
		}
		if (auto err = w->writeByte(static_cast<uint8_t>(length >> 16)); err) {
			return err;
		}
		if (auto err = w->writeByte(static_cast<uint8_t>(length >> 8)); err) {
			return err;
		}
		if (auto err = w->writeByte(static_cast<uint8_t>(length)); err) {
			return err;
		}
	}
	return w->write(data);
}

}  // namespace tsc::api
