// Port of tsc/internal/printer/namegenerator.go — NameGenerator.
#include "internal/printer/emitcontext.h"
#include "internal/printer/printer.h"

#include "internal/ast/ast.h"

#include <cassert>
#include <cstdio>

namespace tsc::printer {

void NameGenerator::PushScope(bool reuseTempVariableScope) {
	nameGenerationScope* oldPrivate = privateNameScope;
	scopePool.emplace_back();
	nameGenerationScope* s = &scopePool.back();
	s->next = oldPrivate;
	privateNameScope = s;
	if (!reuseTempVariableScope) {
		nameGenerationScope* oldPublic = nameScope;
		scopePool.emplace_back();
		nameGenerationScope* s = &scopePool.back();
		s->next = oldPublic;
		nameScope = s;
	}
}

void NameGenerator::PopScope(bool reuseTempVariableScope) {
	if (privateNameScope != nullptr) {
		privateNameScope = privateNameScope->next;
	}
	if (!reuseTempVariableScope && nameScope != nullptr) {
		nameScope = nameScope->next;
	}
}

nameGenerationScope** NameGenerator::getScope(bool privateName) {
	return privateName ? &privateNameScope : &nameScope;
}

tempFlags NameGenerator::getTempFlags(bool privateName) {
	nameGenerationScope** scope = getScope(privateName);
	if (*scope != nullptr) {
		return (*scope)->tempFlags_;
	}
	return tempFlagsAuto;
}

void NameGenerator::setTempFlags(bool privateName, tempFlags flags) {
	nameGenerationScope** scope = getScope(privateName);
	if (*scope == nullptr) {
		scopePool.emplace_back();
		*scope = &scopePool.back();
	}
	(*scope)->tempFlags_ = flags;
}

// Gets the TempFlags to use in the current nameGenerationScope for the given
// key
tempFlags NameGenerator::getTempFlagsForFormattedName(
	bool privateName, const std::string& formattedNameKey) {
	nameGenerationScope** scope = getScope(privateName);
	if (*scope != nullptr) {
		if (auto it = (*scope)->formattedNameTempFlags.find(formattedNameKey);
		    it != (*scope)->formattedNameTempFlags.end()) {
			return it->second;
		}
	}
	return tempFlagsAuto;
}

// Sets the TempFlags to use in the current nameGenerationScope for the given
// key
void NameGenerator::setTempFlagsForFormattedName(
	bool privateName, const std::string& formattedNameKey, tempFlags flags) {
	nameGenerationScope** scope = getScope(privateName);
	if (*scope == nullptr) {
		scopePool.emplace_back();
		*scope = &scopePool.back();
	}
	(*scope)->formattedNameTempFlags[formattedNameKey] = flags;
}

void NameGenerator::reserveName(const std::string& name, bool privateName,
                                bool scoped, bool temp) {
	nameGenerationScope** scope = getScope(privateName);
	if (*scope == nullptr) {
		scopePool.emplace_back();
		*scope = &scopePool.back();
	}
	if (privateName || scoped) {
		(*scope)->reservedNames.insert(name);
	} else if (!temp) {
		generatedNames.insert(name); // NOTE: Matches Strada, but is incorrect.
	}
}

// Generate the text for a generated identifier or private identifier
std::string NameGenerator::GenerateName(Node* name) {
	if (Context != nullptr) {
		if (auto it = Context->autoGenerate.find(name);
		    it != Context->autoGenerate.end()) {
			AutoGenerateInfo& autoGenerate = it->second;
			if (generatedIdentifierFlagsIsNode(autoGenerate.Flags)) {
				// Node names generate unique names based on their original node
				// and are cached based on that node's id.
				return generateNameForNodeCached(
					Context->getNodeForGeneratedName(name),
					isPrivateIdentifier(name), autoGenerate.Flags,
					autoGenerate.Prefix, autoGenerate.Suffix);
			} else {
				// Auto, Loop, and Unique names are cached based on their
				// unique autoGenerateId.
				if (auto jt = autoGeneratedIdToGeneratedName.find(
					    autoGenerate.Id);
				    jt != autoGeneratedIdToGeneratedName.end()) {
					return jt->second;
				}
				std::string autoGeneratedName = makeName(name);
				autoGeneratedIdToGeneratedName[autoGenerate.Id] =
					autoGeneratedName;
				return autoGeneratedName;
			}
		}
	}
	return GetTextOfNode(name);
}

std::string NameGenerator::generateNameForNodeCached(
	Node* node, bool privateName, GeneratedIdentifierFlags flags,
	const std::string& prefix, const std::string& suffix) {
	NodeId nodeId = getNodeId(node);
	auto& cache =
		privateName ? nodeIdToGeneratedPrivateName : nodeIdToGeneratedName;

	if (auto it = cache.find(nodeId); it != cache.end()) {
		return it->second;
	}

	std::string name =
		generateNameForNode(node, privateName, flags, prefix, suffix);
	cache[nodeId] = name;
	return name;
}

std::string NameGenerator::generateNameForNode(Node* node, bool privateName,
                                             GeneratedIdentifierFlags flags,
                                             const std::string& prefix,
                                             const std::string& suffix) {
	switch (node->kind) {
		case Kind::Identifier:
		case Kind::PrivateIdentifier:
			return makeUniqueName(GetTextOfNode(node),
			                      {} /*checkFn*/, generatedIdentifierFlagsIsOptimistic(flags),
			                      generatedIdentifierFlagsIsReservedInNestedScopes(flags), privateName,
			                      prefix, suffix);
		case Kind::ModuleDeclaration:
		case Kind::EnumDeclaration:
			if (privateName || !prefix.empty() || !suffix.empty()) {
				TSC_UNREACHABLE(
					"Generated name for a module or enum cannot be private "
					"and may have neither a prefix nor suffix");
			}
			return generateNameForModuleOrEnum(node);
		case Kind::ImportDeclaration:
		case Kind::JSImportDeclaration:
		case Kind::ExportDeclaration:
			if (privateName || !prefix.empty() || !suffix.empty()) {
				TSC_UNREACHABLE(
					"Generated name for an import or export cannot be "
					"private and may have neither a prefix nor suffix");
			}
			return generateNameForImportOrExportDeclaration(node);
		case Kind::FunctionDeclaration:
		case Kind::ClassDeclaration: {
			if (privateName || !prefix.empty() || !suffix.empty()) {
				TSC_UNREACHABLE(
					"Generated name for a class or function declaration "
					"cannot be private and may have neither a prefix nor "
					"suffix");
			}
			Node* name = node->name();
			// NOTE: preserves the Go bug `g.Context == nil &&` (should be
			// `!=`) verbatim — namegenerator.go:173.
			if (name != nullptr &&
			    !(Context == nullptr && Context->hasAutoGenerateInfo(name))) {
				return generateNameForNode(name, false /*privateName*/, flags,
				                           "" /*prefix*/, "" /*suffix*/);
			}
			return generateNameForExportDefault();
		}
		case Kind::ExportAssignment:
			if (privateName || !prefix.empty() || !suffix.empty()) {
				TSC_UNREACHABLE(
					"Generated name for an export assignment cannot be "
					"private and may have neither a prefix nor suffix");
			}
			return generateNameForExportDefault();
		case Kind::ClassExpression:
			if (privateName || !prefix.empty() || !suffix.empty()) {
				TSC_UNREACHABLE(
					"Generated name for a class expression cannot be "
					"private and may have neither a prefix nor suffix");
			}
			return generateNameForClassExpression();
		case Kind::MethodDeclaration:
		case Kind::GetAccessor:
		case Kind::SetAccessor:
			return generateNameForMethodOrAccessor(node, privateName, prefix,
			                                       suffix);
		case Kind::ComputedPropertyName:
			return makeTempVariableName(tempFlagsAuto,
			                            true /*reservedInNestedScopes*/,
			                            privateName, prefix, suffix);
		default:
			return makeTempVariableName(tempFlagsAuto,
			                            false /*reservedInNestedScopes*/,
			                            privateName, prefix, suffix);
	}
}

std::string NameGenerator::generateNameForModuleOrEnum(
	Node* node /* ModuleDeclaration | EnumDeclaration */) {
	std::string name = GetTextOfNode(node->name());
	// Use module/enum name itself if it is unique, otherwise make a unique
	// variation
	if (isUniqueLocalName(name, node)) {
		return name;
	} else {
		return makeUniqueName(name, {} /*checkFn*/, false /*optimistic*/,
		                      false /*scoped*/, false /*privateName*/,
		                      "" /*prefix*/, "" /*suffix*/);
	}
}

std::string NameGenerator::generateNameForImportOrExportDeclaration(
	Node* node /* ImportDeclaration | ExportDeclaration */) {
	Node* expr = getExternalModuleName(node);
	std::string baseName = "module";
	if (isStringLiteral(expr)) {
		baseName = makeIdentifierFromModuleName(expr->text());
	}
	return makeUniqueName(baseName, {} /*checkFn*/, false /*optimistic*/,
	                      false /*scoped*/, false /*privateName*/,
	                      "" /*prefix*/, "" /*suffix*/);
}

std::string NameGenerator::generateNameForExportDefault() {
	return makeUniqueName("default", {} /*checkFn*/, false /*optimistic*/,
	                      false /*scoped*/, false /*privateName*/,
	                      "" /*prefix*/, "" /*suffix*/);
}

std::string NameGenerator::generateNameForClassExpression() {
	return makeUniqueName("class", {} /*checkFn*/, false /*optimistic*/,
	                      false /*scoped*/, false /*privateName*/,
	                      "" /*prefix*/, "" /*suffix*/);
}

std::string NameGenerator::generateNameForMethodOrAccessor(
	Node* node /* MethodDeclaration | AccessorDeclaration */,
	bool privateName, const std::string& prefix, const std::string& suffix) {
	if (isIdentifier(node->name())) {
		return generateNameForNodeCached(node->name(), privateName,
		                                 GeneratedIdentifierFlagsNone, prefix,
		                                 suffix);
	}
	return makeTempVariableName(tempFlagsAuto, false /*reservedInNestedScopes*/,
	                            privateName, prefix, suffix);
}

std::string NameGenerator::makeName(Node* name) {
	if (Context != nullptr) {
		if (auto it = Context->autoGenerate.find(name);
		    it != Context->autoGenerate.end()) {
			AutoGenerateInfo& autoGenerate = it->second;
			switch (generatedIdentifierFlagsKind(autoGenerate.Flags)) {
				case GeneratedIdentifierFlagsAuto:
					return makeTempVariableName(
						tempFlagsAuto,
						generatedIdentifierFlagsIsReservedInNestedScopes(autoGenerate.Flags),
						isPrivateIdentifier(name), autoGenerate.Prefix,
						autoGenerate.Suffix);
				case GeneratedIdentifierFlagsLoop:
					assert(isIdentifier(name));
					return makeTempVariableName(
						tempFlags_i,
						generatedIdentifierFlagsIsReservedInNestedScopes(autoGenerate.Flags),
						false /*privateName*/, autoGenerate.Prefix,
						autoGenerate.Suffix);
				case GeneratedIdentifierFlagsUnique:
					return makeUniqueName(
						name->text(),
						generatedIdentifierFlagsIsFileLevel(autoGenerate.Flags)
							? IsFileLevelUniqueNameInCurrentFile
							: std::function<bool(const std::string&, bool)>{},
						generatedIdentifierFlagsIsOptimistic(autoGenerate.Flags),
						generatedIdentifierFlagsIsReservedInNestedScopes(autoGenerate.Flags),
						isPrivateIdentifier(name), autoGenerate.Prefix,
						autoGenerate.Suffix);
			}
		}
	}
	return GetTextOfNode(name);
}

// Return the next available name in the pattern _a ... _z, _0, _1, ...
// TempFlags._i may be used to express a preference for that dedicated name.
// Note that names generated by makeTempVariableName and makeUniqueName will
// never conflict.
std::string NameGenerator::makeTempVariableName(tempFlags flags,
                                                bool reservedInNestedScopes,
                                                bool privateName,
                                                const std::string& prefix,
                                                const std::string& suffix) {
	tempFlags currentTempFlags;
	std::string key;
	bool simple = prefix.empty() && suffix.empty();
	if (simple) {
		currentTempFlags = getTempFlags(privateName);
	} else {
		// Generate a key to use to acquire a TempFlags counter based on the
		// fixed portions of the generated name.
		key = FormatGeneratedName(privateName, prefix, "" /*base*/, suffix);
		if (privateName) {
			key = ensureLeadingHash(key);
		}
		currentTempFlags = getTempFlagsForFormattedName(privateName, key);
	}

	if (flags != 0 && (currentTempFlags & flags) == 0) {
		std::string fullName =
			FormatGeneratedName(privateName, prefix, "_i", suffix);
		if (isUniqueName(fullName, privateName)) {
			currentTempFlags |= flags;
			reserveName(fullName, privateName, reservedInNestedScopes,
			            true /*temp*/);
			if (simple) {
				setTempFlags(privateName, currentTempFlags);
			} else {
				setTempFlagsForFormattedName(privateName, key,
				                             currentTempFlags);
			}
			return fullName;
		}
	}

	for (;;) {
		tempFlags count = currentTempFlags & tempFlagsCountMask;
		currentTempFlags++;
		// Skip over 'i' and 'n'
		if (count != 8 && count != 13) {
			std::string name;
			if (count < 26) {
				char buf[4];
				std::snprintf(buf, sizeof buf, "_%c",
				              static_cast<char>('a' + count));
				name = buf;
			} else {
				char buf[16];
				std::snprintf(buf, sizeof buf, "_%d",
				              static_cast<int>(count) - 26);
				name = buf;
			}
			std::string fullName =
				FormatGeneratedName(privateName, prefix, name, suffix);
			if (isUniqueName(fullName, privateName)) {
				reserveName(fullName, privateName, reservedInNestedScopes,
				            true /*temp*/);
				if (simple) {
					setTempFlags(privateName, currentTempFlags);
				} else {
					setTempFlagsForFormattedName(privateName, key,
					                             currentTempFlags);
				}
				return fullName;
			}
		}
	}
}

// Generate a name that is unique within the current file and doesn't conflict
// with any names in global scope. The name is formed by adding an '_n' suffix
// to the specified base name, where n is a positive integer. Note that names
// generated by makeTempVariableName and makeUniqueName are guaranteed to never
// conflict. If `optimistic` is set, the first instance will use 'baseName'
// verbatim instead of 'baseName_1'
std::string NameGenerator::makeUniqueName(
	const std::string& baseName,
	const std::function<bool(const std::string&, bool)>& checkFn,
	bool optimistic, bool scoped, bool privateName, const std::string& prefix,
	const std::string& suffix) {
	std::string base = removeLeadingHash(baseName);
	if (optimistic) {
		std::string fullName =
			FormatGeneratedName(privateName, prefix, base, suffix);
		if (checkUniqueName(fullName, privateName, checkFn)) {
			reserveName(fullName, privateName, scoped, false /*temp*/);
			return fullName;
		}
	}

	// Find the first unique 'name_n', where n is a positive integer
	if (!base.empty() && base.back() != '_') {
		base += "_";
	}

	int i = 1;
	for (;;) {
		std::string fullName = FormatGeneratedName(
			privateName, prefix,
			base + std::to_string(i), suffix);
		if (checkUniqueName(fullName, privateName, checkFn)) {
			reserveName(fullName, privateName, scoped, false /*temp*/);
			return fullName;
		}
		i++;
	}
}

std::string NameGenerator::MakeFileLevelOptimisticUniqueName(
	const std::string& name) {
	return makeUniqueName(name, IsFileLevelUniqueNameInCurrentFile,
	                      true /*optimistic*/, false /*scoped*/,
	                      false /*privateName*/, "" /*prefix*/, "" /*suffix*/);
}

bool NameGenerator::checkUniqueName(
	const std::string& name, bool privateName,
	const std::function<bool(const std::string&, bool)>& checkFn) {
	if (checkFn) {
		return checkFn(name, privateName);
	} else {
		return isUniqueName(name, privateName);
	}
}

Node* nextContainer(Node* node) {
	LocalsContainerDataRef data = node->localsContainerData();
	if (data.nextContainer != nullptr) {
		return *data.nextContainer;
	}
	return nullptr;
}

bool isUniqueLocalName(const std::string& name, Node* container) {
	Node* node = container;
	while (node != nullptr && isNodeDescendantOf(node, container) &&
	       node->localsContainerData().nextContainer != nullptr) {
		SymbolTable* locals = node->locals();
		if (locals != nullptr) {
			// We conservatively include alias symbols to cover cases where
			// they're emitted as locals
			if (auto it = locals->find(name);
			    it != locals->end() &&
			    (it->second->flags & (SymbolFlagsValue |
			                          SymbolFlagsExportValue |
			                          SymbolFlagsAlias)) != 0) {
				return false;
			}
		}
		node = nextContainer(node);
	}
	return true;
}

bool NameGenerator::isUniqueName(const std::string& name, bool privateName) {
	return (!IsFileLevelUniqueNameInCurrentFile ||
	        IsFileLevelUniqueNameInCurrentFile(name, privateName)) &&
	       !isReservedName(name, privateName);
}

bool NameGenerator::isReservedName(const std::string& name, bool privateName) {
	nameGenerationScope** scope = getScope(privateName);

	// NOTE: The following matches Strada, but is incorrect.
	if (generatedNames.count(name) != 0) {
		return true;
	}

	while (*scope != nullptr) {
		if ((*scope)->reservedNames.count(name) != 0) {
			return true;
		}
		scope = &(*scope)->next;
	}
	return false;
}

} // namespace tsc::printer
