// bundled.h — port of tsc/internal/bundled (bundled.go + embed.go, embedded
// variant — our build embeds lib contents like the Go default build).
#pragma once

#include <memory>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

#include "internal/vfs/vfs.h"

namespace tsc::bundled {

// Embedded — bundled.go:20. True: lib files live in embeddedContents.
inline constexpr bool Embedded = true;

// LibNames — libs_generated.go (generated by genbundled.py).
extern const std::vector<std::string> LibNames;

// embeddedContents — embed_generated.go (generated by genbundled.py).
// Keys are "libs/<name>".
extern const std::unordered_map<std::string, std::string_view> embeddedContents;

// WrapFS returns an FS which redirects embedded paths to the embedded file
// system. — bundled.go:24
std::shared_ptr<vfs::FS> WrapFS(std::shared_ptr<vfs::FS> fs);

// LibPath returns the path to the directory containing the bundled lib.d.ts
// files. — bundled.go:33 (embedded variant: "bundled:///libs")
std::string LibPath();

// IsBundled — embed.go:24.
bool IsBundled(const std::string& path);

// TestingLibPath — bundled.go:52. Only valid where the source tree is
// available (resolved relative to the generated file's location).
std::string TestingLibPath();

} // namespace tsc::bundled
