// bundled.cpp — port of tsc/internal/bundled/{bundled.go,embed.go} (embedded
// variant — contents generated by genbundled.py).

#include "internal/bundled/bundled.h"

#include <chrono>
#include <filesystem>

#include "internal/ast/ast.h"
#include "internal/gostd/gostd.h"
#include "internal/tspath/tspath.h"

namespace tsc::bundled {
namespace {

const std::string scheme = "bundled:///";

// splitPath — embed.go:15.
std::pair<std::string, bool> splitPath(const std::string& path) {
	if (path.starts_with(scheme)) {
		return {path.substr(scheme.size()), true};
	}
	return {"", false};
}

// fileInfo — embed.go:129 (implements fs.FileInfo + fs.DirEntry).
struct fileInfo : vfs::FileInfo {
	vfs::FileMode mode;
	std::string name;
	int64_t size = 0;

	fileInfo(vfs::FileMode mode, std::string name, int64_t size)
	    : mode(mode), name(std::move(name)), size(size) {}

	bool IsDir() const override { return mode.IsDir(); }
	vfs::TimePoint ModTime() const override { return vfs::TimePoint{}; }
	vfs::FileMode Mode() const override { return mode; }
	std::string Name() const override { return name; }
	int64_t Size() const override { return size; }
	std::any Sys() const override { return {}; }
};

// wrappedFS — embed.go:37. Implemented directly over vfs::FS (Go comment:
// our vfs works with strings, matching go:embed).
struct wrappedFS : vfs::FS {
	std::shared_ptr<vfs::FS> fs;
	explicit wrappedFS(std::shared_ptr<vfs::FS> fs) : fs(std::move(fs)) {}

	bool UseCaseSensitiveFileNames() override {
		return fs->UseCaseSensitiveFileNames();
	}

	bool FileExists(const std::string& path) override {
		if (auto [rest, ok] = splitPath(path); ok) {
			return embeddedContents.contains(rest);
		}
		return fs->FileExists(path);
	}

	std::pair<std::string, bool> ReadFile(const std::string& path) override {
		if (auto [rest, ok] = splitPath(path); ok) {
			if (auto it = embeddedContents.find(rest);
			    it != embeddedContents.end()) {
				return {std::string(it->second), true};
			}
			return {"", false};
		}
		return fs->ReadFile(path);
	}

	bool DirectoryExists(const std::string& path) override {
		if (auto [rest, ok] = splitPath(path); ok) {
			return rest == "libs";
		}
		return fs->DirectoryExists(path);
	}

	vfs::Entries GetAccessibleEntries(const std::string& path) override {
		vfs::Entries result;
		if (auto [rest, ok] = splitPath(path); ok) {
			if (rest.empty()) {
				result.directories = {"libs"};
			} else if (rest == "libs") {
				result.files = LibNames;
			}
			return result;
		}
		return fs->GetAccessibleEntries(path);
	}

	std::shared_ptr<vfs::FileInfo> Stat(const std::string& path) override {
		if (auto [rest, ok] = splitPath(path); ok) {
			if (rest.empty() || rest == "libs") {
				return std::make_shared<fileInfo>(
					fileInfo{vfs::ModeDir, rest, 0});
			}
			if (auto it = embeddedContents.find(rest);
			    it != embeddedContents.end()) {
				auto libName = std::string(rest);
				if (libName.starts_with("libs/")) {
					libName.erase(0, 5); // strings.CutPrefix
				}
				return std::make_shared<fileInfo>(fileInfo{
					vfs::FileMode{}, libName,
					static_cast<int64_t>(it->second.size())});
			}
			return nullptr;
		}
		return fs->Stat(path);
	}

	std::string Realpath(const std::string& path) override {
		if (auto [rest, ok] = splitPath(path); ok) {
			return path;
		}
		return fs->Realpath(path);
	}

	vfs::Error WriteFile(const std::string& path,
	                     const std::string& data) override {
		if (auto [rest, ok] = splitPath(path); ok) {
			TSC_UNREACHABLE("cannot write to embedded file system");
		}
		return fs->WriteFile(path, data);
	}

	vfs::Error AppendFile(const std::string& path,
	                      const std::string& data) override {
		if (auto [rest, ok] = splitPath(path); ok) {
			TSC_UNREACHABLE("cannot write to embedded file system");
		}
		return fs->AppendFile(path, data);
	}

	vfs::Error Remove(const std::string& path) override {
		if (auto [rest, ok] = splitPath(path); ok) {
			TSC_UNREACHABLE("cannot remove from embedded file system");
		}
		return fs->Remove(path);
	}

	vfs::Error Chtimes(const std::string& path, vfs::TimePoint aTime,
	                   vfs::TimePoint mTime) override {
		if (auto [rest, ok] = splitPath(path); ok) {
			TSC_UNREACHABLE("cannot change times on embedded file system");
		}
		return fs->Chtimes(path, aTime, mTime);
	}
};

} // namespace

// wrapFS — embed.go:46.
std::shared_ptr<vfs::FS> WrapFS(std::shared_ptr<vfs::FS> fs) {
	return std::make_shared<wrappedFS>(std::move(fs));
}

// libPath — embed.go:19 (sync.OnceValue; value is constant).
std::string LibPath() { return scheme + "libs"; }

// IsBundled — embed.go:24.
bool IsBundled(const std::string& path) {
	auto [rest, ok] = splitPath(path);
	return ok;
}

// testingLibPath — bundled.go:46. The source libs dir is resolved relative
// to this file's build-time location (<repo>/cpp/internal/bundled), matching
// runtime.Caller + filepath.Join(..., "libs").
std::string TestingLibPath() {
	static const std::string path = [] {
		namespace fs = std::filesystem;
		fs::path here = fs::path(__FILE__).parent_path(); // cpp/internal/bundled
		fs::path libs = here / ".." / ".." / ".." / "tsc" / "internal" /
		                "bundled" / "libs";
		return tspath::normalizeSlashes(libs.lexically_normal().string());
	}();
	return path;
}

} // namespace tsc::bundled
